# -*- coding: utf-8 -*-
"""Manba nomi (ingliz transliteratsiyasi) -> (hudud kodi, uz, ru)."""

HUDUD = {
 "QR": ("Qoraqalpog'iston", "Qoraqalpog'iston Respublikasi", "Каракалпакстан", "Республика Каракалпакстан"),
 "XO": ("Xorazm",           "Xorazm viloyati",               "Хорезм",         "Хорезмская область"),
 "BU": ("Buxoro",           "Buxoro viloyati",               "Бухара",         "Бухарская область"),
 "NV": ("Navoiy",           "Navoiy viloyati",               "Навои",          "Навоийская область"),
 "SA": ("Samarqand",        "Samarqand viloyati",            "Самарканд",      "Самаркандская область"),
 "QA": ("Qashqadaryo",      "Qashqadaryo viloyati",          "Кашкадарья",     "Кашкадарьинская область"),
 "SU": ("Surxondaryo",      "Surxondaryo viloyati",          "Сурхандарья",    "Сурхандарьинская область"),
 "JI": ("Jizzax",           "Jizzax viloyati",               "Джизак",         "Джизакская область"),
 "SI": ("Sirdaryo",         "Sirdaryo viloyati",             "Сырдарья",       "Сырдарьинская область"),
 "TS": ("Toshkent sh.",     "Toshkent shahri",               "г. Ташкент",     "город Ташкент"),
 "TV": ("Toshkent vil.",    "Toshkent viloyati",             "Ташкентская обл.", "Ташкентская область"),
 "NA": ("Namangan",         "Namangan viloyati",             "Наманган",       "Наманганская область"),
 "AN": ("Andijon",          "Andijon viloyati",              "Андижан",        "Андижанская область"),
 "FA": ("Farg'ona",         "Farg'ona viloyati",             "Фергана",        "Ферганская область"),
}

TUMAN = {
 # Qoraqalpog'iston Respublikasi
 "Amudarya":      ("QR", "Amudaryo tumani",     "Амударьинский район"),
 "Beruniy":       ("QR", "Beruniy tumani",      "Берунийский район"),
 "Chimbay":       ("QR", "Chimboy tumani",      "Чимбайский район"),
 "Ellikkala":     ("QR", "Ellikqal'a tumani",   "Элликкалинский район"),
 "Kanlikul":      ("QR", "Qonliko'l tumani",    "Канлыкульский район"),
 "Karauzyak":     ("QR", "Qorao'zak tumani",    "Караузякский район"),
 "Kegeyli":       ("QR", "Kegeyli tumani",      "Кегейлийский район"),
 "Khojeyli":      ("QR", "Xo'jayli tumani",     "Ходжейлийский район"),
 "Kungrad":       ("QR", "Qo'ng'irot tumani",   "Кунградский район"),
 "Muynak":        ("QR", "Mo'ynoq tumani",      "Муйнакский район"),
 "Nukus":         ("QR", "Nukus tumani",        "Нукусский район"),
 "Nukus city":    ("QR", "Nukus shahri",        "город Нукус"),
 "Shumanay":      ("QR", "Shumanay tumani",     "Шуманайский район"),
 "Takhtakupir":   ("QR", "Taxtako'pir tumani",  "Тахтакупырский район"),
 "Turtkul":       ("QR", "To'rtko'l tumani",    "Турткульский район"),
 # Xorazm viloyati
 "Bagat":         ("XO", "Bog'ot tumani",       "Багатский район"),
 "Gurlen":        ("XO", "Gurlan tumani",       "Гурленский район"),
 "Khanka":        ("XO", "Xonqa tumani",        "Ханкинский район"),
 "Khazarasp":     ("XO", "Hazorasp tumani",     "Хазараспский район"),
 "Khiva":         ("XO", "Xiva tumani",         "Хивинский район"),
 "Khiva city":    ("XO", "Xiva shahri",         "город Хива"),
 "Koshkupir":     ("XO", "Qo'shko'pir tumani",  "Кошкупырский район"),
 "Shavat":        ("XO", "Shovot tumani",       "Шаватский район"),
 "Urgench":       ("XO", "Urganch tumani",      "Ургенчский район"),
 "Urgench city":  ("XO", "Urganch shahri",      "город Ургенч"),
 "Yangiarik":     ("XO", "Yangiariq tumani",    "Янгиарыкский район"),
 "Yangibazar":    ("XO", "Yangibozor tumani",   "Янгибазарский район"),
 # Buxoro viloyati
 "Alat":          ("BU", "Olot tumani",         "Алатский район"),
 "Bukhara":       ("BU", "Buxoro tumani",       "Бухарский район"),
 "Bukhara city":  ("BU", "Buxoro shahri",       "город Бухара"),
 "Gijduvan":      ("BU", "G'ijduvon tumani",    "Гиждуванский район"),
 "Jondor":        ("BU", "Jondor tumani",       "Жондорский район"),
 # Manbada Kogon shahri va tumani geometriyasi almashgan: "Kagan" — shahar ichidagi
 # kichik anklav (1,9 km2), "Kagan city" — uni o'rab turgan tuman (470 km2).
 # Nom shu yerda to'g'rilanadi; qur.py oxiridagi nazorat buni tekshirib turadi.
 "Kagan":         ("BU", "Kogon shahri",        "город Каган"),
 "Kagan city":    ("BU", "Kogon tumani",        "Каганский район"),
 "Karakul":       ("BU", "Qorako'l tumani",     "Каракульский район"),
 "Karaulbazar":   ("BU", "Qorovulbozor tumani", "Караулбазарский район"),
 "Peshku":        ("BU", "Peshku tumani",       "Пешкунский район"),
 "Ramitan":       ("BU", "Romitan tumani",      "Ромитанский район"),
 "Shafirkan":     ("BU", "Shofirkon tumani",    "Шафирканский район"),
 "Vabkent":       ("BU", "Vobkent tumani",      "Вабкентский район"),
 # Navoiy viloyati
 "Kanimekh":      ("NV", "Konimex tumani",      "Канимехский район"),
 "Karmana":       ("NV", "Karmana tumani",      "Карманинский район"),
 "Khatirchi":     ("NV", "Xatirchi tumani",     "Хатырчинский район"),
 "Kiziltepa":     ("NV", "Qiziltepa tumani",    "Кызылтепинский район"),
 "Navbakhor":     ("NV", "Navbahor tumani",     "Навбахорский район"),
 "Navoi city":    ("NV", "Navoiy shahri",       "город Навои"),
 "Nurata":        ("NV", "Nurota tumani",       "Нуратинский район"),
 "Tamdi":         ("NV", "Tomdi tumani",        "Тамдынский район"),
 "Uchkuduk":      ("NV", "Uchquduq tumani",     "Учкудукский район"),
 "Zarafshan city":("NV", "Zarafshon shahri",    "город Зарафшан"),
 # Samarqand viloyati
 "Akdarya":       ("SA", "Oqdaryo tumani",      "Акдарьинский район"),
 "Bulungur":      ("SA", "Bulung'ur tumani",    "Булунгурский район"),
 "Dzhambay":      ("SA", "Jomboy tumani",       "Джамбайский район"),
 "Ishtikhan":     ("SA", "Ishtixon tumani",     "Иштыханский район"),
 "Kattakurgan":   ("SA", "Kattaqo'rg'on tumani","Каттакурганский район"),
 "Kattakurgan city":("SA","Kattaqo'rg'on shahri","город Каттакурган"),
 "Koshrabad":     ("SA", "Qo'shrabot tumani",   "Кошрабадский район"),
 "Narpay":        ("SA", "Narpay tumani",       "Нарпайский район"),
 "Nurabad":       ("SA", "Nurobod tumani",      "Нурабадский район"),
 "Pakhtachi":     ("SA", "Paxtachi tumani",     "Пахтачийский район"),
 "Pastdargom":    ("SA", "Pastdarg'om tumani",  "Пастдаргомский район"),
 "Payarik":       ("SA", "Payariq tumani",      "Пайарыкский район"),
 "Samarkand":     ("SA", "Samarqand tumani",    "Самаркандский район"),
 "Samarkand city":("SA", "Samarqand shahri",    "город Самарканд"),
 "Taylak":        ("SA", "Toyloq tumani",       "Тайлакский район"),
 "Urgut":         ("SA", "Urgut tumani",        "Ургутский район"),
 # Qashqadaryo viloyati
 "Chirakchi":     ("QA", "Chiroqchi tumani",    "Чиракчинский район"),
 "Dehkanabad":    ("QA", "Dehqonobod tumani",   "Дехканабадский район"),
 "Guzar":         ("QA", "G'uzor tumani",       "Гузарский район"),
 "Kamashi":       ("QA", "Qamashi tumani",      "Камашинский район"),
 "Karshi":        ("QA", "Qarshi tumani",       "Каршинский район"),
 "Karshi city":   ("QA", "Qarshi shahri",       "город Карши"),
 "Kasan":         ("QA", "Koson tumani",        "Касанский район"),
 "Kasbi":         ("QA", "Kasbi tumani",        "Касбийский район"),
 "Kitab":         ("QA", "Kitob tumani",        "Китабский район"),
 "Mirishkar":     ("QA", "Mirishkor tumani",    "Миришкорский район"),
 "Mubarek":       ("QA", "Muborak tumani",      "Мубарекский район"),
 "Nishan":        ("QA", "Nishon tumani",       "Нишанский район"),
 "Shakhrisabz":   ("QA", "Shahrisabz tumani",   "Шахрисабзский район"),
 "Shakhrisabz city":("QA","Shahrisabz shahri",  "город Шахрисабз"),
 "Yakkabag":      ("QA", "Yakkabog' tumani",    "Яккабагский район"),
 # Surxondaryo viloyati
 "Altinsay":      ("SU", "Oltinsoy tumani",     "Алтынсайский район"),
 "Angor":         ("SU", "Angor tumani",        "Ангорский район"),
 "Baysun":        ("SU", "Boysun tumani",       "Байсунский район"),
 "Denau":         ("SU", "Denov tumani",        "Денауский район"),
 "Dzharkurgan":   ("SU", "Jarqo'rg'on tumani",  "Джаркурганский район"),
 "Kizirik":       ("SU", "Qiziriq tumani",      "Кизирикский район"),
 "Kumkurgan":     ("SU", "Qumqo'rg'on tumani",  "Кумкурганский район"),
 "Muzrabad":      ("SU", "Muzrabot tumani",     "Музрабадский район"),
 "Sariasiya":     ("SU", "Sariosiyo tumani",    "Сариасийский район"),
 "Sherabad":      ("SU", "Sherobod tumani",     "Шерабадский район"),
 "Shurchi":       ("SU", "Sho'rchi tumani",     "Шурчинский район"),
 "Termez":        ("SU", "Termiz tumani",       "Термезский район"),
 "Termez city":   ("SU", "Termiz shahri",       "город Термез"),
 "Uzun":          ("SU", "Uzun tumani",         "Узунский район"),
 # Jizzax viloyati
 "Arnasay":       ("JI", "Arnasoy tumani",      "Арнасайский район"),
 "Bakhmal":       ("JI", "Baxmal tumani",       "Бахмальский район"),
 "Dustlik":       ("JI", "Do'stlik tumani",     "Дустликский район"),
 "Dzhizak city":  ("JI", "Jizzax shahri",       "город Джизак"),
 "Farish":        ("JI", "Forish tumani",       "Фаришский район"),
 "Gallyaaral":    ("JI", "G'allaorol tumani",   "Галляаральский район"),
 "Mirzachul":     ("JI", "Mirzacho'l tumani",   "Мирзачульский район"),
 "Paxtakor":      ("JI", "Paxtakor tumani",     "Пахтакорский район"),
 "Sharof Rashidov":("JI","Sharof Rashidov tumani","Шарофрашидовский район"),
 "Yangiabad":     ("JI", "Yangiobod tumani",    "Янгиабадский район"),
 "Zaamin":        ("JI", "Zomin tumani",        "Зааминский район"),
 "Zafarabad":     ("JI", "Zafarobod tumani",    "Зафарабадский район"),
 "Zarbdar":       ("JI", "Zarbdor tumani",      "Зарбдарский район"),
 # Sirdaryo viloyati
 "Akaltin":       ("SI", "Oqoltin tumani",      "Акалтынский район"),
 "Bayaut":        ("SI", "Boyovut tumani",      "Баяутский район"),
 "Gulistan":      ("SI", "Guliston tumani",     "Гулистанский район"),
 "Gulistan city": ("SI", "Guliston shahri",     "город Гулистан"),
 "Khavas":        ("SI", "Xovos tumani",        "Хавастский район"),
 "Mirzaabad":     ("SI", "Mirzaobod tumani",    "Мирзаабадский район"),
 "Sardoba":       ("SI", "Sardoba tumani",      "Сардобинский район"),
 "Saykhunabad":   ("SI", "Sayxunobod tumani",   "Сайхунабадский район"),
 "Shirin city":   ("SI", "Shirin shahri",       "город Ширин"),
 "Sirdarya":      ("SI", "Sirdaryo tumani",     "Сырдарьинский район"),
 "Yangiyer city": ("SI", "Yangiyer shahri",     "город Янгиер"),
 # Toshkent shahri
 "Almazar":       ("TS", "Olmazor tumani",      "Алмазарский район"),
 "Bektemir":      ("TS", "Bektemir tumani",     "Бектемирский район"),
 "Chilanzar":     ("TS", "Chilonzor tumani",    "Чиланзарский район"),
 "Mirabad":       ("TS", "Mirobod tumani",      "Мирабадский район"),
 "Mirzo Ulugbek": ("TS", "Mirzo Ulug'bek tumani","Мирзо-Улугбекский район"),
 "Sergeli":       ("TS", "Sergeli tumani",      "Сергелийский район"),
 "Shaykhantokhur":("TS", "Shayxontohur tumani", "Шайхантахурский район"),
 "Uchtepa":       ("TS", "Uchtepa tumani",      "Учтепинский район"),
 "Yakkasaray":    ("TS", "Yakkasaroy tumani",   "Яккасарайский район"),
 "Yangihayot":    ("TS", "Yangihayot tumani",  "Янгихаётский район"),
 "Yashnobod":     ("TS", "Yashnobod tumani",    "Яшнабадский район"),
 "Yunusabad":     ("TS", "Yunusobod tumani",    "Юнусабадский район"),
 # Toshkent viloyati
 "Akhangaran":    ("TV", "Ohangaron tumani",    "Ахангаранский район"),
 "Akhangaran city":("TV","Ohangaron shahri",    "город Ахангаран"),
 "Akkurgan":      ("TV", "Oqqo'rg'on tumani",   "Аккурганский район"),
 "Almalik city":  ("TV", "Olmaliq shahri",      "город Алмалык"),
 "Angren city":   ("TV", "Angren shahri",       "город Ангрен"),
 "Bekabad":       ("TV", "Bekobod tumani",      "Бекабадский район"),
 "Bekabad city":  ("TV", "Bekobod shahri",      "город Бекабад"),
 "Bostanlik":     ("TV", "Bo'stonliq tumani",   "Бостанлыкский район"),
 "Buka":          ("TV", "Bo'ka tumani",        "Букинский район"),
 "Chinaz":        ("TV", "Chinoz tumani",       "Чиназский район"),
 "Chirchik city": ("TV", "Chirchiq shahri",     "город Чирчик"),
 "Kibray":        ("TV", "Qibray tumani",       "Кибрайский район"),
 "Kuyichirchik":  ("TV", "Quyichirchiq tumani", "Куйичирчикский район"),
 "Nurafshon city":("TV", "Nurafshon shahri",    "город Нурафшан"),
 "Parkent":       ("TV", "Parkent tumani",      "Паркентский район"),
 "Pskent":        ("TV", "Piskent tumani",      "Пскентский район"),
 "Tashkent":      ("TV", "Toshkent tumani",     "Ташкентский район"),
 "Urtachirchik":  ("TV", "O'rtachirchiq tumani","Уртачирчикский район"),
 "Yangiyul":      ("TV", "Yangiyo'l tumani",    "Янгиюльский район"),
 "Yangiyul city": ("TV", "Yangiyo'l shahri",    "город Янгиюль"),
 "Yukarichirchik":("TV", "Yuqorichirchiq tumani","Юкоричирчикский район"),
 "Zangiata":      ("TV", "Zangiota tumani",     "Зангиатинский район"),
 # Namangan viloyati
 "Chartak":       ("NA", "Chortoq tumani",      "Чартакский район"),
 "Chust":         ("NA", "Chust tumani",        "Чустский район"),
 "Kasansay":      ("NA", "Kosonsoy tumani",     "Касансайский район"),
 "Mingbulak":     ("NA", "Mingbuloq tumani",    "Мингбулакский район"),
 "Namangan":      ("NA", "Namangan tumani",     "Наманганский район"),
 "Namangan city": ("NA", "Namangan shahri",     "город Наманган"),
 "Narin":         ("NA", "Norin tumani",        "Нарынский район"),
 "Pap":           ("NA", "Pop tumani",          "Папский район"),
 "Turakurgan":    ("NA", "To'raqo'rg'on tumani","Туракурганский район"),
 "Uchkurgan":     ("NA", "Uchqo'rg'on tumani",  "Учкурганский район"),
 "Uychi":         ("NA", "Uychi tumani",        "Уйчинский район"),
 "Yangikurgan":   ("NA", "Yangiqo'rg'on tumani","Янгикурганский район"),
 # Andijon viloyati
 "Altinkul":      ("AN", "Oltinko'l tumani",    "Алтынкульский район"),
 "Andijan":       ("AN", "Andijon tumani",      "Андижанский район"),
 "Andijan city":  ("AN", "Andijon shahri",      "город Андижан"),
 "Asaka":         ("AN", "Asaka tumani",        "Асакинский район"),
 "Balikchi":      ("AN", "Baliqchi tumani",     "Балыкчинский район"),
 "Boz":           ("AN", "Bo'z tumani",         "Бузский район"),
 "Bulakbashi":    ("AN", "Buloqboshi tumani",   "Булакбашинский район"),
 "Djalalkuduk":   ("AN", "Jalaquduq tumani",    "Джалакудукский район"),
 "Izboskan":      ("AN", "Izboskan tumani",     "Избасканский район"),
 "Khadjaabad":    ("AN", "Xo'jaobod tumani",    "Ходжаабадский район"),
 "Khanabad city": ("AN", "Xonobod shahri",      "город Ханабад"),
 "Kurgantepa":    ("AN", "Qo'rg'ontepa tumani", "Кургантепинский район"),
 "Markhamat":     ("AN", "Marhamat tumani",     "Мархаматский район"),
 "Paxtaabad":     ("AN", "Paxtaobod tumani",    "Пахтаабадский район"),
 "Shakhrixan":    ("AN", "Shahrixon tumani",    "Шахриханский район"),
 "Ulugnar":       ("AN", "Ulug'nor tumani",     "Улугнорский район"),
 # Farg'ona viloyati
 "Altiarik":      ("FA", "Oltiariq tumani",     "Алтыарыкский район"),
 "Bagdad":        ("FA", "Bag'dod tumani",      "Багдадский район"),
 "Besharik":      ("FA", "Beshariq tumani",     "Бешарыкский район"),
 "Buvayda":       ("FA", "Buvayda tumani",      "Бувайдинский район"),
 "Dangara":       ("FA", "Dang'ara tumani",     "Дангаринский район"),
 "Fergana":       ("FA", "Farg'ona tumani",     "Ферганский район"),
 "Fergana city":  ("FA", "Farg'ona shahri",     "город Фергана"),
 "Furkat":        ("FA", "Furqat tumani",       "Фуркатский район"),
 "Kokand city":   ("FA", "Qo'qon shahri",       "город Коканд"),
 "Kushtepa":      ("FA", "Qo'shtepa tumani",    "Куштепинский район"),
 "Kuva":          ("FA", "Quva tumani",         "Кувинский район"),
 "Kuvasay city":  ("FA", "Quvasoy shahri",      "город Кувасай"),
 "Margilan city": ("FA", "Marg'ilon shahri",    "город Маргилан"),
 "Rishtan":       ("FA", "Rishton tumani",      "Риштанский район"),
 "Sokh":          ("FA", "So'x tumani",         "Сохский район"),
 "Tashlak":       ("FA", "Toshloq tumani",      "Ташлакский район"),
 "Uchkuprik":     ("FA", "Uchko'prik tumani",   "Учкуприкский район"),
 "Uzbekistan":    ("FA", "O'zbekiston tumani",  "Узбекистанский район"),
 "Yazyavan":      ("FA", "Yozyovon tumani",     "Язъяванский район"),
}
