/* ============================================================
   Interfeys tili — ruscha variant lug'ati.
   Kalit: interfeysdagi o'zbekcha matn (aynan, bo'sh joysiz).
   Qiymat: ruscha muqobili. Kalit topilmasa matn o'zbekcha qoladi.
   Xos ismlar, manzillar va hujjat raqamlari ataylab tarjima qilinmaydi.
   ============================================================ */
window.MKB_LUGAT = {
 "180 kundan ortiq": "более 180 дней",
 "30 kungacha": "до 30 дней",
 "31–90 kun": "31–90 дней",
 "4 ekran": "4 экрана",
 "9 ekran": "9 экранов",
 "91–180 kun": "91–180 дней",
 "94% onlayn": "94% онлайн",
 "Admin": "Админ",
 "Administrator": "Администратор",
 "Administrator sifatida kirish →": "Войти как администратор →",
 "Agrokredit": "Агрокредит",
 "Algoritm": "Алгоритм",
 "Aloqa": "Связь",
 "Aloqa kanali": "Канал связи",
 "Aloqa kanallari va qurilmalar": "Каналы связи и устройства",
 "Aloqa yo'q": "Нет связи",
 "Amalda": "Действует",
 "Amallar": "Действия",
 "Arxivdan qidirish": "Поиск по архиву",
 "Arxivlash": "В архив",
 "Asosiy kirish": "Главный вход",
 "Asosiy ko'rsatkichlar": "Ключевые показатели",
 "Asosiy navigatsiya": "Основная навигация",
 "Asosiy qarz, foiz va penya bilan": "С основным долгом, процентами и пеней",
 "Asosiy rekvizitlar": "Основные реквизиты",
 "Audit jurnali": "Журнал аудита",
 "Auditor": "Аудитор",
 "Auksion": "Аукцион",
 "Auksion ishtirokchilari": "Участники аукциона",
 "Auksion natijasini rasmiylashtirish": "Оформление результата аукциона",
 "Auksion savdolari": "Аукционные торги",
 "Auksion tushumlari": "Поступления от аукционов",
 "Auksion va ijara tushumlari": "Поступления от аукционов и аренды",
 "Auksionda": "На аукционе",
 "Auksiondagi obyektlar ro'yxati": "Список объектов на аукционе",
 "Auksionga chiqarildi": "Выставлено на аукцион",
 "Auksionga chiqarish": "Выставление на аукцион",
 "Avtokredit": "Автокредит",
 "Avtomatik hisobotlar": "Автоматические отчёты",
 "Avtotransport": "Автотранспорт",
 "Avtoturargoh": "Автостоянка",
 "Axborot texnologiyalari departamenti": "Департамент информационных технологий",
 "Aylanma mablag' krediti": "Кредит на оборотные средства",
 "Baholangan qiymat": "Оценочная стоимость",
 "Baholangan qiymati": "Оценочная стоимость",
 "Baholash hisoboti": "Отчёт об оценке",
 "Band": "Занято",
 "Bandlik darajasi": "Уровень занятости",
 "Bank balansida": "На балансе банка",
 "Bank nazoratida": "Под контролем банка",
 "Bank nazoratidagi garov obyektlarini kechayu kunduz kuzatish va trevogalarga javob berish": "Круглосуточное наблюдение за залоговыми объектами банка и реагирование на тревоги",
 "Bank rahbariyati": "Руководство банка",
 "Barcha bildirishnomalar va yangiliklar markazi": "Центр всех уведомлений и новостей",
 "Barcha bosqichlar": "Все этапы",
 "Barcha eshiklar": "Все двери",
 "Barcha filiallar": "Все филиалы",
 "Barcha holatlar": "Все статусы",
 "Barcha hududlar": "Все регионы",
 "Barcha obyektlar": "Все объекты",
 "Barcha qurilmalar": "Все устройства",
 "Barcha turlar": "Все типы",
 "Barcha undiruv ishlari": "Все дела о взыскании",
 "Barcha viloyatlar": "Все области",
 "Barcha yillar": "Все годы",
 "Barchasi": "Все",
 "Barchasini ko'rish": "Смотреть все",
 "Barqaror": "Стабильно",
 "Bartaraf etilmoqda": "Устраняется",
 "Bekor qilish": "Отменить",
 "Belgilangan ko'riklar jadvali": "График назначенных осмотров",
 "Beqaror": "Нестабильно",
 "Bildirishnoma sozlamalari": "Настройки уведомлений",
 "Bildirishnomalar": "Уведомления",
 "Biriktirilgan shartnomalar": "Закреплённые договоры",
 "Biriktirish": "Прикрепить",
 "Bo'lim": "Отдел",
 "Bo'lim sahifalari": "Разделы",
 "Bo'limni tanlang": "Выберите отдел",
 "Bo'sh": "Свободно",
 "Bosh kirish eshigi": "Главная входная дверь",
 "Bosh sahifaga qaytish": "Вернуться на главную",
 "Boshlang'ich holat": "Начальный статус",
 "Boshqa qurilmalar": "Другие устройства",
 "Boshqaruv paneli": "Панель управления",
 "Boshqaruv raisi o'rinbosari": "Заместитель председателя правления",
 "Bosqich": "Этап",
 "Bosqichni o'zgartirish": "Изменение этапа",
 "Brifing varag'i": "Лист брифинга",
 "Bugungi faollik": "Активность за сегодня",
 "Bugungi mehmonlar": "Сегодняшние посетители",
 "Bugungi tashriflar": "Визиты за сегодня",
 "Bugungi tekshiruvlar": "Проверки за сегодня",
 "Chastota": "Периодичность",
 "Chiqish vaqti": "Время выхода",
 "Chiqishda xona tekshiruvi": "Проверка помещения при выходе",
 "Da'vo arizasi": "Исковое заявление",
 "Da'vo arizasi berildi": "Подано исковое заявление",
 "Da'vo arizasi berilgan ishlar": "Дела с поданным иском",
 "Da'vo va sud bosqichidagi ishlar": "Дела на исковой и судебной стадии",
 "Dala hovli": "Дача",
 "Dalolatnoma": "Акт",
 "Daromad dinamikasi": "Динамика поступлений",
 "Daromad tuzilmasi": "Структура поступлений",
 "Davom etish": "Продолжить",
 "Davr": "Период",
 "Dehqonchilik": "Земледелие",
 "Dinamik": "Динамик",
 "Diqqat": "Внимание",
 "Diqqat talab qiladi": "Требует внимания",
 "Doimiy saqlash rejimi.": "Режим постоянного хранения.",
 "Eksport": "Экспорт",
 "Elektr ta'minoti": "Электроснабжение",
 "Energiya samaradorligi": "Энергоэффективность",
 "Eshik": "Дверь",
 "Eshik kirish tizimi": "Система дверного доступа",
 "Eshiklarni masofadan boshqarish": "Дистанционное управление дверями",
 "Etaj rejasi": "План этажа",
 "Excel (XLSX)": "Excel (XLSX)",
 "Face ID / domofon qurilmasi": "Устройство Face ID / домофон",
 "Face ID natijasi": "Результат Face ID",
 "Face ID orqali eshik ochish": "Открыть дверь по Face ID",
 "FaceID skaner": "Сканер FaceID",
 "Faol": "Активен",
 "Faol sessiyalar": "Активные сессии",
 "Faoliyat tahlili": "Анализ деятельности",
 "Faoliyat tarixi": "История действий",
 "Faollik tarixi": "История активности",
 "Faqat o'qish rejimi": "Режим только для чтения",
 "Fayl hajmi": "Размер файла",
 "Filial": "Филиал",
 "Filtrlar": "Фильтры",
 "Firmware versiyasi": "Версия прошивки",
 "Foiz va penya": "Проценты и пеня",
 "Format": "Формат",
 "Foydalanuvchi ko'rinishida tekshirish": "Просмотр от имени пользователя",
 "Foydalanuvchi ma'lumotlari": "Данные пользователя",
 "Foydalanuvchi nomi va parolni kiriting": "Введите имя пользователя и пароль",
 "Foydalanuvchi nomi yoki email": "Имя пользователя или email",
 "Foydalanuvchilar": "Пользователи",
 "Foydalanuvchilar va rollar": "Пользователи и роли",
 "Galereya": "Галерея",
 "Garov aktivlari nazorati": "Контроль залоговых активов",
 "Garov aktivlarini nazorat qilish tizimi": "Система контроля залоговых активов",
 "Garov obyekti": "Залоговый объект",
 "Garov obyekti kartasi": "Карточка залогового объекта",
 "Garov obyektlari": "Залоговые объекты",
 "Garov obyektlari rentabelligi (ROA)": "Рентабельность залоговых объектов (ROA)",
 "Garov obyektlari reyestri": "Реестр залоговых объектов",
 "Garov portfeli": "Залоговый портфель",
 "Garov turlari": "Типы залога",
 "Garovda": "В залоге",
 "Gaz ta'minoti": "Газоснабжение",
 "Har chorakda": "Ежеквартально",
 "Har oyda": "Ежемесячно",
 "Hisobot davri": "Отчётный период",
 "Hisobot markazi": "Центр отчётности",
 "Hisobot nomi": "Название отчёта",
 "Hisobot turi": "Тип отчёта",
 "Hisobot yaratish": "Сформировать отчёт",
 "Hisobotlar": "Отчёты",
 "Hisobotlar markazi": "Центр отчётности",
 "Hodisa ochish": "Открыть происшествие",
 "Hodisa qo'shish": "Добавить происшествие",
 "Hodisalar": "Происшествия",
 "Hodisalar bo'yicha umumiy ko'rsatkichlar": "Сводные показатели по происшествиям",
 "Hodisalar dinamikasi": "Динамика происшествий",
 "Hodisalar markazi": "Центр происшествий",
 "Hodisalar xaritasi (O'zbekiston)": "Карта происшествий (Узбекистан)",
 "Holat": "Статус",
 "Holati": "Статус",
 "Hudud": "Регион",
 "Hududiy xarita": "Карта регионов",
 "Hujjat nomi": "Название документа",
 "Hujjat qo'shish": "Добавить документ",
 "Hujjat yuklash": "Загрузить документ",
 "Hujjatlar": "Документы",
 "Hujjatlar markazi": "Центр документов",
 "Hujjatlar topilmadi": "Документы не найдены",
 "ID raqam": "Идентификатор",
 "ID raqami": "Идентификатор",
 "IP Kamera": "IP-камера",
 "IP kamera": "IP-камера",
 "IP manzil": "IP-адрес",
 "Ichki eshik": "Внутренняя дверь",
 "Identifikatsiya": "Идентификация",
 "Ijarachi": "Арендатор",
 "Ijaraga berilgan": "Сдано в аренду",
 "Ijro hujjati muddatlari": "Сроки исполнительных документов",
 "Ijro varaqasi": "Исполнительный лист",
 "Ijro varaqasi MIBga topshirildi": "Исполнительный лист передан в МИБ",
 "Infratuzilma": "Инфраструктура",
 "Integratsiyalar": "Интеграции",
 "Interfeys tili": "Язык интерфейса",
 "Interkom izohi": "Комментарий интеркома",
 "Internet aloqasi yo'q": "Нет подключения к интернету",
 "Inventar raqami": "Инвентарный номер",
 "Investitsiya krediti": "Инвестиционный кредит",
 "Ipoteka krediti": "Ипотечный кредит",
 "Ish davomiyligi": "Длительность работы",
 "Ish hujjatlari": "Документы дела",
 "Ish jarayoni": "Рабочий процесс",
 "Ish maydoni": "Рабочая область",
 "Ishga kirish sanasi": "Дата приёма на работу",
 "Ishlab chiqarish": "Производство",
 "Ishlab chiqaruvchi": "Производитель",
 "Ishlash vaqti": "Время работы",
 "Ishlayapti": "Работает",
 "Iste'mol krediti (garov bilan)": "Потребительский кредит (под залог)",
 "Jami": "Итого",
 "Jami ochiq ishlar:": "Всего открытых дел:",
 "Jami qarzdorlar": "Всего должников",
 "Jami:": "Итого:",
 "Jarayon tarixi": "История процесса",
 "Jarayonda": "В процессе",
 "Javobgacha": "До реакции",
 "Jismoniy shaxs": "Физическое лицо",
 "Jonli": "В эфире",
 "Jonli aloqa": "Живая связь",
 "Jonli kamera": "Живая камера",
 "Jonli tashrif nazorati": "Контроль визитов в реальном времени",
 "Joriy bosqich": "Текущий этап",
 "Joriy likvidlik koeffitsienti": "Коэффициент текущей ликвидности",
 "Joriy tashrif holati": "Статус текущего визита",
 "Joylashuv": "Расположение",
 "Joylashuv izohi": "Примечание к расположению",
 "Kadastr": "Кадастр",
 "Kadastr hujjati": "Кадастровый документ",
 "Kadastr ma'lumotlari": "Кадастровые данные",
 "Kadastr raqami": "Кадастровый номер",
 "Kamera": "Камера",
 "Kamera oflayn": "Камера не в сети",
 "Kamera onlayn": "Камер онлайн",
 "Kamera tasviri": "Изображение с камеры",
 "Kamera, Face ID, domofon yoki eshik kontrollerini obyektga bog'lab, tizimga qo'shing": "Привяжите камеру, Face ID, домофон или дверной контроллер к объекту и добавьте в систему",
 "Kameralardan kuzatish": "Наблюдение с камер",
 "Kanalizatsiya": "Канализация",
 "Kanban taxtasi": "Канбан-доска",
 "Kapital rentabelligi (ROE)": "Рентабельность капитала (ROE)",
 "Karta raqami": "Номер карты",
 "Kechikish": "Просрочка",
 "Kechikish muddati": "Срок просрочки",
 "Kechikish: barchasi": "Просрочка: все",
 "Kengaytirilgan filtrlar": "Расширенные фильтры",
 "Keyingi": "Следующая",
 "Keyingi bosqichga o'tkazish": "Перевести на следующий этап",
 "Keyingi muddat": "Ближайший срок",
 "Keyingi oy": "Следующий месяц",
 "Keyingi sahifa": "Следующая страница",
 "Keyingi yuborilish": "Следующая отправка",
 "Kirish": "Вход",
 "Kirish nazorati": "Контроль доступа",
 "Kirish nazorati paneli": "Панель контроля доступа",
 "Kirish nuqtasi": "Точка доступа",
 "Kirish nuqtasi (3D)": "Точка входа (3D)",
 "Kirish so'rovlar": "Запросы на вход",
 "Kirish so'rovlari": "Запросы на доступ",
 "Kirish taqiqlangan": "Доступ запрещён",
 "Kirish vaqti": "Время входа",
 "Kirish voqealari": "События доступа",
 "Kirish voqealari markazi": "Центр событий доступа",
 "Ko'rib chiqilmoqda": "На рассмотрении",
 "Ko'rik belgilangan": "Осмотр назначен",
 "Ko'rish": "Просмотр",
 "Kommunikatsiya kirish nuqtalari": "Точки ввода коммуникаций",
 "Konferensiya zali": "Конференц-зал",
 "Korporativ hisobingiz bilan kiring — kirish huquqi lavozimingizga muvofiq beriladi": "Войдите с корпоративной учётной записью — права доступа выдаются согласно должности",
 "Kredit shartnomalari": "Кредитные договоры",
 "Kredit shartnomasi": "Кредитный договор",
 "Kredit turi": "Вид кредита",
 "Kritik": "Критично",
 "Kutilmoqda": "Ожидает",
 "Kvartira": "Квартира",
 "Lavozim": "Должность",
 "MAC manzil": "MAC-адрес",
 "MIB bo'limi": "Отделение МИБ",
 "MIB hujjatlari": "Документы МИБ",
 "MIB ijro ishi": "Исполнительное дело МИБ",
 "MIB ijro ishi raqami": "Номер исполнительного дела МИБ",
 "MIB ijrosi": "Исполнение МИБ",
 "MIB'dan obyekt qabul qilish": "Приём объекта от МИБ",
 "MIB'dan qabul qilingan": "Принято от МИБ",
 "Ma'lumotlar sinxronlanmoqda": "Данные синхронизируются",
 "Manzil": "Адрес",
 "Maqsad": "Цель",
 "Maqsadli foydalanish": "Целевое использование",
 "Mas'ul mutaxassis": "Ответственный специалист",
 "Mas'ul shaxs": "Ответственное лицо",
 "Mas'ul texnik xodim": "Ответственный техник",
 "Mas'ul yurist": "Ответственный юрист",
 "Masofadan ochiladigan eshik qulfi": "Дверной замок с дистанционным управлением",
 "Masofaviy ko'rik": "Дистанционный осмотр",
 "Masofaviy ko'rik boshlash": "Начать дистанционный осмотр",
 "Masofaviy ko'rik sessiyasi": "Сессия дистанционного осмотра",
 "Maydon": "Площадь",
 "Mehmon": "Посетитель",
 "Mehmon uchun masofaviy ko'rikni boshqaring va xavfsiz kirishni ta'minlang.": "Управляйте дистанционным осмотром для посетителя и обеспечьте безопасный доступ.",
 "Meni eslab qolish": "Запомнить меня",
 "Mening qarzdorlarim": "Мои должники",
 "Mening servis topshiriqlarim": "Мои сервисные задания",
 "Mezbon": "Принимающий",
 "Mijoz": "Клиент",
 "Mijoz qo'shish": "Добавить клиента",
 "Mijoz, shartnoma raqami yoki INN...": "Клиент, номер договора или ИНН...",
 "Mikrofon": "Микрофон",
 "Mikrokreditbank": "Микрокредитбанк",
 "Mikroqarz": "Микрозайм",
 "Mikroqarz (garov bilan)": "Микрозайм (под залог)",
 "Model": "Модель",
 "Modul / Rollar": "Модуль / Роли",
 "Moliya": "Финансы",
 "Moliyaviy": "Финансовые",
 "Moliyaviy hisobotlar": "Финансовые отчёты",
 "Moliyaviy ko'rsatkichlar": "Финансовые показатели",
 "Moliyaviy ko'rsatkichlar sharhi": "Обзор финансовых показателей",
 "Monitoring": "Мониторинг",
 "Monitoring intervali": "Интервал мониторинга",
 "Monitoring markazi": "Центр мониторинга",
 "Muammoli aktivlar departamenti": "Департамент проблемных активов",
 "Muddat": "Срок",
 "Muddati o'tgan": "Просрочено",
 "Muddati o'tgan kredit va lizing shartnomalari bo'yicha qarzdorlar reyestri": "Реестр должников по просроченным кредитным и лизинговым договорам",
 "Muddati o'tgan kreditlar bo'yicha da'vo, sud va majburiy ijro jarayonlarini kuzatish": "Контроль исковых, судебных и исполнительных процессов по просроченным кредитам",
 "Muddati o'tgan qarz": "Просроченная задолженность",
 "Muddati yaqinlashgan": "Срок истекает",
 "Muddatni tanlang": "Выберите срок",
 "Muhim": "Важно",
 "Muhim eslatma": "Важное напоминание",
 "Musodara dalolatnomasi": "Акт конфискации",
 "Musodara jarayonida": "В процессе конфискации",
 "Musodara qabuli": "Приём конфиската",
 "Musodara qabuliga o'tish": "Перейти к приёму конфиската",
 "Musodara qilingan": "Конфисковано",
 "Musodara qilingan garov": "Конфискованный залог",
 "Musodara qilingan garov obyektlarini realizatsiya qilish": "Реализация конфискованных залоговых объектов",
 "Musodara qilingan garov obyektlarini realizatsiya qilish: ko'rikdan hujjatlargacha yagona jarayon": "Реализация конфискованных залоговых объектов: единый процесс от осмотра до документов",
 "Musodara qilingan obyektni hujjatlari bilan tizimga kiritish va nazoratga olish": "Постановка конфискованного объекта с документами на учёт и контроль",
 "Mustaqil baholash bo'yicha": "По независимой оценке",
 "Muzokarada": "На переговорах",
 "Muzokaradagi obyektlar": "Объекты на переговорах",
 "Nazorat balli": "Балл контроля",
 "Nazorat davri": "Период контроля",
 "Nazorat markazi": "Центр контроля",
 "Nazorat xarajatlari (YTD)": "Затраты на контроль (с начала года)",
 "Nazorat, ijara va auksiondagi obyektlar": "Объекты под контролем, в аренде и на аукционе",
 "Nazoratda": "Под контролем банка",
 "Nazoratdagi obyektlar soni": "Количество объектов под контролем",
 "Nazoratga olinmoqda": "Ставится на контроль",
 "Nazoratga olish": "Постановка на контроль",
 "Nofaol": "Неактивен",
 "Norma buzildi": "Норматив нарушен",
 "Normal": "Норма",
 "O'chirish": "Удалить",
 "O'rnatish akti": "Акт установки",
 "O'rnatish muddati": "Срок установки",
 "O'rta": "Средний",
 "O'rtacha bartaraf etish vaqti": "Среднее время устранения",
 "O'rtacha javob vaqti": "Среднее время реакции",
 "O'tgan oyga nisbatan": "К прошлому месяцу",
 "O'tgan yilga nisbatan": "К прошлому году",
 "O'tkazish": "Перевести",
 "O'xshashlik darajasi": "Степень совпадения",
 "O'zbek tili": "Узбекский язык",
 "Obhod jurnali": "Журнал обходов",
 "Obyekt": "Объект",
 "Obyekt / bino": "Объект / здание",
 "Obyekt bank balansiga qabul qilindi": "Объект принят на баланс банка",
 "Obyekt bank balansiga qabul qilingan": "Принято на баланс банка",
 "Obyekt hayot sikli": "Жизненный цикл объекта",
 "Obyekt hujjatlari": "Документы объекта",
 "Obyekt ma'lumotlari": "Данные объекта",
 "Obyekt nomi": "Наименование объекта",
 "Obyekt turi": "Тип объекта",
 "Obyekt va joylashuv": "Объект и расположение",
 "Obyekt, shartnoma yoki mijoz bo'yicha qidirish...": "Поиск по объекту, договору или клиенту...",
 "Obyekt, xaridor yoki undiruv ishi raqami...": "Объект, покупатель или номер дела о взыскании...",
 "Obyektlar holati": "Статусы объектов",
 "Ochiq": "Открыт",
 "Ochiq hodisalar": "Открытые происшествия",
 "Ochiq servis topshiriqlari": "Открытые сервисные задания",
 "Ochiq trevoga": "Открытых тревог",
 "Ochish": "Открыть",
 "Ofis binosi": "Офисное здание",
 "Oflayn": "Оффлайн",
 "Ogohlantirish": "Предупреждение",
 "Ogohlantirishlar": "Предупреждения",
 "Oldi-sotdi shartnomasi rasmiylashtirildi": "Оформлен договор купли-продажи",
 "Oldingi": "Предыдущая",
 "Oldingi oy": "Предыдущий месяц",
 "Oldingi sahifa": "Предыдущая страница",
 "Ombor": "Склад",
 "Ombor kirish": "Вход на склад",
 "Onlayn": "Онлайн",
 "Onlayn qurilmalar": "Устройства онлайн",
 "Operator ish joyi": "Рабочее место оператора",
 "Operatsion xarajatlar": "Операционные затраты",
 "Orqaga": "Назад",
 "Oylik": "Ежемесячно",
 "Oylik faoliyat hisoboti": "Ежемесячный отчёт о деятельности",
 "Oylik undiruv": "Взыскание за месяц",
 "Parking kirish": "Въезд на парковку",
 "Parol": "Пароль",
 "Parolni kiriting": "Введите пароль",
 "Parolni ko'rsatish": "Показать пароль",
 "Parolni unutdingizmi?": "Забыли пароль?",
 "Past": "Низкий",
 "Port": "Порт",
 "Portfel baholangan qiymati": "Оценочная стоимость портфеля",
 "Prioritet": "Приоритет",
 "Profil ma'lumotlari": "Данные профиля",
 "Protokol": "Протокол",
 "Qabul qilish": "Принять",
 "Qabul qiluvchilar": "Получатели",
 "Qarz / Kapital nisbati": "Отношение долга к капиталу",
 "Qarzdor mijoz": "Клиент-должник",
 "Qarzdor mijozlar": "Клиенты-должники",
 "Qarzdorlar": "Должники",
 "Qarzdorlar orasidan qidirish": "Поиск среди должников",
 "Qarzdorlar reyestri": "Реестр должников",
 "Qarzdorlik ko'rsatkichlari": "Показатели задолженности",
 "Qarzdorni tanlash": "Выбрать должника",
 "Qavat": "Этаж",
 "Qavatlar soni": "Количество этажей",
 "Qayta urinib ko'rish": "Повторить попытку",
 "Qidirish": "Поиск",
 "Qidirish...": "Поиск...",
 "Qidiruv yoki filtrga mos arxiv yozuvi yo'q.": "Нет архивных записей по запросу или фильтру.",
 "Qishloq xo'jaligi yerlari": "Сельскохозяйственные земли",
 "Qo'llab-quvvatlash": "Техподдержка",
 "Qo'riqlanadigan obyekt": "Объектов под охраной",
 "Qo'riqlash posti": "Пост охраны",
 "Qo'riqlash rejimi": "Режим охраны",
 "Qo'shish": "Добавить",
 "Qoldiq asosiy qarz": "Остаток основного долга",
 "Qoldiq qarz": "Остаток долга",
 "Qoldiq qarz summasi": "Сумма остатка долга",
 "Qurilgan yili": "Год постройки",
 "Qurilish yerlari": "Земли под застройку",
 "Qurilma": "Устройство",
 "Qurilma diagnostikasi": "Диагностика устройства",
 "Qurilma hayot sikli": "Жизненный цикл устройства",
 "Qurilma holati": "Состояние устройства",
 "Qurilma nomi (tizimda ko'rinadi)": "Имя устройства (отображается в системе)",
 "Qurilma turi": "Тип устройства",
 "Qurilma turi va modeli": "Тип и модель устройства",
 "Qurilmalar": "Устройства",
 "Qurilmalar holati": "Состояние устройств",
 "Quvvat manbai": "Источник питания",
 "Rad etish": "Отклонить",
 "Rad etish sababi": "Причина отклонения",
 "Rad qilish": "Отказать",
 "Rasm": "Изображение",
 "Realizatsiya": "Реализация",
 "Realizatsiya arxivi": "Архив реализации",
 "Realizatsiya qilingan garov obyektlarining doimiy arxivi": "Постоянный архив реализованных залоговых объектов",
 "Realizatsiya sanasi": "Дата реализации",
 "Realizatsiya tushumi (YTD)": "Выручка от реализации (с начала года)",
 "Rejalashtirilgan": "Запланировано",
 "Rejaning 78 foizi bajarildi": "План выполнен на 78 процентов",
 "Reyestr": "Реестр",
 "Reyestr eksporti": "Экспорт реестра",
 "Reyestrda": "В реестре",
 "Rollar bo'yicha ruxsat matritsasi": "Матрица прав по ролям",
 "Rolni almashtirish": "Сменить роль",
 "Rus tili": "Русский язык",
 "Ruxsat berish": "Разрешить доступ",
 "Ruxsat rad etildi · 403": "Доступ запрещён · 403",
 "Ruxsat yetarli emas": "Недостаточно прав",
 "Sababni kiriting...": "Укажите причину...",
 "Sahifa topilmadi": "Страница не найдена",
 "Sana": "Дата",
 "Sana va vaqt": "Дата и время",
 "Sanoat yerlari": "Промышленные земли",
 "Saqlash": "Сохранить",
 "Sarlavha": "Заголовок",
 "Savdo maydoni": "Торговая площадь",
 "Seriya raqami": "Серийный номер",
 "Servis": "Сервис",
 "Servis topshirig'i": "Сервисное задание",
 "Servis topshirig'i va tekshiruv": "Сервисное задание и проверка",
 "Sessiya bosqichlari": "Этапы сессии",
 "Shartnoma": "Договор",
 "Shartnoma raqami": "Номер договора",
 "Shartnoma turi": "Тип договора",
 "Shartnomalar": "Договоры",
 "Shlagbaum": "Шлагбаум",
 "Shoshilinch muddatlar": "Срочные сроки",
 "Shoshilinch undiruv ishlari": "Срочные дела о взыскании",
 "Shu oy realizatsiya qilingan": "Реализовано в этом месяце",
 "Signal sifati": "Качество сигнала",
 "So'nggi 12 oy to'lov intizomi": "Платёжная дисциплина за 12 месяцев",
 "So'nggi 24 soat": "За последние 24 часа",
 "So'nggi hodisalar": "Последние происшествия",
 "So'nggi qabul qilingan obyektlar": "Последние принятые объекты",
 "Sof qoplama (YTD)": "Чистое покрытие (с начала года)",
 "Solishtirma ball": "Сравнительный балл",
 "Sotilgan": "Реализовано",
 "Sotuv narxi": "Цена продажи",
 "Sozlamalar": "Настройки",
 "Sud jarayonida": "В судебном процессе",
 "Sud organi": "Судебный орган",
 "Sud qarori": "Решение суда",
 "Sud qarori qabul qilindi": "Принято решение суда",
 "Sud qarori raqami": "Номер решения суда",
 "Sug'orish tizimi": "Система орошения",
 "Suhbat boshlash": "Начать разговор",
 "Suv ta'minoti": "Водоснабжение",
 "Tahliliy hisobotlar kutubxonasi va eksport": "Библиотека аналитических отчётов и экспорт",
 "Tahrirlash": "Редактировать",
 "Tanlangan ish tafsiloti": "Детали выбранного дела",
 "Tanlangan obyekt": "Выбранный объект",
 "Tanlangan qarzdor tafsiloti": "Детали выбранного должника",
 "Tanlangan qavat": "Выбранный этаж",
 "Tarix": "История",
 "Tarmoq moduli": "Сетевой модуль",
 "Tarmoq va identifikatsiya": "Сеть и идентификация",
 "Tasdiq kutmoqda": "Ожидает подтверждения",
 "Tasdiqlangan": "Подтверждено",
 "Tasdiqlash": "Подтвердить",
 "Tashkilot": "Организация",
 "Tashrif buyuruvchi": "Посетитель",
 "Tashrif maqsadi": "Цель визита",
 "Tavsif": "Описание",
 "Taxminiy qiymati (so'm)": "Предварительная стоимость (сум)",
 "Tayyor": "Готово",
 "Tekshirildi": "Проверено",
 "Tekshirilmoqda": "Проверяется",
 "Tekshirish usuli": "Способ проверки",
 "Telefon": "Телефон",
 "Texnik": "Техник",
 "Texnik holat": "Техническое состояние",
 "Texnik pasport": "Технический паспорт",
 "Texnik qavat": "Технический этаж",
 "Texnik ta'minot bo'limi": "Отдел технического обеспечения",
 "Texnik xizmat ish joyi": "Рабочее место техслужбы",
 "Texnik xodim": "Технический специалист",
 "Texnik xulosa": "Техническое заключение",
 "Tez eksportlar": "Быстрый экспорт",
 "Tezkor eslatmalar": "Оперативные напоминания",
 "Tijorat obyekti": "Коммерческий объект",
 "Tizim": "Система",
 "Tizim parametrlari": "Параметры системы",
 "Tizim texnik xizmatda": "Система на техническом обслуживании",
 "Tizimdan chiqish": "Выйти из системы",
 "Tizimga kirish": "Вход в систему",
 "To'liq ekran": "Полный экран",
 "To'lov": "Платёж",
 "To'lov kechikkan": "Платёж просрочен",
 "To'lov tasdiqnomasi biriktirildi": "Приложено подтверждение оплаты",
 "To'xtatilgan": "Приостановлено",
 "Top obyektlar (balans qiymati)": "Топ объектов (балансовая стоимость)",
 "Topshiriq": "Задание",
 "Topshiriq tafsilotlari, obyekt xaritasi va tekshiruv vazifalari": "Детали задания, карта объекта и задачи проверки",
 "Topshirish dalolatnomasi biriktirildi": "Приложен акт передачи",
 "Trevoga navbati": "Очередь тревог",
 "Trevogani qabul qilish": "Принять тревогу",
 "Tugatish": "Завершить",
 "Turar-joy majmuasi": "Жилой комплекс",
 "Turi": "Тип",
 "Uchastka chegarasi": "Граница участка",
 "Uchastka ma'lumotlari": "Данные участка",
 "Ulangan": "Подключено",
 "Ulanish testi va faollashtirish": "Тест подключения и активация",
 "Umumiy": "Общие",
 "Umumiy ma'lumot": "Общие сведения",
 "Umumiy maydon": "Общая площадь",
 "Umumiy maydon (m²)": "Общая площадь (м²)",
 "Umumiy qiymat": "Общая стоимость",
 "Undirilayotgan summa": "Взыскиваемая сумма",
 "Undirilgan mablag' (YTD)": "Взыскано (с начала года)",
 "Undirilgan mablag' (oy)": "Взыскано за месяц",
 "Undiruv": "Взыскание",
 "Undiruv bosqichlari": "Этапы взыскания",
 "Undiruv ishi": "Дело о взыскании",
 "Undiruv ishini ochish": "Открыть дело о взыскании",
 "Undiruv ishlari": "Дела о взыскании",
 "Undiruv ishlariga o'tish": "Перейти к делам о взыскании",
 "Undiruv jarayoni bosqichlari": "Этапы процесса взыскания",
 "Undiruv ko'rsatkichlari": "Показатели взыскания",
 "Undiruv mutaxassisi": "Специалист по взысканию",
 "Undiruv mutaxassisi ish joyi": "Рабочее место специалиста по взысканию",
 "Undiruv to'lovlari": "Платежи по взысканию",
 "Undiruv va sud ishlari": "Взыскание и судебные дела",
 "Undiruvda": "На взыскании",
 "Ushbu bosqichda ochiq ish yo'q.": "На этом этапе нет открытых дел.",
 "Uzilgan": "Обрыв",
 "Uzoqlashtirish": "Отдалить",
 "Vaqt": "Время",
 "Vazifalar": "Задачи",
 "Vazifalar va tasdiqlar": "Задачи и согласования",
 "Videostena": "Видеостена",
 "Voqea turi": "Тип события",
 "Xaridor": "Покупатель",
 "Xarita": "Карта",
 "Xarita va geolokatsiya": "Карта и геолокация",
 "Xatolik va ogohlantirish ekranlari": "Экраны ошибок и предупреждений",
 "Xavfsizlik": "Безопасность",
 "Xavfsizlik nazorati": "Контроль безопасности",
 "Xavfsizlik operatori": "Оператор безопасности",
 "Xavfsizlik operatori ish joyi": "Рабочее место оператора безопасности",
 "Xavfsizlik rejasi": "План безопасности",
 "Xavfsizlik rejasi va texnik topshiriq": "План безопасности и техническое задание",
 "Xavfsizlik tizimi": "Система безопасности",
 "Xavfsizlik topshirig'i": "Задание по безопасности",
 "Xavfsizlik xizmati · Nazorat markazi": "Служба безопасности · Центр контроля",
 "Xizmat amallari": "Сервисные действия",
 "Xodimni tanlang": "Выберите сотрудника",
 "Xona": "Помещение",
 "Xona / zona": "Помещение / зона",
 "Xonalar ro'yxati": "Список помещений",
 "Xonalar va qavatlar": "Помещения и этажи",
 "Xususiy uy va dala hovli": "Частный дом и дача",
 "Yakuniy narx": "Итоговая цена",
 "Yakuniy tasdiqlash": "Финальное подтверждение",
 "Yakunlandi": "Завершено",
 "Yangi": "Новый",
 "Yangi hodisa ochish": "Открыть новое происшествие",
 "Yangi hodisalar": "Новые происшествия",
 "Yangi jadval qo'shish": "Добавить расписание",
 "Yangi qurilma o'rnatish": "Установка нового устройства",
 "Yangi rol": "Новая роль",
 "Yangi so'rov": "Новый запрос",
 "Yangi undiruv ishi": "Новое дело о взыскании",
 "Yaqinlashtirish": "Приблизить",
 "Yaratgan": "Автор",
 "Yaratilgan": "Создано",
 "Yaratish": "Создать",
 "Yaxshi": "Хорошо",
 "Yer uchastkalari": "Земельные участки",
 "Yer uchastkasi": "Земельный участок",
 "Yon eshikni ochish": "Открыть боковую дверь",
 "Yon kirish": "Боковой вход",
 "Yong'in detektori": "Пожарный извещатель",
 "Yong'in signali – kritik": "Пожарный сигнал — критично",
 "Yong'in signalizatsiyasi": "Пожарная сигнализация",
 "Yong'in xavfsizligi": "Пожарная безопасность",
 "Yopildi": "Закрыто",
 "Yopilgan": "Закрыт",
 "Yopiq": "Закрыт",
 "Yopish": "Закрыть",
 "Yozma ogohlantirish yuborildi": "Направлено письменное предупреждение",
 "Yozuv topilmadi": "Записи не найдены",
 "Yuklab olish": "Скачать",
 "Yuklangan hujjatlar": "Загруженные документы",
 "Yuklash uchun bosing": "Нажмите для загрузки",
 "Yuqori": "Высокий",
 "Yuridik shaxs": "Юридическое лицо",
 "Yuz mos keldi": "Лицо распознано",
 "Yuz mos kelmadi": "Лицо не распознано",
 "Zaxira generator": "Резервный генератор",
 "Zaxira quvvat": "Резервное питание",
 "Zaxira quvvat (UPS)": "Резервное питание (ИБП)",
 "Zaxira yerlar": "Резервные земли",
 "gektar": "га",
 "kun": "дней",
 "kun qoldi": "дней осталось",
 "mln so'm": "млн сум",
 "mlrd so'm": "млрд сум",
 "portfelda": "в портфеле",
 "so'm": "сум",
 "ta ish": "дел",
 "ta obyekt": "объектов",
 "trln so'm": "трлн сум",
 "uchastka": "участков"
};
