/* ============================================================
   Interfeys tili — ruscha variant lug'ati.
   Kalit: interfeysdagi o'zbekcha matn (aynan, bo'sh joysiz).
   Qiymat: ruscha muqobili. Kalit topilmasa matn o'zbekcha qoladi.
   Xos ismlar, manzillar va hujjat raqamlari ataylab tarjima qilinmaydi.
   ============================================================ */
window.MKB_LUGAT = {
  "Interfeys uslubi": "Стиль интерфейса",
  "Konsol": "Консоль",
  "Panorama": "Панорама",
  "Konsol uslubi": "Стиль «Консоль»",
  "Galereya uslubi": "Стиль «Галерея»",
  "Panorama uslubi": "Стиль «Панорама»",
  "Diqqat markazida · eng yuqori xavf": "В фокусе внимания · наивысший риск",
  "Kechikish, kun": "Просрочка, дней",
  "Toshkent shahar sudi": "Ташкентский городской суд",
  "Toshkent viloyat sudi": "Ташкентский областной суд",
  "Samarqand sudi": "Самаркандский суд",
  "Buxoro sudi": "Бухарский суд",
 /* 24.08.2026: lug'at to'liq qamrovgacha to'ldirildi */
  "Ish o'rni": "Рабочее место",
  "Aylantirish uchun sudrang": "Перетащите, чтобы повернуть",
  "Obyekt topilmadi": "Объект не найден",
  "Dalolatnoma topilmadi": "Акт не найден",
  "So'ralgan identifikator reyestrda yo'q:": "Запрошенный идентификатор отсутствует в реестре:",
  "So'ralgan ko'rik reyestrda yo'q:": "Запрошенный осмотр отсутствует в реестре:",
  "Reyestrga qaytish": "Вернуться в реестр",
  "Ko'rik rejasiga qaytish": "Вернуться к плану осмотров",
  "Navbat bo'sh": "Очередь пуста",
  "Barcha so'rovlar ko'rib chiqildi.": "Все запросы рассмотрены.",
  "Ko'rik hali o'tkazilmagan — tekshiruv bandlari chiqishdan keyin to'ldiriladi.": "Осмотр ещё не проведён — пункты проверки заполняются после выезда.",
  "Fotojamlanma chiqish vaqtida yuklanadi.": "Фотофиксация загружается во время выезда.",
  "Tanlov faqat ko'rsatma muhitida amal qiladi.": "Выбор действует только в ознакомительной среде.",
  "Ko'rik dalolatnomasi rasmiylashtirildi": "Оформлен акт осмотра",
  "Navbatdagi ko'rik rejalashtirildi": "Запланирован очередной осмотр",
  "Qisman to'lov qabul qilindi": "Принят частичный платёж",
  "Sug'urta polisi yangilandi": "Обновлён страховой полис",
  "Asosiy qarz va hisoblangan foizlar bilan": "Основной долг с начисленными процентами",
  "Auksionda (doska)": "На аукционе (доска)",
  "Barcha hodisalar ro'yxati": "Список всех событий",
  "Birinchi ko'rik": "Первый осмотр",
  "Byudjet bajarilishi – Iyul 2026": "Исполнение бюджета – июль 2026",
  "Dala marshruti": "Полевой маршрут",
  "Daromad dinamikasi: yanvardan avgustgacha 5,8 dan 12 milliard so'mgacha o'sish": "Динамика поступлений: рост с января по август",
  "Ta'minot shartnomasi ilovasi yuklab olinmoqda": "Загружается приложение к договору актива",
  "Ta'minot shartnomasi ilovasi.pdf · 860 KB": "Приложение к договору актива.pdf · 860 KB",
  "Hodisalar dinamikasi, 18-avgustdan 24-avgustgacha, uch seriya: yangi, bartaraf etilmoqda va yopildi": "Динамика событий с 18 по 24 августа, три серии: новые, устраняются и закрытые",
  "Interaktiv 3D tarkib ko'rinishi": "Интерактивный 3D-вид состава",
  "Moliyaviy hisobot – 2026 Q2": "Финансовый отчёт – 2026 Q2",
  "Obyektlar holati bo'yicha taqsimot diagrammasi": "Диаграмма распределения объектов по состояниям",
  "Pul oqimi hisoboti – 2026 Q2": "Отчёт о денежном потоке – 2026 Q2",
  "Topshiriq avtomatik yaratiladi": "Поручение создаётся автоматически",
  "Undiruvgacha bosqich": "Этап до взыскания",
  "Bu bo'lim sizning rolingiz uchun ochiq emas": "Этот раздел недоступен для вашей роли",
  "Faqat Administrator hodisani o'chirishi mumkin": "Удалить событие может только администратор",
  "Majburiy hujjatlarni yuklang — sud qarori va musodara dalolatnomasi": "Загрузите обязательные документы — решение суда и акт конфискации",
  "Ijro ishi raqamini kiriting": "Укажите номер исполнительного производства исполнения",
  "Obyekt nomini kiriting": "Укажите наименование объекта",
  "Obyekt qabul qilindi — KO-2026/0413 birinchi ko'rik topshirig'i yaratildi": "Объект принят — создано поручение на первый осмотр KO-2026/0413",
  "Obyekt turini tanlang": "Выберите тип объекта",
  "Rad etish sababini kiriting": "Укажите причину отклонения",
  "Rejaga o'tish": "Перейти к плану",
  "30 kun ichida tugaydigan polislar": "Полисы, истекающие в течение 30 дней",
  "90 kun ichida yillik muddati to'ladi": "Годовой срок истекает в течение 90 дней",
  "3D aylantirish": "3D-вращение",
  "404 illyustratsiyasi": "Иллюстрация 404",
  "404 — sahifa topilmadi illyustratsiyasi": "Иллюстрация «404 — страница не найдена»",
  "Avgust 2026": "Август 2026",
 "Bugun": "Сегодня",
 "Tasdiqlar": "Согласования",
 "Baholangan qiymat / qoldiq qarz": "Оценочная стоимость / остаток долга",
 "Barcha hodisalar": "Все события",
 "Email": "Email",
 "Hafta": "Неделя",
 "Keyingi sahifa yuklanmoqda": "Загружается следующая страница",
 "Obyekt yangilandi": "Объект обновлён",
 "obyektdan": "объектов",
 "Ofis qavat 5": "Офис, 5-й этаж",
 "Ofis qavati": "Офисный этаж",
 "PDF · majburiy": "PDF · обязательно",
 "Qarzning": "покрывает",
 "qismi": "долга",
 "To'lov qabul qilindi": "Платёж принят",
 "Xizmat ko'rsatilishi rejalashtirildi": "Обслуживание запланировано",
 "Yangi hujjat yuklandi": "Загружен новый документ",
 "Yangi ijara shartnomasi imzolandi": "Подписан новый договор аренды",
 "Yaqin atrofdagi uy": "Дом поблизости",
 "-1-qavat": "-1-й этаж",
 "● Faol": "● Активен",
 "1. Balansga qabul qilish": "1. Приём на баланс",
 "2. Nazoratga olish": "2. Постановка на контроль",
 "3. Davriy nazorat": "3. Периодический контроль",
 "4. Xaridor ko'rigi": "4. Осмотр покупателем",
 "5. Sotuvga tayyorlash": "5. Подготовка к продаже",
 "6. Doimiy arxiv": "6. Постоянный архив",
 "Administrator roli tafsiloti": "Детали роли администратора",
 "Alohida nazorat qarori bo'yicha": "По отдельному решению о контроле",
 "Aloqa tiklanguncha natijalar navbatda saqlanadi": "До восстановления связи результаты хранятся в очереди",
 "API, integratsiyalar va tizim ulanishlari": "API, интеграции и системные подключения",
 "Arxiv": "Архив",
 "Arxiv ro'yxati XLSX eksport qilinmoqda": "Список архива экспортируется в XLSX",
 "Asosiy": "Основное",
 "Audit jurnali ruxsatlari": "Права на журнал аудита",
 "Auksion tushumlari tafsiloti": "Детали поступлений от аукционов",
 "Baholash dolzarbligi kesimi": "Срез актуальности оценки",
 "Baholash hisoboti yangilandi": "Отчёт об оценке обновлён",
 "Baholash ko'rsatkichlari": "Показатели оценки",
 "Baholovchi tashkilotga buyurtma oynasi": "Окно заказа в оценочную организацию",
 "Bank balansiga qabul qilingan": "Принято на баланс банка",
 "Bank nazoratidagi uchastkalar": "Участки под контролем банка",
 "Barcha 14 ta hodisa ro'yxati": "Список всех 14 событий",
 "Barcha eksport shablonlari": "Все шаблоны экспорта",
 "Barcha faoliyatni ko'rish": "Смотреть всю активность",
 "Barcha formatlar": "Все форматы",
 "Barcha modul va ma'lumotlarga to'liq kirish": "Полный доступ ко всем модулям и данным",
 "Barcha obyektlarni ko'rish": "Смотреть все объекты",
 "Barcha obyektlarni ko'rsatish": "Показать все объекты",
 "Barcha shablonlarni ko'rish": "Смотреть все шаблоны",
 "Barcha shartnomalar": "Все договоры",
 "Barcha tasdiqlar ro'yxati": "Список всех согласований",
 "Barcha tasdiqlash so'rovlari": "Все запросы на согласование",
 "Barcha uchastkalar ro'yxati": "Список всех участков",
 "Barcha vazifalar ro'yxati": "Список всех задач",
 "Barchasini o'qilgan deb belgilash": "Отметить все как прочитанные",
 "Batafsil nazoratdagi yozuvlar bo'yicha": "По записям на детальном контроле",
 "Batafsil yozuvlar bo'yicha sug'urta summasi": "Страховая сумма по детальным записям",
 "Bildirishnoma kanallari": "Каналы уведомлений",
 "Bildirishnoma qo'ng'irog'i illyustratsiyasi": "Иллюстрация колокольчика уведомлений",
 "Bildirishnoma turlari": "Типы уведомлений",
 "Bildirishnomalar — yangi xabarlar bor": "Уведомления — есть новые сообщения",
 "Bino qavatlari kesim ko'rinishi": "Вид здания в разрезе по этажам",
 "Binoning 3D ko'rinishi": "3D-вид здания",
 "Binoning interaktiv 3D ko'rinishi": "Интерактивный 3D-вид здания",
 "Birinchi ko'rik dalolatnomasi va fotojamlanma": "Акт первичного осмотра и фотофиксация",
 "Birinchi ko'rik muddati": "Срок первичного осмотра",
 "Biznes markazi": "Бизнес-центр",
 "Bo'stonliq": "Бостанлык",
 "Bo'stonliq · Ta'minotda": "Бостанлык · В активе",
 "bo'yicha ma'lumotlar ko'rsatilmoqda": "— показаны данные",
 "Boshlanish sanasi": "Дата начала",
 "Boshqa daromadlar": "Прочие поступления",
 "Boshqa daromadlar tafsiloti": "Детали прочих поступлений",
 "Boshqaruv paneliga qaytish": "Вернуться в панель управления",
 "Butun portfel bo'yicha dolzarblik kesimi": "Срез актуальности по всему портфелю",
 "Butun portfel bo'yicha sug'urta kesimi": "Срез страхования по всему портфелю",
 "Buxoro ijro": "исполнения Бухары",
 "Byudjet bajarilishi – Aprel 2024": "Исполнение бюджета – апрель 2024",
 "Byudjet fayli yuklab olinmoqda": "Файл бюджета скачивается",
 "Ch": "Ср",
 "Chegara rejasi yuklab olinmoqda": "План границ скачивается",
 "Chorak": "Квартал",
 "Choraklik": "Ежеквартально",
 "Da'vo, sud va ijro hujjatlari": "Исковые, судебные и исполнительные документы",
 "Dalolatnoma imzolangan chiqishlar": "Выезды с подписанным актом",
 "Dalolatnoma PDF shaklida yuklanmoqda": "Акт скачивается в формате PDF",
 "Dalolatnoma shakli ochilmoqda — imzolash uchun barcha bandlar yakunlanishi kerak": "Открывается форма акта — для подписания все пункты должны быть завершены",
 "Daromad dinamikasi (so'm)": "Динамика поступлений (сум)",
 "Daromad dinamikasi: yanvardan maygacha 5,8 dan 12 milliard so'mgacha o'sish": "Динамика поступлений: рост с 5,8 до 12 миллиардов сум с января по май",
 "Daromad tuzilmasi: ijara 45,2%, savdo 26,7%, xizmat 18,3%, boshqa 9,8%": "Структура поступлений: аренда 45,2%, торги 26,7%, услуги 18,3%, прочее 9,8%",
 "Daromadlar tafsiloti": "Детали поступлений",
 "Daromadlar va xarajatlar tahlili": "Анализ поступлений и затрат",
 "Davr tanlash oynasi": "Окно выбора периода",
 "Davriylik reglamenti bo'yicha navbatdagi chiqish": "Очередной выезд по регламенту периодичности",
 "Disk foydalanish": "Использование диска",
 "Do'kon": "Магазин",
 "Doimiy yuboriladigan hisobotlar": "Регулярно отправляемые отчёты",
 "Du": "Пн",
 "E-mail": "E-mail",
 "E'tibor talab qilinadigan holatlar": "Случаи, требующие внимания",
 "Eksport qilish": "Экспортировать",
 "Elektron pochta": "Электронная почта",
 "Elektron pochta sozlamalari": "Настройки электронной почты",
 "Email yozish": "Написать email",
 "Email yuborish oynasi": "Окно отправки email",
 "English": "English",
 "Faol foydalanuvchilar": "Активные пользователи",
 "Faol shartnomalar": "Действующие договоры",
 "Faollik darajasi": "Уровень активности",
 "Filial rahbari roli tafsiloti": "Детали роли руководителя филиала",
 "Filialni tanlash": "Выбор филиала",
 "Filtrlar: rol, bo'lim, holat": "Фильтры: роль, отдел, статус",
 "Formatni tanlash": "Выбор формата",
 "Fotojamlanma hali yuklanmagan": "Фотофиксация ещё не загружена",
 "Fotojamlanma hali yuklanmagan illyustratsiyasi": "Иллюстрация: фотофиксация ещё не загружена",
 "Foydalanuvchi qidirish": "Поиск пользователя",
 "Foydalanuvchilar, rollar, sozlamalar va xavfsizlik": "Пользователи, роли, настройки и безопасность",
 "Aktiv obyektlari direktori": "Директор по активовым объектам",
 "Aktiv obyektlari joylashuvi — Toshkent shahri va viloyati xaritasi": "Расположение активовых объектов — карта города Ташкента и области",
 "Aktiv obyektlari ro'yxati": "Список активовых объектов",
 "Aktiv obyektlari ro'yxati XLSX shakllantirilmoqda": "Список активовых объектов формируется в XLSX",
 "Ta'minot qiymati yetmaydigan qism": "Часть, не покрытая стоимостью актива",
 "Aktivlar nazorati bo'limi": "Отдел обеспечения",
 "Aktivlar nazorati ko'rsatkichlari": "Показатели службы контроля активов",
 "Aktivlar nazorati roli tafsiloti": "Детали роли службы контроля активов",
 "Ta'minotning baholangan qiymati qarzga nisbatan": "Оценочная стоимость актива по отношению к долгу",
 "Hal qilindi": "Решено",
 "Har bir chiqishda majburiy qadamlar soni": "Количество обязательных шагов на каждом выезде",
 "Hisob yozuvlari, ma'lumotnomalar, audit": "Учётные записи, справочники, аудит",
 "Hisobot 3D illyustratsiyasi": "3D-иллюстрация отчёта",
 "Hisobot ko'rish oynasida ochildi": "Отчёт открыт в окне просмотра",
 "Hisobot turini tanlash": "Выбор типа отчёта",
 "Hisobotlar bo'limi": "Раздел отчётов",
 "Hisobotlar kutubxonasi": "Библиотека отчётов",
 "Hisobotlar ruxsatlari": "Права на отчёты",
 "Hisobotlarni ko'rish, yaratish va eksport qilish": "Просмотр, создание и экспорт отчётов",
 "Hodisa yoki topshiriq asosida 3 ish kuni ichida": "На основании события или поручения в течение 3 рабочих дней",
 "Hodisalar bildirishnomalari sozlamasi": "Настройка уведомлений о событиях",
 "Hodisalar dinamikasi, 18-maydan 24-maygacha, uch seriya: yangi, bartaraf etilmoqda va yopildi": "Динамика событий с 18 по 24 мая, три серии: новые, устраняются и закрыто",
 "Hodisalar issiqlik xaritasi": "Тепловая карта событий",
 "Hodisalar ro'yxati": "Список событий",
 "Holat ekranlari": "Экраны состояний",
 "Hudud va til": "Регион и язык",
 "Hudud va til sozlamalari": "Настройки региона и языка",
 "Hujjat yuklash oynasi": "Окно загрузки документа",
 "Hujjatlar topilmadi illyustratsiyasi": "Иллюстрация: документы не найдены",
 "Hujjatlar va fayllar": "Документы и файлы",
 "Hujjatlar va fayllar sozlamalari": "Настройки документов и файлов",
 "Hujjatlarni ko'rish": "Просмотр документов",
 "Hujjatlarni qidirish": "Поиск документов",
 "Identifikatsiya, holat, egallik, sug'urta, ro'yxat": "Идентификация, состояние, занятость, страховка, опись",
 "Ijara shartnomasi (Turon Retail).pdf · 860 KB": "Договор аренды (Turon Retail).pdf · 860 КБ",
 "Ijara shartnomasi yuklab olinmoqda": "Договор аренды скачивается",
 "Ijara to'lovlari": "Арендные платежи",
 "Ijara to'lovlari XLSX shakllantirilmoqda": "Арендные платежи формируются в XLSX",
 "Infratuzilma brifing varag'i PDF sifatida shakllantirildi": "Лист брифинга по инфраструктуре сформирован в PDF",
 "Integratsiyalar ruxsatlari": "Права на интеграции",
 "Integratsiyalar sozlamalari": "Настройки интеграций",
 "Internet aloqasi yo'q illyustratsiyasi": "Иллюстрация: нет подключения к интернету",
 "Investor: Global Invest Ltd.": "Инвестор: Global Invest Ltd.",
 "Ishtirokchilar": "Участники",
 "IT bo'limi": "IT-отдел",
 "Izoh": "Комментарий",
 "Jami shartnomalar": "Всего договоров",
 "Jami xonalar": "Всего помещений",
 "Jarayon": "Процесс",
 "Jarayonlar ko'rinishi": "Представление процессов",
 "Javob muddati": "Срок ответа",
 "Joriy yil (YTD)": "Текущий год (YTD)",
 "Joy": "Место",
 "Joylashuvni markazlash": "Центрировать расположение",
 "Ju": "Пт",
 "Jurnal XLSX ga yuklanmoqda": "Журнал выгружается в XLSX",
 "Kadastr hujjati.pdf · 1,1 MB · 12-yan 2024": "Кадастровый документ.pdf · 1,1 МБ · 12 янв 2024",
 "Kadastr hujjati.pdf yuklab olinmoqda": "Кадастровый документ.pdf скачивается",
 "Kadastr pasporti yuklab olinmoqda": "Кадастровый паспорт скачивается",
 "Kadastr tekshiruvi o'tdi": "Кадастровая проверка пройдена",
 "Kadastrga taqiq belgisini kiritish": "Внесение в кадастр отметки о запрете",
 "Kamera ulanishi qayta tekshirilmoqda…": "Подключение камеры проверяется повторно…",
 "Kamomad tekshiruvida oldindan ogohlantirish talab etilmaydi": "При проверке недостачи предварительное уведомление не требуется",
 "Karimova Feruza — Aktivlar nazorati bo'limi": "Каримова Феруза — Отдел обеспечения",
 "Kecha": "Вчера",
 "Kengaytirilgan filtrlar paneli": "Панель расширенных фильтров",
 "Keyingi xonalar": "Следующие помещения",
 "Kirish nazorati bildirishnomalari sozlamasi": "Настройка уведомлений контроля доступа",
 "Kirish taqiqlangan illyustratsiyasi": "Иллюстрация: доступ запрещён",
 "Kirish va lobby": "Вход и лобби",
 "Ko'chmas mulk — har chorakda": "Недвижимость — ежеквартально",
 "Ko’rik dalolatnomasi": "Акт осмотра",
 "Ko'rik jadvali XLSX ga yuklanmoqda": "График осмотров выгружается в XLSX",
 "Ko'rik ko'rsatkichlari": "Показатели осмотров",
 "Ko'rik muddati yaqinlashgan yoki to'lgan": "Срок осмотра приближается или истёк",
 "Ko'rik reglamenti": "Регламент осмотров",
 "Ko'rik, sug'urta va baholash nazorati": "Контроль осмотров, страхования и оценки",
 "Ko'rikda nimaga e'tibor qaratiladi": "На что обратить внимание при осмотре",
 "Ko'rikdan 3 kun oldin rasmiy xat yuboriladi": "Официальное письмо направляется за 3 дня до осмотра",
 "Ko'riklar kesimi butun portfel bo'yicha": "Срез осмотров по всему портфелю",
 "Kommunal hisoblarni bank nomiga o'tkazish": "Перевод коммунальных счетов на имя банка",
 "Konferensiya zali — kattalashtirilgan ko'rinish": "Конференц-зал — увеличенный вид",
 "KPI panel eksporti": "Экспорт KPI-панели",
 "KPI panel PPTX shakllantirilmoqda": "KPI-панель формируется в PPTX",
 "Kredit menejeri roli tafsiloti": "Детали роли кредитного менеджера",
 "kun-oy, yil — masalan: 30-avg, 2026": "день-месяц, год — например: 30 авг, 2026",
 "Kunlik ko'rsatkichlar": "Дневные показатели",
 "Kutilayotgan tasdiqlar": "Ожидающие согласования",
 "Lavozimi": "Должность",
 "Ma'lumotlar": "Данные",
 "Ma'lumotlar bazasi": "База данных",
 "Ma'lumotlar boshqaruvi": "Управление данными",
 "Ma'lumotlar boshqaruvi ruxsatlari": "Права на управление данными",
 "Ma'lumotlarni saqlash": "Хранение данных",
 "Ma'lumotlarni saqlash sozlamalari": "Настройки хранения данных",
 "Ma'lumotlarni tekshiring — tasdiqlangach obyekt bank balansiga qabul qilinadi va tegishli rollarga (filial rahbari, ta'minot xizmati, yurist) ko'rinadi.": "Проверьте данные — после подтверждения объект будет принят на баланс банка и станет виден соответствующим ролям (руководитель филиала, служба контроля активов, юрист).",
 "Majburiy hujjatlarni yuklang — hujjatsiz obyekt \"tasdiqlangan\" hisoblanmaydi.": "Загрузите обязательные документы — без документов объект не считается \"подтверждённым\".",
 "Markazlash": "Центрировать",
 "Marshrut varaqasi chop etilmoqda": "Маршрутный лист печатается",
 "Mas'ul inspektor": "Ответственный инспектор",
 "Mas'ul menejer": "Ответственный менеджер",
 "Masalan: 1 250": "Например: 1 250",
 "Masalan: Sergeli turar-joy binosi": "Например: жилой дом в Сергели",
 "Masofaviy ko'rik sessiyasini tasdiqlash": "Подтверждение сессии дистанционного осмотра",
 "Mavjud maydon": "Доступная площадь",
 "Mening vazifalarim": "Мои задачи",
 "Sud qarori bilan musodara qilingan obyekt rekvizitlarini kiriting.": "Введите реквизиты объекта, конфискованного по исполнительному делу исполнения.",
 "Balansga qabul qilish": "Приём на баланс",
 "Model ko'rinishi almashtirildi": "Вид модели переключён",
 "Model rejimi": "Режим модели",
 "Mol-mulk ro'yxatini (opis) tuzish": "Составление описи имущества",
 "Moliya bildirishnomalari sozlamasi": "Настройка финансовых уведомлений",
 "Moliyaviy hisobot": "Финансовый отчёт",
 "Moliyaviy hisobot – 2024 Q1": "Финансовый отчёт – 2024 Q1",
 "Moliyaviy hisobot yuklab olinmoqda": "Финансовый отчёт скачивается",
 "Moliyaviy ko'rsatkichlar 3D illyustratsiyasi": "3D-иллюстрация финансовых показателей",
 "Moliyaviy ko'rsatkichlar PDF shakllantirilmoqda": "Финансовые показатели формируются в PDF",
 "Monitoring hisoboti PDF ga yuklanmoqda": "Отчёт мониторинга выгружается в PDF",
 "Muammoli portfel bilan ishlash": "Работа с проблемным портфелем",
 "Muddati o'tgan chiqishlar darhol qayta tayinlanadi": "Просроченные выезды переназначаются немедленно",
 "Muddati o'tgan yoki rasmiylashtirilmagan": "Просрочено или не оформлено",
 "Muddati o'tganlar": "Просроченные",
 "Muddati yaqinlashganlar": "С приближающимся сроком",
 "Muddatlar": "Сроки",
 "Muddatlar taqvimi": "Календарь сроков",
 "Musodara qabuli yoki auksion oldidan holat qayd etish": "Фиксация состояния перед приёмом конфиската или аукционом",
 "Naf oluvchi — bank": "Выгодоприобретатель — банк",
 "Natija — dalolatnoma": "Результат — акт",
 "Navbatdan tashqari — hodisa bo'yicha": "Внеплановый — по событию",
 "Nazorat": "Контроль",
 "Nazorat ko'rsatkichlari": "Показатели контроля",
 "Nazoratga olish rejasi": "План постановки на контроль",
 "Nurafshon": "Нурафшан",
 "Nurafshon · Musodarada": "Нурафшан · В конфискации",
 "Nurafshon majmuasidagi xonadon": "Квартира в комплексе Нурафшан",
 "O'tgan yil": "Прошлый год",
 "O'tkazilgan ko'riklar bo'yicha o'rtacha holat balli": "Средний балл состояния по проведённым осмотрам",
 "O'zbekiston hududlari bo'yicha obyektlar faollik xaritasi": "Карта активности объектов по регионам Узбекистана",
 "Obyekt sotilguncha bank balansida nazoratda turadi — birinchi ko’rik va sug’urta rasmiylashtirish muddatlarini belgilang.": "До продажи объект остаётся под контролем на балансе банка — установите сроки первичного осмотра и оформления страховки.",
 "Obyekt surati": "Фото объекта",
 "Obyektlar holati: Bank nazoratida 1082 (87%), Ijaraga berilgan 104 (8%), Musodara jarayonida 42 (3%), Auksionda 20 (2%)": "Статусы объектов: Под контролем банка 1082 (87%), Сдано в аренду 104 (8%), В процессе конфискации 42 (3%), На аукционе 20 (2%)",
 "Obyektlarni qidirish": "Поиск объектов",
 "Obyektni ochish": "Открыть объект",
 "Obyektning 3D ko'rinishi": "3D-вид объекта",
 "Obyektning xavfsizlik qamrovi va hujjatlar to'liqligi bo'yicha umumiy baho": "Общая оценка охвата безопасности и полноты документов объекта",
 "Ochiq aktiv hodisalari — yuridik ish bo'limida": "Открытые события по активам — в разделе юридической работы",
 "Ofis qavat 5 — kattalashtirilgan ko'rinish": "Офис, 5-й этаж — увеличенный вид",
 "Oflayn rejim.": "Оффлайн-режим.",
 "Oldingi sahifaga qaytish": "Вернуться на предыдущую страницу",
 "Oxirgi zaxira nusxa": "Последняя резервная копия",
 "Oy": "Месяц",
 "Oylik faoliyat hisoboti yuklab olinmoqda": "Ежемесячный отчёт о деятельности скачивается",
 "Pa": "Чт",
 "Panel yopildi": "Панель закрыта",
 "PDF hisobot": "PDF-отчёт",
 "PDF pasport": "PDF-паспорт",
 "PDF ro'yxat": "PDF-список",
 "PDF sifatida": "В формате PDF",
 "Penthouse": "Пентхаус",
 "Polislar ro'yxati XLSX ga yuklanmoqda": "Список полисов выгружается в XLSX",
 "Portfel, tasdiqlash, hisobot": "Портфель, согласование, отчётность",
 "PostgreSQL 15.4": "PostgreSQL 15.4",
 "Pul oqimi hisoboti – 2024 Q1": "Отчёт о движении денежных средств – 2024 Q1",
 "Pul oqimi hisoboti yuklab olinmoqda": "Отчёт о движении денежных средств скачивается",
 "Pul oqimi tafsiloti": "Детали денежного потока",
 "Push bildirishnoma": "Push-уведомления",
 "Qamrov — baholangan qiymatdan kam emas": "Покрытие — не менее оценочной стоимости",
 "Qamrovsiz obyekt — hodisa": "Объект без покрытия — событие",
 "Qaror yuklab olinmoqda": "Решение скачивается",
 "Qavatlar": "Этажи",
 "Qavatlar bo'yicha PDF": "PDF по этажам",
 "Qayta ko'rib chiqish": "На повторное рассмотрение",
 "Qayta tekshirish": "Проверить повторно",
 "Qiymat tahlili": "Анализ стоимости",
 "Qiymat yangilandi": "Стоимость обновлена",
 "Qiymati pasayganlar": "Со снизившейся стоимостью",
 "Qo'lda tasdiqlash": "Ручное подтверждение",
 "Qo'lda tasdiqlash oynasi ochildi": "Открыто окно ручного подтверждения",
 "Qo'ng'iroq": "Звонок",
 "Qo'ng'iroq qilish": "Позвонить",
 "Qo'shimcha": "Дополнительно",
 "Qoldiq qarz — faol muammoli yozuvlar bo'yicha": "Остаток долга — по активным проблемным записям",
 "Qolgan vaqt": "Оставшееся время",
 "Qulf va plombalarni almashtirish": "Замена замков и пломб",
 "Rahbar tasdiqlash ko'rinishi": "Вид согласования для руководителя",
 "Ro'yxatdan o'tgan sana": "Дата регистрации",
 "Ro'yxatdan o'tkazildi": "Зарегистрировано",
 "Ro'yxatga qaytish": "Вернуться к списку",
 "Rol tanlash": "Выбор роли",
 "rolida kerakli ruxsatlar mavjud emas.\n              Administrator bilan bog'laning yoki boshqa rol bilan kiring.": "нет необходимых прав. Свяжитесь с администратором или войдите под другой ролью.",
 "Rollar ro'yxati": "Список ролей",
 "Ruxsat yetarli emas illyustratsiyasi": "Иллюстрация: недостаточно прав",
 "Ruxsatlar belgisi illyustratsiyasi": "Иллюстрация значка прав доступа",
 "Ruxsatlar va huquqlar": "Разрешения и права",
 "Sana oralig'i": "Диапазон дат",
 "Sana oralig'ini tanlash": "Выбор диапазона дат",
 "Saralash": "Сортировка",
 "Saralash: yangi birinchi": "Сортировка: сначала новые",
 "Sattorov Jasur — Aktivlar nazorati bo'limi": "Сатторов Жасур — Отдел обеспечения",
 "Savdo markazi": "Торговый центр",
 "Savdo qavati": "Торговый этаж",
 "Savdo tushumlari": "Поступления от торгов",
 "Savdo tushumlari tafsiloti": "Детали поступлений от торгов",
 "Se": "Вт",
 "Server holati": "Состояние сервера",
 "Server holati illyustratsiyasi": "Иллюстрация состояния сервера",
 "Sessiya turi": "Тип сессии",
 "Sh": "Сб",
 "Shartnoma ko'rsatkichlari": "Показатели договоров",
 "Shartnoma muddati": "Срок договора",
 "Shartnoma obyekti": "Объект договора",
 "Shartnoma PDF yuklab olinmoqda": "Договор скачивается в PDF",
 "Shartnoma tafsilotlari": "Детали договора",
 "Shartnoma tasdiqlandi": "Договор подтверждён",
 "Shartnomalarni qidirish": "Поиск договоров",
 "Shartnomani bekor qilish": "Расторжение договора",
 "Shartnomani yuklab olish": "Скачать договор",
 "Shikast, kamomad yoki huquqiy cheklov aniqlangan": "Выявлено повреждение, недостача или правовое ограничение",
 "Sinxronizatsiya illyustratsiyasi": "Иллюстрация синхронизации",
 "So'nggi 30 kunda o'tkazilgan ko'riklar": "Осмотры, проведённые за последние 30 дней",
 "So'nggi baholashda qiymati pasaygan obyektlar": "Объекты, стоимость которых снизилась при последней оценке",
 "So'nggi chorak": "Последний квартал",
 "So'nggi oy": "Последний месяц",
 "So'nggi qayta baholash bo'yicha": "По последней переоценке",
 "So'rov qayta ko'rib chiqishga yuborildi": "Запрос отправлен на повторное рассмотрение",
 "So'rov sanasi": "Дата запроса",
 "So'rov tasdiqlandi — keyingi bosqichga o'tdi": "Запрос подтверждён — переведён на следующий этап",
 "So'rov yaratildi": "Запрос создан",
 "So'rovchi": "Заявитель",
 "Soatlik bildirishnomalar taqsimoti, eng ko'pi tushga yaqin": "Почасовое распределение уведомлений, пик ближе к полудню",
 "Sof foyda tafsiloti": "Детали чистой прибыли",
 "Sozlama bo'limlari": "Разделы настроек",
 "Sozlamalarni ochish": "Открыть настройки",
 "Sputnik": "Спутник",
 "Sputnik ko'rinishi": "Спутниковый вид",
 "Sud qarori / Ijro hujjati": "Решение суда / Исполнительный документ",
 "Sug'urta amal qilish kesimi": "Срез действия страховки",
 "Sug'urta ko'rsatkichlari": "Показатели страхования",
 "Sug'urta polisi yuklab olinmoqda": "Страховой полис скачивается",
 "Sug'urta polisi.pdf · 640 KB": "Страховой полис.pdf · 640 КБ",
 "Sug'urta polisini bank nomiga rasmiylashtirish": "Оформление страхового полиса на имя банка",
 "Sug'urta talablari": "Требования к страхованию",
 "ta batafsil yozuv": "детальных записей",
 "ta muammoli yozuv": "проблемных записей",
 "ta muddati o'tgan": "просрочено",
 "ta yozuvda": "записей",
 "Tahlil fayli yuklab olinmoqda": "Файл анализа скачивается",
 "Tanlangan baholash tafsiloti": "Детали выбранной оценки",
 "Tanlangan hujjatlar arxiv sifatida yuklanmoqda": "Выбранные документы скачиваются архивом",
 "Tanlangan obyekt ma'lumotlari": "Данные выбранного объекта",
 "Tanlangan yozuv bo'yicha hisob-kitob": "Расчёт по выбранной записи",
 "Taqdimot (PPTX)": "Презентация (PPTX)",
 "Taqqoslash rejimi: 2-uchastkani tanlang": "Режим сравнения: выберите второй участок",
 "Tarkib": "Состав",
 "Tarkibiy qism": "Составная часть",
 "Tasdiqlar bildirishnomalari sozlamasi": "Настройка уведомлений о согласованиях",
 "Tasdiqlar va topshiriqlar": "Согласования и поручения",
 "Tasdiqlash hujjatlari illyustratsiyasi": "Иллюстрация документов согласования",
 "Tasdiqlash jarayoni illyustratsiyasi": "Иллюстрация процесса согласования",
 "Tasdiqlash jarayonlarini ko'rib chiqing va vazifalaringizni boshqaring.": "Просматривайте процессы согласования и управляйте своими задачами.",
 "Tasdiqlash navbati": "Очередь согласования",
 "Tasnif jadvali XLSX ga yuklanmoqda": "Таблица классификации выгружается в XLSX",
 "Tasnif, zaxira, qiymat nazorati": "Классификация, резерв, контроль стоимости",
 "Tavakkalchilik ko'rsatkichlari": "Показатели рисков",
 "Tavakkalchilik roli tafsiloti": "Детали роли риск-менеджера",
 "Tavakkalchiliklarni boshqarish departamenti": "Департамент управления рисками",
 "Tayinlangan chiqishlar — ko'rik rejasidan": "Назначенные выезды — из плана осмотров",
 "Texnik hisobot": "Технический отчёт",
 "Texnik pasport.pdf yuklab olinmoqda": "Технический паспорт.pdf скачивается",
 "Texnik xizmat illyustratsiyasi": "Иллюстрация технического обслуживания",
 "Tezkor amallar": "Быстрые действия",
 "Tezkor havolalar": "Быстрые ссылки",
 "Tezkor statistikalar": "Быстрая статистика",
 "Tizim administratori": "Системный администратор",
 "Tizim bildirishnomalari sozlamasi": "Настройка системных уведомлений",
 "Tizim boshqaruvi": "Управление системой",
 "Tizim boshqaruvi ruxsatlari": "Права на управление системой",
 "Tizim diagnostikasi": "Диагностика системы",
 "Tizim faoliyati va o'zgarishlarni ko'rish": "Просмотр действий и изменений в системе",
 "Tizim holati": "Состояние системы",
 "Tizim ichida": "В системе",
 "Tizim ishlash vaqti": "Время работы системы",
 "Tizim parametrlari — quyida": "Параметры системы — ниже",
 "Tizim versiyasi": "Версия системы",
 "Tizimning asosiy ishlash parametrlarini sozlang.": "Настройте основные рабочие параметры системы.",
 "To'liq ekranni ko'rish": "Смотреть в полноэкранном режиме",
 "To'lov jadvali": "График платежей",
 "To'lov jadvali XLSX yuklab olinmoqda": "График платежей скачивается в XLSX",
 "To'lov jadvalini yuklab olish": "Скачать график платежей",
 "To'lov sharti": "Условие оплаты",
 "To'lov summasi": "Сумма платежа",
 "To'lovlar": "Платежи",
 "Toifalar bo'yicha qarz taqsimoti": "Распределение долга по категориям",
 "Topshiriqlar": "Поручения",
 "Toshkent · Auksionda": "Ташкент · На аукционе",
 "Toshkent · Musodarada": "Ташкент · В конфискации",
 "Transport va uskuna — har oyda": "Транспорт и оборудование — ежемесячно",
 "Tugash sanasi": "Дата окончания",
 "Turar-joy binosi": "Жилое здание",
 "Turini tanlang": "Выберите тип",
 "Tuzilish jarayonida": "В процессе заключения",
 "Tuzilish jarayonidagilar": "В процессе заключения",
 "Uchastka aerofoto ko'rinishi — chegara polygon bilan": "Аэрофотоснимок участка — с полигоном границы",
 "Uchastka hujjatlari ko'rish oynasi": "Окно просмотра документов участка",
 "Uchastka joylashuvi": "Расположение участка",
 "Uchastkalar ro'yxati eksport qilinmoqda": "Список участков экспортируется",
 "Uchastkani taqqoslash": "Сравнение участков",
 "Ulanish qayta tekshirilmoqda…": "Подключение проверяется повторно…",
 "Umumiy maydon tahlili": "Анализ общей площади",
 "Ushbu bo'limni ochish uchun": "Для открытия этого раздела у роли",
 "Uzaytirish": "Продление",
 "Uzaytirish — muddatdan 30 kun oldin": "Продление — за 30 дней до срока",
 "Uzaytirish jarayoni": "Процесс продления",
 "Uzaytirish jarayoni boshlandi": "Начат процесс продления",
 "Valyuta va soliqlar": "Валюта и налоги",
 "Valyuta va soliqlar sozlamalari": "Настройки валюты и налогов",
 "Video konferensiya": "Видеоконференция",
 "Viloyat, tuman, ko'cha, uy": "Область, район, улица, дом",
 "Xarajatlar tafsiloti": "Детали затрат",
 "Xarid so'rovnomasi": "Заявка на покупку",
 "Xarita rejimi": "Режим карты",
 "Xatcho'pga qo'shish": "Добавить в закладки",
 "Xatolik va holat ekranlari": "Экраны ошибок и состояний",
 "Xatolik va holatlar galereyasi": "Галерея ошибок и состояний",
 "Xavfsizlik rejasi ochildi — evakuatsiya yo'nalishlari": "Открыт план безопасности — маршруты эвакуации",
 "Xavfsizlik xizmatiga qo'ng'iroq qilish": "Позвонить в службу безопасности",
 "Xavfsizlik xizmatiga qo'ng'iroq: 101": "Звонок в службу безопасности: 101",
 "Xizmat ko'rsatish": "Обслуживание",
 "Xizmat ko'rsatish tafsiloti": "Детали обслуживания",
 "Xonalar (3-qavat)": "Помещения (3-й этаж)",
 "Xonalar ro'yxati XLSX": "Список помещений XLSX",
 "Ya": "Вс",
 "Yangi hujjat yaratish": "Создание нового документа",
 "Yangi obyekt": "Новый объект",
 "Yangi vazifa": "Новая задача",
 "Yangi yer maydoni": "Новый земельный участок",
 "Yanvardan maygacha daromad ustunlari, may eng yuqori": "Столбцы поступлений с января по май, максимум в мае",
 "Yaqin atrofdagi uy — kattalashtirilgan ko'rinish": "Дом поблизости — увеличенный вид",
 "Yaratiladi (WO avtomatik)": "Создаётся (WO автоматически)",
 "Yer turi": "Тип земли",
 "Yer uchastkalari — yarim yilda": "Земельные участки — раз в полгода",
 "Yer uchastkalari sug'urtalanmaydi": "Земельные участки не страхуются",
 "Yer uchastkalarini boshqarish va monitoring": "Управление земельными участками и мониторинг",
 "Yer uchastkasi — kattalashtirilgan ko'rinish": "Земельный участок — увеличенный вид",
 "Yig'ma statistika": "Сводная статистика",
 "Yillik": "Ежегодно",
 "Yillik muddati o'tgan baholashlar": "Оценки с истёкшим годовым сроком",
 "Yillik to'lov": "Годовой платёж",
 "Yong'in signali illyustratsiyasi": "Иллюстрация пожарного сигнала",
 "Yordam markazi": "Центр помощи",
 "Yordam va qo'llanmalar": "Помощь и руководства",
 "Yunusobod filiali · boshqaruvchi": "Филиал Юнусабад · управляющий",
 "Yunusobod xonadoni": "Квартира в Юнусабаде",
 "Yuridik departament · da'vo-ariza sektori": "Юридический департамент · сектор исковых заявлений",
 "Yuridik ko'rsatkichlar": "Юридические показатели",
 "Yurist roli tafsiloti": "Детали роли юриста",
 "Yuz mos kelmadi illyustratsiyasi": "Иллюстрация: лицо не распознано",
 "Yuz tanish qayta ishga tushirildi": "Распознавание лица перезапущено",
 "Zarafshon Tekstil": "Зарафшон Текстиль",
 "Zaxira generator — kattalashtirilgan ko'rinish": "Резервный генератор — увеличенный вид",
 "Zaxira ko'rsatkichlari": "Показатели резерва",
 "Zaxira toifa stavkasi bo'yicha hisoblanadi": "Резерв рассчитывается по ставке категории",
 "Bosqich o'tkazish": "Перевод этапа",
 "Aktivlar nazorati": "Контроль активов",
 "Hisobdan chiqarish": "Снятие с учёта",
 "Lot rasmiylashtirish": "Оформление лота",
 "Portfel": "Портфель",
 "Xatolik va holatlar": "Ошибки и состояния",
 "2D reja ko'rinishi": "2D-вид плана",
 "2D xarita rejimi": "Режим 2D-карты",
 "3D ko'rinish": "3D-вид",
 "3D xarita rejimi": "Режим 3D-карты",
 "Administrator kirishi": "Вход администратора",
 "Amallar: ko'rish / yuklab olish / o'chirish": "Действия: просмотр / скачивание / удаление",
 "Arxiv yozuvi —": "Архивная запись —",
 "Auksion natijasini rasmiylashtirish —": "Оформление результата аукциона —",
 "Avtomatik jadval qo'shildi": "Автоматическое расписание добавлено",
 "Avval obyektni tanlang": "Сначала выберите объект",
 "Barcha bildirishnomalar o'qilgan deb belgilandi": "Все уведомления отмечены как прочитанные",
 "Barcha obyektlar ko'rinishga keltirildi": "Все объекты показаны на карте",
 "Dalil yoki izoh kiritilishi shart": "Необходимо указать подтверждение или комментарий",
 "Davr:": "Период:",
 "Faqat Administrator hodisani yopishi mumkin": "Закрыть событие может только администратор",
 "Hal qilindi deb belgilash": "Отметить как решённое",
 "Havola yuborish": "Отправить ссылку",
 "Hisobot navbatga qo'yildi — tayyor bo'lganda xabar beramiz": "Отчёт поставлен в очередь — сообщим о готовности",
 "Hodisa o'chirildi": "Событие удалено",
 "Hodisa yangilandi": "Событие обновлено",
 "Hodisa yopildi deb belgilandi": "Событие отмечено как закрытое",
 "Hodisani hal qilish": "Решение события",
 "Hodisani o'chirish": "Удаление события",
 "Hodisani tahrirlash": "Редактирование события",
 "Hujjat yuklandi va tasdiqlashga yuborildi": "Документ загружен и отправлен на согласование",
 "Ish yakuniy bosqichda — obyekt realizatsiyaga tayyor": "Дело на финальном этапе — объект готов к реализации",
 "Ko'rik tayinlandi": "Осмотр назначен",
 "Moliyaviy hisobot eksport qilinmoqda": "Финансовый отчёт экспортируется",
 "O'zgarishlar saqlandi": "Изменения сохранены",
 "Obyekt qabul qilindi — WO-2026-0001 texnik topshiriq yaratildi": "Объект принят — создано техническое задание WO-2026-0001",
 "Obyektni nazoratga olish": "Постановка объекта на контроль",
 "Obyektni tahrirlash": "Редактирование объекта",
 "Parolni tiklash": "Восстановление пароля",
 "Qarzdorlar reyestri XLSX shaklida tayyorlanmoqda": "Реестр должников формируется в формате XLSX",
 "Rejalashtirilgan sanani kiriting": "Укажите планируемую дату",
 "Sarlavha kiritilishi shart": "Необходимо указать заголовок",
 "Shartnoma bekor qilish jarayoni boshlandi": "Начат процесс расторжения договора",
 "So'rov rad etildi": "Запрос отклонён",
 "So'rov rad etildi va muallifga qaytarildi": "Запрос отклонён и возвращён автору",
 "So'rovni rad etish": "Отклонение запроса",
 "Sotuvni tasdiqlash": "Подтверждение продажи",
 "Sozlamalar muvaffaqiyatli saqlandi": "Настройки успешно сохранены",
 "Sputnik ko'rinishi yoqildi": "Включён спутниковый вид",
 "Sxematik xarita ko'rinishi": "Схематический вид карты",
 "Tahrirlash oynasi": "Окно редактирования",
 "Texnik xulosa kiritilishi shart": "Необходимо указать техническое заключение",
 "Tiklash havolasi emailga yuborildi": "Ссылка для восстановления отправлена на email",
 "Uchastka arxivlandi": "Участок архивирован",
 "Uchastkani arxivlash": "Архивирование участка",
 "Undiruv ishlari reyestri XLSX shaklida tayyorlanmoqda": "Реестр дел о взыскании формируется в формате XLSX",
 "Vazifa nomini kiriting": "Укажите название задачи",
 "Xona ma'lumotlari saqlandi": "Данные помещения сохранены",
 "Xonani tahrirlash": "Редактирование помещения",
 "Yangi avtomatik jadval": "Новое автоматическое расписание",
 "Yangi hisobot yaratish": "Создание нового отчёта",
 "Yangi hodisa qo'shish": "Добавление нового события",
 "Yangi hodisa yaratildi": "Создано новое событие",
 "Yangi obyekt qo'shish": "Добавление нового объекта",
 "Yangi obyekt qoralama sifatida saqlandi": "Новый объект сохранён как черновик",
 "Yangi rol yaratildi": "Создана новая роль",
 "Yangi rol yaratish": "Создание новой роли",
 "Yangi uchastka ro'yxatga qo'shildi": "Новый участок добавлен в список",
 "Yangi vazifa qo'shildi": "Новая задача добавлена",
 "Yangi yer maydoni qo'shish": "Добавление нового земельного участка",
 "Yuklash": "Загрузить",
 "rolida kerakli ruxsatlar mavjud emas.": "нет необходимых прав.",
 "Administrator bilan bog'laning yoki boshqa rol bilan kiring.": "Свяжитесь с администратором или войдите под другой ролью.",
 "Ishchi tizimda rol hisob yozuviga biriktiriladi va serverdan keladi. Tanlov faqat namoyish uchun.": "В рабочей системе роль закреплена за учётной записью и приходит с сервера. Выбор — только для ознакомления.",
 "Filial rahbari": "Руководитель филиала",
 "Kredit menejeri": "Кредитный менеджер",
 "Aktivlar nazorati mutaxassisi": "Специалист службы контроля активов",
 "Yurist": "Юрист",
 "Tavakkalchilik menejeri": "Риск-менеджер",
 "Tavakkalchilik": "Риски",
 "Namoyish rejimi — ish o'rni": "Ознакомительный режим — рабочее место",
 "Muammoli portfel": "Проблемный портфель",
 "Yuridik ish": "Юридическая работа",
 "Tasnif va zaxira": "Классификация и резерв",
 "Aktivlar reyestri": "Реестр активов",
 "Ko'rik rejasi": "План осмотров",
 "Qayta baholash": "Переоценка",
 "Sug'urta nazorati": "Контроль страхования",
 "Da'vo va sud ishlari": "Претензии и суды",
 "Aktiv hodisalari": "События по активам",
 "Balansga qabul": "Приём на баланс",
 "Savdo": "Торги",
 "Aktivlar tasnifi": "Классификация активов",
 "Ish navbati": "Рабочая очередь",
 "Aktivlar tasnifi va zaxira": "Классификация активов и резерв",
 "Muddati o'tgan kunlar bo'yicha toifa, toifa bo'yicha imkoniyatli yo'qotishlar zaxirasi": "Категория по дням просрочки, резерв на возможные потери по категории",
 "Qoldiq qarz": "Остаток долга",
 "Shakllantirilgan zaxira": "Сформированный резерв",
 "Ta'minot bilan qoplash": "Покрытие обеспечением",
 "Ta'minlanmagan qoldiq": "Необеспеченный остаток",
 "Toifalar kesimi": "Разрез по категориям",
 "Yozuvlar bo'yicha": "По записям",
 "Toifa": "Категория",
 "Kechikish": "Просрочка",
 "Yozuv": "Записей",
 "Stavka": "Ставка",
 "Zaxira": "Резерв",
 "Qarzdor": "Должник",
 "Qoplash": "Покрытие",
 "Yaxshi": "Хорошая",
 "Standart": "Стандартная",
 "Substandart": "Субстандартная",
 "Shubhali": "Сомнительная",
 "Umidsiz": "Безнадёжная",
 "kechikishsiz": "без просрочки",
 "Zaxiraga ajratma": "Отчисление в резерв",
 "Toifa migratsiyasi": "Миграция категории",
 "Aktiv obyekti kartochkasi": "Карточка объекта актива",
 "Me'yoriy qiymatlar tasdiqlanishi kerak": "Нормативные значения требуют утверждения",
 "Zaxira stavkasi": "Ставка резерва",
 "Ta'minot baholangan qiymati": "Оценочная стоимость актива",
 "Qoplash darajasi": "Уровень покрытия",
 "Tasnif toifasi": "Категория классификации",
 "Aktivlar monitoringi": "Мониторинг активов",
 "Har bir obyekt bo'yicha ko'rik, sug'urta va baholash holati — bir ekranda": "Осмотр, страховка и оценка по каждому объекту — на одном экране",
 "Ko'riklar (portfel)": "Осмотры (портфель)",
 "Sug'urta amalda": "Страховка действует",
 "Baholash dolzarb": "Оценка актуальна",
 "Ochiq hodisalar": "Открытые события",
 "Shikast, kamomad, huquqiy cheklov": "Повреждение, недостача, правовое ограничение",
 "Batafsil nazoratdagi obyektlar": "Объекты на детальном контроле",
 "Nazorat balli": "Балл контроля",
 "So'nggi ko'rik": "Последний осмотр",
 "Sug'urta": "Страховка",
 "Baholash": "Оценка",
 "E'tibor talab qilinadi": "Требует внимания",
 "Ko'rik o'tkazilmadi": "Осмотр не проведён",
 "Rejalashtirilgan": "Запланирован",
 "Polis yo'q": "Нет полиса",
 "Muddati o'tgan": "Просрочен",
 "Eskirgan": "Устарела",
 "Baholanmagan": "Не оценён",
 "Hisobot": "Отчёт",
 "Aktiv obyektlarini joyida tekshirish: rejalashtirilgan chiqishlar va natijalar": "Проверка активовых объектов на месте: запланированные выезды и результаты",
 "Shu oyda rejalashtirilgan": "Запланировано в этом месяце",
 "Qayta tayinlash talab qilinadi": "Требуется переназначение",
 "O'tkazildi (30 kun)": "Проведено (30 дней)",
 "Dalolatnomalar biriktirilgan": "Акты приложены",
 "O'rtacha holat balli": "Средний балл состояния",
 "100 ballik shkala bo'yicha": "По 100-балльной шкале",
 "Navbatdagi va kechikkan chiqishlar": "Предстоящие и просроченные выезды",
 "O'tkazilgan ko'riklar": "Проведённые осмотры",
 "Butun tarix →": "Вся история →",
 "Ko'rik davriyligi": "Периодичность осмотров",
 "Ko'rik tayinlash": "Назначить осмотр",
 "Ko'rik varaqasi": "Лист осмотра",
 "Qayta tayinlash": "Переназначить",
 "Dalolatnoma": "Акт",
 "Inspektor": "Инспектор",
 "Holat balli": "Балл состояния",
 "Rejali": "Плановый",
 "Navbatdan tashqari": "Внеплановый",
 "Rejada": "Запланирован",
 "Jadval": "График",
 "Ko'rik dalolatnomasi": "Акт осмотра",
 "Joyida o'tkazilgan ko'rik natijalari": "Результаты осмотра на месте",
 "Rejaga qaytish": "К плану",
 "Tekshiruv bandlari": "Пункты проверки",
 "Fotojamlanma": "Фотофиксация",
 "Xulosa": "Заключение",
 "Ko'rik turi": "Тип осмотра",
 "Sana": "Дата",
 "Ish bosqichi": "Этап дела",
 "Qarzdor ishtiroki": "Участие должника",
 "Dalolatnoma holati": "Статус акта",
 "Bog'liq ish": "Связанное дело",
 "Ish raqami": "Номер дела",
 "Bosqich": "Этап",
 "Mas'ul": "Ответственный",
 "Obyekt kartochkasi": "Карточка объекта",
 "Umumiy ko'rinish": "Общий вид",
 "Kirish qismi": "Входная часть",
 "Hudud chegarasi": "Граница участка",
 "Atrof holati": "Состояние вокруг",
 "Imzolangan": "Подписан",
 "Kutilmoqda": "Ожидается",
 "Aktiv obyektlari bo'yicha polislar amal qilishi va qamrov nazorati": "Действие полисов и контроль покрытия по активовым объектам",
 "Amaldagi polislar (portfel)": "Действующие полисы (портфель)",
 "30 kunda tugaydi": "Истекает за 30 дней",
 "Uzaytirish xatlari yuborilgan": "Письма о продлении отправлены",
 "Qamrovsiz": "Без покрытия",
 "Muddati o'tgan yoki polis yo'q": "Просрочен или полиса нет",
 "Sug'urta summasi": "Страховая сумма",
 "Polislar reyestri": "Реестр полисов",
 "Talab va tartib": "Требования и порядок",
 "Polis": "Полис",
 "Sug'urtalovchi": "Страховщик",
 "Summa": "Сумма",
 "Qamrov": "Покрытие",
 "Tugash": "Окончание",
 "Tez orada tugaydi": "Скоро истекает",
 "Talab etilmaydi": "Не требуется",
 "Ta'minot qiymatining dolzarbligi: baholash muddatlari va qiymat dinamikasi": "Актуальность стоимости актива: сроки оценки и динамика стоимости",
 "Dolzarb baholash (portfel)": "Актуальная оценка (портфель)",
 "90 kunda eskiradi": "Устареет за 90 дней",
 "Buyurtmalar rejalashtirilmoqda": "Заказы планируются",
 "Zaxira hisobi shartli qiymatda": "Резерв считается по условной стоимости",
 "Qiymati pasaygan": "Стоимость снизилась",
 "Baholashlar reyestri": "Реестр оценок",
 "So'nggi baholash": "Последняя оценка",
 "Baholovchi": "Оценщик",
 "Qiymat": "Стоимость",
 "Dinamika": "Динамика",
 "Keyingi muddat": "Следующий срок",
 "Baholash buyurtmasi": "Заказ оценки",
 "Dolzarb": "Актуальна",
 "Tez orada eskiradi": "Скоро устареет",
 "O'zgarish": "Изменение",
 "Baholash usuli": "Метод оценки",
 "Baholovchi tashkilot": "Оценочная организация",
 "Baholash sanasi": "Дата оценки",
 "Ko'riklar tarixi": "История осмотров",
 "Barcha o'tkazilgan va rejalashtirilgan ko'riklar jurnali": "Журнал всех проведённых и запланированных осмотров",
 "Yig'ma ko'rsatkichlar": "Сводные показатели",
 "Jami yozuvlar": "Всего записей",
 "Rejali ko'riklar": "Плановых осмотров",
 "Qamrab olingan obyektlar": "Охвачено объектов",
 "Ko'rik": "Осмотр",
 "Turi": "Тип",
 "Ball": "Балл",
 "O'tkazildi": "Проведён",
 "Aktiv obyektiga chiqishni rejalashtirish: obyekt, tur va ijrochi": "Планирование выезда на активовый объект: объект, тип и исполнитель",
 "Obyekt": "Объект",
 "Tur va sana": "Тип и дата",
 "Ijrochi": "Исполнитель",
 "Aktiv obyekti": "Объект актива",
 "Obyektni tanlang": "Выберите объект",
 "Asos": "Основание",
 "Reglament davriyligi": "Регламентная периодичность",
 "Aktiv hodisasi": "Событие по активу",
 "Bosqich talabi": "Требование этапа",
 "Rahbariyat topshirig'i": "Поручение руководства",
 "Rejalashtirilgan sana": "Планируемая дата",
 "Izoh (ixtiyoriy)": "Комментарий (необязательно)",
 "Inspektorni tanlang": "Выберите инспектора",
 "Qarzdorni xabardor qilish": "Уведомление должника",
 "Yozma xabarnoma": "Письменное уведомление",
 "Xabardor qilinmaydi": "Без уведомления",
 "Tayinlov xulosasi": "Сводка назначения",
 "Davom etish": "Продолжить",
 "Orqaga": "Назад",
 "Tayinlash": "Назначить",
 "Xabardor qilish": "Уведомление",
 "Dala ko'rigi": "Полевой осмотр",
 "Inspektorning kunlik marshruti — mobil ish o'rnining veb-ko'rinishi": "Дневной маршрут инспектора — веб-представление мобильного рабочего места",
 "Marshrutda": "В маршруте",
 "Tayinlangan chiqishlar": "Назначенные выезды",
 "Yakunlangan": "Завершено",
 "Dalolatnoma rasmiylashtirilgan": "Акт оформлен",
 "Sinxronizatsiya": "Синхронизация",
 "Yuborilmagan natijalar navbati": "Очередь неотправленных результатов",
 "Bugungi marshrut": "Маршрут на сегодня",
 "Joriy chiqish varag'i": "Лист текущего выезда",
 "Dalolatnomani rasmiylashtirish": "Оформить акт",
 "Marshrut varaqasi": "Маршрутный лист",
 "Joriy chiqish": "Текущий выезд",
 "Navbatda": "В очереди",
 "Obyekt tarkibi": "Состав объекта",
 "Kadastr birliklari": "Кадастровые единицы",
 "Baholashdagi ulush": "Доля в оценке",
 "Kadastr birligi": "Кадастровая единица",
 "Huquqiy holat": "Правовой статус",
 "Ko'rik qaydi": "Отметка осмотра",
 "Kadastr hujjatlari": "Кадастровые документы",
 "Ta'minot predmeti": "Предмет актива",
 "Asosiy ta'minot predmeti": "Основной предмет обеспечения",
 "Yordamchi maydon": "Вспомогательная площадь",
 "Texnik maydon": "Техническая площадь",
 "Aktivlar nazorati ish o'rni": "Рабочее место службы контроля активов",
 "Tavakkalchilik ish o'rni": "Рабочее место риск-менеджера",
 "Yuridik ish o'rni": "Рабочее место юриста",
 "Navbatdagi ko'riklar": "Предстоящие осмотры",
 "Baholash muddati": "Срок оценки",
 "Eskirgan yoki tugayotgan baholashlar": "Устаревшие или истекающие оценки",
 "Qamrovsiz yoki tugayotgan polislar": "Полисы без покрытия или истекающие",
 "Bugungi ishlar": "Дела на сегодня",
 "Ko'rik rejasi →": "План осмотров →",
 "To'liq jadval →": "Полная таблица →",
 "Muammoli qoldiq": "Проблемный остаток",
 "Sud bosqichida": "На судебной стадии",
 "Da'vo va sud jarayonidagi ishlar": "Дела на стадии претензии и суда",
 "Ijro bosqichida": "На стадии исполнения",
 "Qaror ijrosidagi ishlar": "Дела в исполнении БПИ",
 "Huquqiy hodisalar": "Правовые события",
 "Ruxsatsiz foydalanish va cheklovlar": "Несанкционированное использование и ограничения",
 "Sud qarorlari va ijro varaqalar": "Судебные решения и исполнительные листы",
 "Yaqinlashayotgan muddatlar": "Приближающиеся сроки",
 "Barcha ishlar →": "Все дела →",
 "Qarzdorlar": "Должники",
 "Sud ishlari": "Судебные дела",
 "Ko'riklar tarixi →": "История осмотров →",
 "Yillik nazorat ko'rigi": "Контрольных осмотров за год",
 "180 kundan ortiq": "более 180 дней",
 "30 kungacha": "до 30 дней",
 "31–90 kun": "31–90 дней",
 "4 ekran": "4 экрана",
 "9 ekran": "9 экранов",
 "91–180 kun": "91–180 дней",
 "94% onlayn": "94% онлайн",
 "Admin": "Админ",
 "Administrator": "Администратор",
 "Administrator sifatida kirish →": "Войти как администратор →",
 "Agrokredit": "Агрокредит",
 "Algoritm": "Алгоритм",
 "Aloqa": "Связь",
 "Aloqa kanali": "Канал связи",
 "Aloqa kanallari va qurilmalar": "Каналы связи и устройства",
 "Aloqa yo'q": "Нет связи",
 "Amalda": "Действует",
 "Amallar": "Действия",
 "Arxivdan qidirish": "Поиск по архиву",
 "Arxivlash": "В архив",
 "Asosiy kirish": "Главный вход",
 "Asosiy ko'rsatkichlar": "Ключевые показатели",
 "Asosiy navigatsiya": "Основная навигация",
 "Asosiy qarz, foiz va penya bilan": "С основным долгом, процентами и пеней",
 "Asosiy rekvizitlar": "Основные реквизиты",
 "Audit jurnali": "Журнал аудита",
 "Auditor": "Аудитор",
 "Auksion": "Аукцион",
 "Auksion ishtirokchilari": "Участники аукциона",
 "Auksion natijasini rasmiylashtirish": "Оформление результата аукциона",
 "Auksion oldi ko'rigi": "Предаукционный осмотр",
 "Auksion savdolari": "Аукционные торги",
 "Auksion savdolari va doimiy arxiv": "Аукционные торги и постоянный архив",
 "Auksion tushumlari": "Поступления от аукционов",
 "Auksion va ijara tushumlari": "Поступления от аукционов и аренды",
 "Auksionda": "На аукционе",
 "Auksiondagi obyektlar ro'yxati": "Список объектов на аукционе",
 "Auksionga chiqarildi": "Выставлено на аукцион",
 "Auksionga chiqarish": "Выставление на аукцион",
 "Avtokredit": "Автокредит",
 "Avtomatik hisobotlar": "Автоматические отчёты",
 "Avtotransport": "Автотранспорт",
 "Avtoturargoh": "Автостоянка",
 "Axborot texnologiyalari departamenti": "Департамент информационных технологий",
 "Aylanma mablag' krediti": "Кредит на оборотные средства",
 "Baholangan qiymat": "Оценочная стоимость",
 "Baholangan qiymati": "Оценочная стоимость",
 "Baholash hisoboti": "Отчёт об оценке",
 "Band": "Занято",
 "Bandlik darajasi": "Уровень занятости",
 "Bank balansida": "На балансе банка",
 "Bank nazoratida": "Под контролем банка",
 "Bank nazoratidagi aktiv obyektlarini kechayu kunduz kuzatish va trevogalarga javob berish": "Круглосуточное наблюдение за активовыми объектами банка и реагирование на тревоги",
 "Barcha bildirishnomalar va yangiliklar markazi": "Центр всех уведомлений и новостей",
 "Barcha bosqichlar": "Все этапы",
 "Barcha eshiklar": "Все двери",
 "Barcha filiallar": "Все филиалы",
 "Barcha holatlar": "Все статусы",
 "Barcha hududlar": "Все регионы",
 "Barcha obyektlar": "Все объекты",
 "Barcha qurilmalar": "Все устройства",
 "Barcha turlar": "Все типы",
 "Barcha undiruv ishlari": "Все дела о взыскании",
 "Barcha viloyatlar": "Все области",
 "Barcha yillar": "Все годы",
 "Barchasi": "Все",
 "Barchasini ko'rish": "Смотреть все",
 "Barqaror": "Стабильно",
 "Bartaraf etilmoqda": "Устраняется",
 "Bekor qilish": "Отменить",
 "Belgilangan ko'riklar jadvali": "График назначенных осмотров",
 "Beqaror": "Нестабильно",
 "Bildirishnoma sozlamalari": "Настройки уведомлений",
 "Bildirishnomalar": "Уведомления",
 "Biriktirilgan shartnomalar": "Закреплённые договоры",
 "Biriktirish": "Прикрепить",
 "Bo'lim": "Отдел",
 "Bo'lim sahifalari": "Разделы",
 "Sudni tanlang": "Выберите отдел",
 "Bo'sh": "Свободно",
 "Bosh kirish eshigi": "Главная входная дверь",
 "Bosh sahifaga qaytish": "Вернуться на главную",
 "Boshlang'ich holat": "Начальный статус",
 "Boshqa qurilmalar": "Другие устройства",
 "Boshqaruv paneli": "Панель управления",
 "Boshqaruv raisi o'rinbosari": "Заместитель председателя правления",
 "Bosqichni o'zgartirish": "Изменение этапа",
 "Brifing varag'i": "Лист брифинга",
 "Bugungi faollik": "Активность за сегодня",
 "Bugungi mehmonlar": "Сегодняшние посетители",
 "Bugungi tashriflar": "Визиты за сегодня",
 "Bugungi tekshiruvlar": "Проверки за сегодня",
 "Chastota": "Периодичность",
 "Chiqish vaqti": "Время выхода",
 "Chiqishda xona tekshiruvi": "Проверка помещения при выходе",
 "Da'vo arizasi": "Исковое заявление",
 "Da'vo arizasi berildi": "Подано исковое заявление",
 "Da'vo arizasi berilgan ishlar": "Дела с поданным иском",
 "Da'vo va sud bosqichidagi ishlar": "Дела на исковой и судебной стадии",
 "Dala hovli": "Дача",
 "Daromad dinamikasi": "Динамика поступлений",
 "Daromad tuzilmasi": "Структура поступлений",
 "Davr": "Период",
 "Dehqonchilik": "Земледелие",
 "Dinamik": "Динамик",
 "Diqqat": "Внимание",
 "Diqqat talab qiladi": "Требует внимания",
 "Doimiy saqlash rejimi.": "Режим постоянного хранения.",
 "Eksport": "Экспорт",
 "Elektr ta'minoti": "Электроснабжение",
 "Energiya samaradorligi": "Энергоэффективность",
 "Eshik": "Дверь",
 "Eshik kirish tizimi": "Система дверного доступа",
 "Eshiklarni masofadan boshqarish": "Дистанционное управление дверями",
 "Etaj rejasi": "План этажа",
 "Excel (XLSX)": "Excel (XLSX)",
 "Face ID / domofon qurilmasi": "Устройство Face ID / домофон",
 "Face ID natijasi": "Результат Face ID",
 "Face ID orqali eshik ochish": "Открыть дверь по Face ID",
 "FaceID skaner": "Сканер FaceID",
 "Faol": "Активен",
 "Faol sessiyalar": "Активные сессии",
 "Faoliyat tahlili": "Анализ деятельности",
 "Faoliyat tarixi": "История действий",
 "Faollik tarixi": "История активности",
 "Faqat o'qish rejimi": "Режим только для чтения",
 "Fayl hajmi": "Размер файла",
 "Filial": "Филиал",
 "Filtrlar": "Фильтры",
 "Firmware versiyasi": "Версия прошивки",
 "Foiz va penya": "Проценты и пеня",
 "Format": "Формат",
 "Foydalanuvchi ko'rinishida tekshirish": "Просмотр от имени пользователя",
 "Foydalanuvchi ma'lumotlari": "Данные пользователя",
 "Foydalanuvchi nomi va parolni kiriting": "Введите имя пользователя и пароль",
 "Foydalanuvchi nomi yoki email": "Имя пользователя или email",
 "Foydalanuvchilar": "Пользователи",
 "Foydalanuvchilar va rollar": "Пользователи и роли",
 "Galereya": "Галерея",
 "Ta'minot aktivlarini nazorat qilish tizimi": "Система контроля проблемных активов",
 "Muammoli aktivlarni raqamli nazorat qilish tizimi": "Система цифрового контроля проблемных активов",
 "Aktiv obyekti kartasi": "Карточка активового объекта",
 "Aktiv obyektlari": "Обеспечениеовые объекты",
 "Aktiv obyektlari rentabelligi (ROA)": "Рентабельность активовых объектов (ROA)",
 "Aktiv obyektlari reyestri": "Реестр активовых объектов",
 "Ta'minot portfeli": "Обеспечениеовый портфель",
 "Ta'minot turlari": "Типы актива",
 "Ta'minotda": "В активе",
 "Gaz ta'minoti": "Газоснабжение",
 "Har chorakda": "Ежеквартально",
 "Har oyda": "Ежемесячно",
 "Hisobot davri": "Отчётный период",
 "Hisobot markazi": "Центр отчётности",
 "Hisobot nomi": "Название отчёта",
 "Hisobot turi": "Тип отчёта",
 "Hisobot yaratish": "Сформировать отчёт",
 "Hisobotlar": "Отчёты",
 "Hisobotlar markazi": "Центр отчётности",
 "Hodisa ochish": "Открыть происшествие",
 "Hodisa qo'shish": "Добавить происшествие",
 "Hodisalar": "Происшествия",
 "Hodisalar bo'yicha umumiy ko'rsatkichlar": "Сводные показатели по происшествиям",
 "Hodisalar dinamikasi": "Динамика происшествий",
 "Hodisalar markazi": "Центр происшествий",
 "Hodisalar xaritasi (O'zbekiston)": "Карта происшествий (Узбекистан)",
 "Holat": "Статус",
 "Holati": "Статус",
 "Hudud": "Регион",
 "Hududiy xarita": "Карта регионов",
 "Hududlar bo'yicha jami": "Итого по регионам",
 "Hujjat nomi": "Название документа",
 "Hujjat qo'shish": "Добавить документ",
 "Hujjat yuklash": "Загрузить документ",
 "Hujjatlar": "Документы",
 "Hujjatlar markazi": "Центр документов",
 "Hujjatlar topilmadi": "Документы не найдены",
 "ID raqam": "Идентификатор",
 "ID raqami": "Идентификатор",
 "IP Kamera": "IP-камера",
 "IP kamera": "IP-камера",
 "IP manzil": "IP-адрес",
 "Ichki eshik": "Внутренняя дверь",
 "Identifikatsiya": "Идентификация",
 "Ijarachi": "Арендатор",
 "Ijaraga berilgan": "Сдано в аренду",
 "Ijro hujjati muddatlari": "Сроки исполнительных документов",
 "Ijro hujjati": "Исполнительный документ",
 "Ijro hujjati ijroga qabul qilindi": "Исполнительный документ передан в исполнения",
 "Infratuzilma": "Инфраструктура",
 "Integratsiyalar": "Интеграции",
 "Interfeys tili": "Язык интерфейса",
 "Interkom izohi": "Комментарий интеркома",
 "Internet aloqasi yo'q": "Нет подключения к интернету",
 "Inventar raqami": "Инвентарный номер",
 "Investitsiya krediti": "Инвестиционный кредит",
 "Ipoteka krediti": "Ипотечный кредит",
 "Ish davomiyligi": "Длительность работы",
 "Ish hujjatlari": "Документы дела",
 "Ish jarayoni": "Рабочий процесс",
 "Ish maydoni": "Рабочая область",
 "Ishga kirish sanasi": "Дата приёма на работу",
 "Ishlab chiqarish": "Производство",
 "Ishlab chiqaruvchi": "Производитель",
 "Ishlash vaqti": "Время работы",
 "Ishlayapti": "Работает",
 "Iste'mol krediti (ta'minot bilan)": "Потребительский кредит (под актив)",
 "Jami": "Итого",
 "Jami ochiq ishlar:": "Всего открытых дел:",
 "Jami qarzdorlar": "Всего должников",
 "Jami:": "Итого:",
 "Jarayon tarixi": "История процесса",
 "Jarayonda": "В процессе",
 "Javobgacha": "До реакции",
 "Jismoniy shaxs": "Физическое лицо",
 "Jonli": "В эфире",
 "Jonli aloqa": "Живая связь",
 "Jonli kamera": "Живая камера",
 "Jonli tashrif nazorati": "Контроль визитов в реальном времени",
 "Joriy bosqich": "Текущий этап",
 "Joriy likvidlik koeffitsienti": "Коэффициент текущей ликвидности",
 "Joriy tashrif holati": "Статус текущего визита",
 "Joylashuv": "Расположение",
 "Joylashuv izohi": "Примечание к расположению",
 "Kadastr": "Кадастр",
 "Kadastr hujjati": "Кадастровый документ",
 "Kadastr ma'lumotlari": "Кадастровые данные",
 "Kadastr raqami": "Кадастровый номер",
 "Kamera": "Камера",
 "Kamera oflayn": "Камера не в сети",
 "Kamera onlayn": "Камер онлайн",
 "Kamera tasviri": "Изображение с камеры",
 "Kamera, Face ID, domofon yoki eshik kontrollerini obyektga bog'lab, tizimga qo'shing": "Привяжите камеру, Face ID, домофон или дверной контроллер к объекту и добавьте в систему",
 "Kameralardan kuzatish": "Наблюдение с камер",
 "Kanalizatsiya": "Канализация",
 "Kanban taxtasi": "Канбан-доска",
 "Kapital rentabelligi (ROE)": "Рентабельность капитала (ROE)",
 "Karta raqami": "Номер карты",
 "Kechikish muddati": "Срок просрочки",
 "Kechikish: barchasi": "Просрочка: все",
 "Kengaytirilgan filtrlar": "Расширенные фильтры",
 "Keyingi": "Следующая",
 "Keyingi bosqichga o'tkazish": "Перевести на следующий этап",
 "Keyingi oy": "Следующий месяц",
 "Keyingi sahifa": "Следующая страница",
 "Keyingi yuborilish": "Следующая отправка",
 "Kirish": "Вход",
 "Kirish nazorati": "Контроль доступа",
 "Kirish nazorati paneli": "Панель контроля доступа",
 "Kirish nuqtasi": "Точка доступа",
 "Kirish nuqtasi (3D)": "Точка входа (3D)",
 "Kirish so'rovlar": "Запросы на вход",
 "Kirish so'rovlari": "Запросы на доступ",
 "Kirish taqiqlangan": "Доступ запрещён",
 "Kirish vaqti": "Время входа",
 "Kirish voqealari": "События доступа",
 "Kirish voqealari markazi": "Центр событий доступа",
 "Ko'rib chiqilmoqda": "На рассмотрении",
 "Ko'rik belgilangan": "Осмотр назначен",
 "Ko'rish": "Просмотр",
 "Kommunikatsiya kirish nuqtalari": "Точки ввода коммуникаций",
 "Konferensiya zali": "Конференц-зал",
 "Korporativ hisobingiz bilan kiring — kirish huquqi lavozimingizga muvofiq beriladi": "Войдите с корпоративной учётной записью — права доступа выдаются согласно должности",
 "Kredit shartnomalari": "Кредитные договоры",
 "Kredit shartnomasi": "Кредитный договор",
 "Kredit turi": "Вид кредита",
 "Kritik": "Критично",
 "Kvartira": "Квартира",
 "Lavozim": "Должность",
 "MAC manzil": "MAC-адрес",
 "Qaror chiqargan sud": "Отделение исполнения",
 "Ijro hujjatlari": "Документы исполнения",
 "ijro ijro ishi": "Исполнительное дело исполнения",
 "Ijro ishi raqami": "Номер исполнительного дела исполнения",
 "Qaror ijrosi": "Исполнение решения",
 "Obyektni balansga qabul qilish": "Приём объекта на баланс",
 "Balansga qabul qilingan": "Принято на баланс",
 "Ma'lumotlar sinxronlanmoqda": "Данные синхронизируются",
 "Manzil": "Адрес",
 "Maqsad": "Цель",
 "Maqsadli foydalanish": "Целевое использование",
 "Mas'ul mutaxassis": "Ответственный специалист",
 "Mas'ul shaxs": "Ответственное лицо",
 "Mas'ul texnik xodim": "Ответственный техник",
 "Mas'ul yurist": "Ответственный юрист",
 "Masofadan ochiladigan eshik qulfi": "Дверной замок с дистанционным управлением",
 "Masofaviy ko'rik": "Дистанционный осмотр",
 "Masofaviy ko'rik boshlash": "Начать дистанционный осмотр",
 "Masofaviy ko'rik sessiyasi": "Сессия дистанционного осмотра",
 "Maydon": "Площадь",
 "Mehmon": "Посетитель",
 "Mehmon uchun masofaviy ko'rikni boshqaring va xavfsiz kirishni ta'minlang.": "Управляйте дистанционным осмотром для посетителя и обеспечьте безопасный доступ.",
 "Meni eslab qolish": "Запомнить меня",
 "Mening qarzdorlarim": "Мои должники",
 "Mening servis topshiriqlarim": "Мои сервисные задания",
 "Mezbon": "Принимающий",
 "Mijoz": "Клиент",
 "Mijoz qo'shish": "Добавить клиента",
 "Mijoz, shartnoma raqami yoki INN...": "Клиент, номер договора или ИНН...",
 "Mikrofon": "Микрофон",
 "Mikrokreditbank": "Микрокредитбанк",
 "Mikroqarz": "Микрозайм",
 "Mikroqarz (ta'minot bilan)": "Микрозайм (под актив)",
 "Model": "Модель",
 "Modul / Rollar": "Модуль / Роли",
 "Moliya": "Финансы",
 "Moliyaviy": "Финансовые",
 "Moliyaviy hisobotlar": "Финансовые отчёты",
 "Moliyaviy ko'rsatkichlar": "Финансовые показатели",
 "Moliyaviy ko'rsatkichlar sharhi": "Обзор финансовых показателей",
 "Monitoring": "Мониторинг",
 "Monitoring intervali": "Интервал мониторинга",
 "Monitoring markazi": "Центр мониторинга",
 "Muammoli aktivlar departamenti": "Департамент проблемных активов",
 "Muddat": "Срок",
 "Muddati o'tgan kredit va lizing shartnomalari bo'yicha qarzdorlar reyestri": "Реестр должников по просроченным кредитным и лизинговым договорам",
 "Muddati o'tgan kreditlar bo'yicha da'vo, sud va majburiy ijro jarayonlarini kuzatish": "Контроль исковых, судебных и исполнительных процессов по просроченным кредитам",
 "Muddati o'tgan qarz": "Просроченная задолженность",
 "Muddati yaqinlashgan": "Срок истекает",
 "Muddatni tanlang": "Выберите срок",
 "Muhim": "Важно",
 "Muhim eslatma": "Важное напоминание",
 "Musodara dalolatnomasi": "Акт конфискации",
 "Musodara jarayonida": "В процессе конфискации",
 "Musodara qabuli": "Приём конфиската",
 "Balansga qabulga o'tish": "Перейти к приёму конфиската",
 "Musodara qilingan": "Конфисковано",
 "Musodara qilingan aktiv": "Конфискованный актив",
 "Musodara qilingan aktiv obyektlarini realizatsiya qilish": "Реализация конфискованных активовых объектов",
 "Musodara qilingan aktiv obyektlarini realizatsiya qilish: ko'rikdan hujjatlargacha yagona jarayon": "Реализация конфискованных активовых объектов: единый процесс от осмотра до документов",
 "Musodara qilingan obyektni hujjatlari bilan tizimga kiritish va nazoratga olish": "Постановка конфискованного объекта с документами на учёт и контроль",
 "Mustaqil baholash bo'yicha": "По независимой оценке",
 "Muzokarada": "На переговорах",
 "Muzokaradagi obyektlar": "Объекты на переговорах",
 "Nazorat davri": "Период контроля",
 "Nazorat markazi": "Центр контроля",
 "Nazorat xarajatlari (YTD)": "Затраты на контроль (с начала года)",
 "Nazorat, ijara va auksiondagi obyektlar": "Объекты под контролем, в аренде и на аукционе",
 "Nazoratda": "Под контролем банка",
 "Nazoratdagi obyektlar soni": "Количество объектов под контролем",
 "Nazoratga olinmoqda": "Ставится на контроль",
 "Nazoratga olish": "Постановка на контроль",
 "Nofaol": "Неактивен",
 "Norma buzildi": "Норматив нарушен",
 "Normal": "Норма",
 "O'chirish": "Удалить",
 "O'rnatish akti": "Акт установки",
 "O'rnatish muddati": "Срок установки",
 "O'rta": "Средний",
 "O'rtacha bartaraf etish vaqti": "Среднее время устранения",
 "O'rtacha javob vaqti": "Среднее время реакции",
 "O'tgan oyga nisbatan": "К прошлому месяцу",
 "O'tgan yilga nisbatan": "К прошлому году",
 "O'tkazish": "Перевести",
 "O'xshashlik darajasi": "Степень совпадения",
 "O'zbek tili": "Узбекский язык",
 "Obhod jurnali": "Журнал обходов",
 "Obyekt / bino": "Объект / здание",
 "Obyekt bank balansiga qabul qilindi": "Объект принят на баланс банка",
 "Obyekt bank balansiga qabul qilingan": "Принято на баланс банка",
 "Obyekt hayot sikli": "Жизненный цикл объекта",
 "Obyekt hujjatlari": "Документы объекта",
 "Obyekt ma'lumotlari": "Данные объекта",
 "Obyekt nomi": "Наименование объекта",
 "Obyekt turi": "Тип объекта",
 "Obyekt va joylashuv": "Объект и расположение",
 "Obyekt, shartnoma yoki mijoz bo'yicha qidirish...": "Поиск по объекту, договору или клиенту...",
 "Obyekt, xaridor yoki undiruv ishi raqami...": "Объект, покупатель или номер дела о взыскании...",
 "Obyektlar holati": "Статусы объектов",
 "Ochiq": "Открыт",
 "Ochiq servis topshiriqlari": "Открытые сервисные задания",
 "Ochiq trevoga": "Открытых тревог",
 "Ochish": "Открыть",
 "Ofis binosi": "Офисное здание",
 "Oflayn": "Оффлайн",
 "Ogohlantirish": "Предупреждение",
 "Ogohlantirishlar": "Предупреждения",
 "Oldi-sotdi shartnomasi rasmiylashtirildi": "Оформлен договор купли-продажи",
 "Oldingi": "Предыдущая",
 "Oldingi oy": "Предыдущий месяц",
 "Oldingi sahifa": "Предыдущая страница",
 "Ombor": "Склад",
 "Ombor kirish": "Вход на склад",
 "Onlayn": "Онлайн",
 "Onlayn qurilmalar": "Устройства онлайн",
 "Operator ish joyi": "Рабочее место оператора",
 "Operatsion xarajatlar": "Операционные затраты",
 "Oylik": "Ежемесячно",
 "Oylik faoliyat hisoboti": "Ежемесячный отчёт о деятельности",
 "Oylik undiruv": "Взыскание за месяц",
 "Parking kirish": "Въезд на парковку",
 "Parol": "Пароль",
 "Parolni kiriting": "Введите пароль",
 "Parolni ko'rsatish": "Показать пароль",
 "Parolni unutdingizmi?": "Забыли пароль?",
 "Past": "Низкий",
 "Port": "Порт",
 "Portfel baholangan qiymati": "Оценочная стоимость портфеля",
 "Prioritet": "Приоритет",
 "Profil ma'lumotlari": "Данные профиля",
 "Protokol": "Протокол",
 "Qabul qilish": "Принять",
 "Qabul qiluvchilar": "Получатели",
 "Qabuldan auksionda realizatsiya qilishgacha — yagona reyestr, videokuzatuv va undiruv jarayoni bitta tizimda.": "От приёма до реализации на аукционе — единый реестр, видеонаблюдение и процесс взыскания в одной системе.",
 "Qarz / Kapital nisbati": "Отношение долга к капиталу",
 "Qarzdor mijoz": "Клиент-должник",
 "Qarzdor mijozlar": "Клиенты-должники",
 "Qarzdorlar orasidan qidirish": "Поиск среди должников",
 "Qarzdorlar reyestri": "Реестр должников",
 "Qarzdorlik ko'rsatkichlari": "Показатели задолженности",
 "Qarzdorni tanlash": "Выбрать должника",
 "Qavat": "Этаж",
 "Qavatlar soni": "Количество этажей",
 "Qayta urinib ko'rish": "Повторить попытку",
 "Qidirish": "Поиск",
 "Qidirish...": "Поиск...",
 "Qidiruv yoki filtrga mos arxiv yozuvi yo'q.": "Нет архивных записей по запросу или фильтру.",
 "Qishloq xo'jaligi yerlari": "Сельскохозяйственные земли",
 "Qo'llab-quvvatlash": "Техподдержка",
 "Qo'riqlanadigan obyekt": "Объектов под охраной",
 "Qo'riqlash posti": "Пост охраны",
 "Qo'riqlash rejimi": "Режим охраны",
 "Qo'shish": "Добавить",
 "Qoldiq asosiy qarz": "Остаток основного долга",
 "Qoldiq qarz summasi": "Сумма остатка долга",
 "Qurilgan yili": "Год постройки",
 "Qurilish yerlari": "Земли под застройку",
 "Qurilma": "Устройство",
 "Qurilma diagnostikasi": "Диагностика устройства",
 "Qurilma hayot sikli": "Жизненный цикл устройства",
 "Qurilma holati": "Состояние устройства",
 "Qurilma nomi (tizimda ko'rinadi)": "Имя устройства (отображается в системе)",
 "Qurilma turi": "Тип устройства",
 "Qurilma turi va modeli": "Тип и модель устройства",
 "Qurilmalar": "Устройства",
 "Qurilmalar holati": "Состояние устройств",
 "Quvvat manbai": "Источник питания",
 "Rad etish": "Отклонить",
 "Rad etish sababi": "Причина отклонения",
 "Rad qilish": "Отказать",
 "Rasm": "Изображение",
 "Realizatsiya": "Реализация",
 "Realizatsiya arxivi": "Архив реализации",
 "Realizatsiya qilingan aktiv obyektlarining doimiy arxivi": "Постоянный архив реализованных активовых объектов",
 "Realizatsiya sanasi": "Дата реализации",
 "Realizatsiya tushumi (YTD)": "Выручка от реализации (с начала года)",
 "Rejaning 78 foizi bajarildi": "План выполнен на 78 процентов",
 "Reyestr": "Реестр",
 "Reyestr eksporti": "Экспорт реестра",
 "Reyestrda": "В реестре",
 "Rollar bo'yicha ruxsat matritsasi": "Матрица прав по ролям",
 "Rolni almashtirish": "Сменить роль",
 "Rus tili": "Русский язык",
 "Ruxsat berish": "Разрешить доступ",
 "Ruxsat rad etildi · 403": "Доступ запрещён · 403",
 "Ruxsat yetarli emas": "Недостаточно прав",
 "Sababni kiriting...": "Укажите причину...",
 "Sahifa topilmadi": "Страница не найдена",
 "Sana va vaqt": "Дата и время",
 "Sanoat yerlari": "Промышленные земли",
 "Saqlash": "Сохранить",
 "Sarlavha": "Заголовок",
 "Savdo maydoni": "Торговая площадь",
 "Seriya raqami": "Серийный номер",
 "Servis": "Сервис",
 "Servis topshirig'i": "Сервисное задание",
 "Servis topshirig'i va tekshiruv": "Сервисное задание и проверка",
 "Sessiya bosqichlari": "Этапы сессии",
 "Shartnoma": "Договор",
 "Shartnoma raqami": "Номер договора",
 "Shartnoma turi": "Тип договора",
 "Shartnomalar": "Договоры",
 "Shlagbaum": "Шлагбаум",
 "Shoshilinch muddatlar": "Срочные сроки",
 "Shoshilinch undiruv ishlari": "Срочные дела о взыскании",
 "Shu oy realizatsiya qilingan": "Реализовано в этом месяце",
 "Signal sifati": "Качество сигнала",
 "So'nggi 12 oy to'lov intizomi": "Платёжная дисциплина за 12 месяцев",
 "So'nggi 24 soat": "За последние 24 часа",
 "So'nggi hodisalar": "Последние происшествия",
 "So'nggi qabul qilingan obyektlar": "Последние принятые объекты",
 "Sof qoplama (YTD)": "Чистое покрытие (с начала года)",
 "Solishtirma ball": "Сравнительный балл",
 "Sotilgan": "Реализовано",
 "Sotuv narxi": "Цена продажи",
 "Sozlamalar": "Настройки",
 "Sud jarayonida": "В судебном процессе",
 "Sud organi": "Судебный орган",
 "Sud qarori": "Решение суда",
 "Sud qarori qabul qilindi": "Принято решение суда",
 "Sud qarori raqami": "Номер решения суда",
 "Sug'orish tizimi": "Система орошения",
 "Suhbat boshlash": "Начать разговор",
 "Suv ta'minoti": "Водоснабжение",
 "Tahliliy hisobotlar kutubxonasi va eksport": "Библиотека аналитических отчётов и экспорт",
 "Tahrirlash": "Редактировать",
 "Tanlangan ish tafsiloti": "Детали выбранного дела",
 "Tanlangan obyekt": "Выбранный объект",
 "Tanlangan qarzdor tafsiloti": "Детали выбранного должника",
 "Tanlangan qavat": "Выбранный этаж",
 "Tarix": "История",
 "Tarmoq moduli": "Сетевой модуль",
 "Tarmoq va identifikatsiya": "Сеть и идентификация",
 "Tasdiq kutmoqda": "Ожидает подтверждения",
 "Tasdiqlangan": "Подтверждено",
 "Tasdiqlash": "Подтвердить",
 "Tashkilot": "Организация",
 "Tashrif buyuruvchi": "Посетитель",
 "Tashrif buyuruvchini kutmoqda…": "Ожидание посетителя…",
 "Tashrif maqsadi": "Цель визита",
 "Tavsif": "Описание",
 "Taxminiy qiymati (so'm)": "Предварительная стоимость (сум)",
 "Tayyor": "Готово",
 "Tekshirildi": "Проверено",
 "Tekshirilmoqda": "Проверяется",
 "Tekshirish usuli": "Способ проверки",
 "Telefon": "Телефон",
 "Texnik": "Техник",
 "Texnik holat": "Техническое состояние",
 "Texnik pasport": "Технический паспорт",
 "Texnik qavat": "Технический этаж",
 "Texnik ta'minot bo'limi": "Отдел технического обеспечения",
 "Texnik xizmat ish joyi": "Рабочее место техслужбы",
 "Texnik xulosa": "Техническое заключение",
 "Tez eksportlar": "Быстрый экспорт",
 "Tezkor eslatmalar": "Оперативные напоминания",
 "Tijorat obyekti": "Коммерческий объект",
 "Tizim": "Система",
 "Tizim haqida": "О системе",
 "Tizim parametrlari": "Параметры системы",
 "Tizim texnik xizmatda": "Система на техническом обслуживании",
 "Tizimdan chiqish": "Выйти из системы",
 "Tizimga kirish": "Вход в систему",
 "To'liq ekran": "Полный экран",
 "To'lov": "Платёж",
 "To'lov kechikkan": "Платёж просрочен",
 "To'lov tasdiqnomasi biriktirildi": "Приложено подтверждение оплаты",
 "To'xtatilgan": "Приостановлено",
 "Top obyektlar (balans qiymati)": "Топ объектов (балансовая стоимость)",
 "Topshiriq": "Задание",
 "Topshiriq tafsilotlari, obyekt xaritasi va tekshiruv vazifalari": "Детали задания, карта объекта и задачи проверки",
 "Topshirish dalolatnomasi biriktirildi": "Приложен акт передачи",
 "Trevoga navbati": "Очередь тревог",
 "Trevogani qabul qilish": "Принять тревогу",
 "Tugatish": "Завершить",
 "Turar-joy majmuasi": "Жилой комплекс",
 "Uchastka chegarasi": "Граница участка",
 "Uchastka ma'lumotlari": "Данные участка",
 "Ulangan": "Подключено",
 "Ulanish testi va faollashtirish": "Тест подключения и активация",
 "Umumiy": "Общие",
 "Umumiy ma'lumot": "Общие сведения",
 "Umumiy maydon": "Общая площадь",
 "Umumiy maydon (m²)": "Общая площадь (м²)",
 "Umumiy qiymat": "Общая стоимость",
 "Undirilayotgan summa": "Взыскиваемая сумма",
 "Undirilgan mablag' (YTD)": "Взыскано (с начала года)",
 "Undirilgan mablag' (oy)": "Взыскано за месяц",
 "Undiruv": "Взыскание",
 "Undiruv bosqichlari": "Этапы взыскания",
 "Undiruv ishi": "Дело о взыскании",
 "Undiruv ishini ochish": "Открыть дело о взыскании",
 "Undiruv ishlari": "Дела о взыскании",
 "Undiruv ishlariga o'tish": "Перейти к делам о взыскании",
 "Undiruv jarayoni bosqichlari": "Этапы процесса взыскания",
 "Undiruv jarayoni: da'vodan sud ijrosigacha": "Процесс взыскания: от иска до исполнения исполнения",
 "Undiruv ko'rsatkichlari": "Показатели взыскания",
 "Undiruv to'lovlari": "Платежи по взысканию",
 "Undiruv va sud ishlari": "Взыскание и судебные дела",
 "Undiruvda": "На взыскании",
 "Ushbu bosqichda ochiq ish yo'q.": "На этом этапе нет открытых дел.",
 "Uzilgan": "Обрыв",
 "Uzoqlashtirish": "Отдалить",
 "Vaqt": "Время",
 "Vazifalar": "Задачи",
 "Vazifalar va tasdiqlar": "Задачи и согласования",
 "Videokuzatuv nuqtasi": "Точек видеонаблюдения",
 "Videokuzatuv posti va trevoga navbati": "Пост видеонаблюдения и очередь тревог",
 "Videostena": "Видеостена",
 "Voqea turi": "Тип события",
 "Xaridor": "Покупатель",
 "Xarita": "Карта",
 "Xarita va geolokatsiya": "Карта и геолокация",
 "Xatolik va ogohlantirish ekranlari": "Экраны ошибок и предупреждений",
 "Xavfsizlik": "Безопасность",
 "Xavfsizlik nazorati": "Контроль безопасности",
 "Xavfsizlik rejasi": "План безопасности",
 "Xavfsizlik rejasi va texnik topshiriq": "План безопасности и техническое задание",
 "Xavfsizlik tizimi": "Система безопасности",
 "Xavfsizlik topshirig'i": "Задание по безопасности",
 "Xavfsizlik xizmati · Nazorat markazi": "Служба безопасности · Центр контроля",
 "Xizmat amallari": "Сервисные действия",
 "Xodimni tanlang": "Выберите сотрудника",
 "Xona": "Помещение",
 "Xona / zona": "Помещение / зона",
 "Xonalar": "Помещения",
 "Xonalar ro'yxati": "Список помещений",
 "Xonalar va qavatlar": "Помещения и этажи",
 "Xususiy uy va dala hovli": "Частный дом и дача",
 "Yagona aktivlar reyestri va obyekt kartochkalari": "Единый реестр активов и карточки объектов",
 "Yakuniy narx": "Итоговая цена",
 "Yakuniy tasdiqlash": "Финальное подтверждение",
 "Yakunlandi": "Завершено",
 "Yangi": "Новый",
 "Yangi hodisa ochish": "Открыть новое происшествие",
 "Yangi hodisalar": "Новые происшествия",
 "Yangi jadval qo'shish": "Добавить расписание",
 "Yangi qurilma o'rnatish": "Установка нового устройства",
 "Yangi rol": "Новая роль",
 "Yangi so'rov": "Новый запрос",
 "Yangi undiruv ishi": "Новое дело о взыскании",
 "Yaqinlashtirish": "Приблизить",
 "Yaratgan": "Автор",
 "Yaratilgan": "Создано",
 "Yaratish": "Создать",
 "Yer uchastkalari": "Земельные участки",
 "Yer uchastkasi": "Земельный участок",
 "Yon eshikni ochish": "Открыть боковую дверь",
 "Yon kirish": "Боковой вход",
 "Yong'in detektori": "Пожарный извещатель",
 "Yong'in signali – kritik": "Пожарный сигнал — критично",
 "Yong'in signalizatsiyasi": "Пожарная сигнализация",
 "Yong'in xavfsizligi": "Пожарная безопасность",
 "Yopildi": "Закрыто",
 "Yopilgan": "Закрыт",
 "Yopiq": "Закрыт",
 "Yopish": "Закрыть",
 "Yozma ogohlantirish yuborildi": "Направлено письменное предупреждение",
 "Yozuv topilmadi": "Записи не найдены",
 "Yuklab olish": "Скачать",
 "Yuklangan hujjatlar": "Загруженные документы",
 "Yuklash uchun bosing": "Нажмите для загрузки",
 "Yuqori": "Высокий",
 "Yuridik shaxs": "Юридическое лицо",
 "Yuz mos keldi": "Лицо распознано",
 "Yuz mos kelmadi": "Лицо не распознано",
 "Zaxira generator": "Резервный генератор",
 "Zaxira quvvat": "Резервное питание",
 "Zaxira quvvat (UPS)": "Резервное питание (ИБП)",
 "Zaxira yerlar": "Резервные земли",
 "gektar": "га",
 "kun": "дней",
 "kun qoldi": "дней осталось",
 "mln so'm": "млн сум",
 "mlrd so'm": "млрд сум",
 "portfelda": "в портфеле",
 "so'm": "сум",
 "ta ish": "дел",
 "ta obyekt": "объектов",
 "trln so'm": "трлн сум",
 "uchastka": "участков"
};
