/* Ma'ruzachi izohlari: har slaydda nima deyiladi.
   Kalit - slayd id, uz va ru - og'zaki matn (slayd matnini takrorlamaydi). */
window.MKB_IZOH = {
  "s-muqova": {
    uz: "Bank balansida 267 ta obyekt turibdi. Ularning ko'pida elektr ham, internet ham, qorovul ham yo'q, lekin mulk uchun javobgarlik bizda. Bugun shu obyektlarni masofadan qanday ko'rib turishni ko'rsataman. O'nta yechimni solishtirdik, har birining ishlash sxemasi va narxi bor. Hammasi bitta MKB platformasiga ulanadi: kamera qaysi brend bo'lmasin, operator bitta ekranga qaraydi. Taqdimot oxirida sizdan to'rtta qaror so'rayman: pilot obyektlar, byudjet oralig'i, integrator modeli va ulanish standarti. Avval taqdimot tuzilishini ko'rsatay.",
    ru: "На балансе банка 267 объектов. На многих нет ни света, ни интернета, ни охраны, а ответственность за имущество остаётся на нас. Сегодня покажу, как видеть эти объекты удалённо. Мы сравнили десять решений, по каждому есть схема работы и цена. Все они подключаются к одной платформе MKB: какой бы ни была марка камеры, оператор смотрит в один экран. В конце попрошу вас утвердить четыре пункта: пилотные объекты, диапазон бюджета, модель интегратора и стандарт подключения. Сначала коротко о структуре."
  },
  "s-mundarija": {
    uz: "Taqdimot yetti bobdan iborat. Muammodan boshlaymiz, keyin o'nta yechim va narx, platforma, montaj, moliya va huquq, sotuv va oxirida joriy etish rejasi keladi. Hamma slaydni birdek ko'rish shart emas. Rahbariyat, moliya va huquq, jamoa rahbarlari, montajchi va marketing uchun alohida o'qish yo'li bor, har biri olti-yetti slayd. Chuqurroq ma'lumot kartochkalar ortida turadi: savol tug'ilsa, ochib ko'rsataman. Endi asosiy savolga o'tamiz: bu obyektlarda aslida nima yo'q?",
    ru: "В презентации семь разделов. Начнём с проблемы, потом десять решений и цены, платформа, монтаж, финансы и право, продажи и в конце план внедрения. Смотреть всё подряд не обязательно. Для правления, финансов и юристов, тимлидов, монтажников и маркетинга есть свои маршруты, по шесть-семь слайдов. Подробности спрятаны за карточками: если возникнет вопрос, открою. Переходим к главному: чего на этих объектах на самом деле нет."
  },
  "s-muammo": {
    uz: "Bank mulkni qabul qilganda hisoblagichlar nolga tushirilgan bo'ladi. Elektr shartnomasi bekor, internet o'chirilgan, qorovul yo'q. Keyingi ko'rikkacha obyektga hech kim bormaydi. Lekin mulk, yong'in xavfsizligi va sug'urta bo'yicha javobgarlik bank zimmasida qoladi. Qisqasi, biz javob beramiz, ammo ko'rmaymiz. Shuning uchun bitta qoidani qat'iy qo'ydik: bo'sh yer uchastkasidan tashqari har bir obyektda kamera bo'ladi. Endi savol shu: bu 267 obyekt qanday obyektlar? Ular bir xil emas, buni keyingi slayd ko'rsatadi.",
    ru: "Банк принимает имущество с обнулёнными счётчиками. Договор на электричество расторгнут, интернет отключён, охраны нет. До следующего осмотра туда никто не приезжает. При этом ответственность за имущество, пожарную безопасность и страховку остаётся на банке. Проще говоря, мы отвечаем, но не видим. Поэтому правило жёсткое: камера стоит на каждом объекте, кроме пустых земельных участков. Теперь вопрос: что это за 267 объектов? Они очень разные, и следующий слайд это показывает."
  },
  "s-tarkib": {
    uz: "267 obyektning 188 tasi bino va inshoot, 79 tasi ko'char mulk: avtotransport, texnika, asbob-uskuna. Ya'ni har uchinchi obyekt bino emas. Mashinaga kamera osib qo'yib bo'lmaydi, unga plomba va GPS kerak. Binolar orasida ham farq katta: ma'muriy bino, ferma, sex, ko'p qavatli uydagi xonadon. Shuning uchun bitta universal komplektni sotib olib, hamma joyga qo'yish ishlamaydi, u ro'yxatning yarmiga ham mos kelmaydi. Jihoz tanlashdan oldin esa oltita xatarni hal qilish kerak, ularga o'taman.",
    ru: "Из 267 объектов 188 — это здания и сооружения, а 79 — движимое имущество: автотранспорт, техника, оборудование. То есть каждый третий объект вообще не здание. На машину камеру не повесишь, там нужны пломба и GPS. Среди зданий разброс тоже большой: административные здания, фермы, цеха, квартиры в многоэтажках. Поэтому купить один универсальный комплект и поставить везде не получится, он не подойдёт даже половине списка. А до выбора оборудования нужно закрыть шесть рисков, о них дальше."
  },
  "s-xatar": {
    uz: "Bu oltita xatarning har biri loyihani to'xtata oladi, shuning uchun ularni jihozdan oldin hal qildik. Eng og'iri ikkitasi. Birinchisi qish: dekabrda quyosh iyundagidan 4,7 marta kam, LiFePO4 akkumulyatorni 0 °C dan past zaryadlash uni buzadi. Ikkinchisi Markaziy bank nizomi: bir yilda sotilmagan mulk 100% zaxira talab qiladi. Rahbariyat odatda so'raydi: xususiy qo'riqlash firmasini yollasak-chi? Bo'lmaydi, O'RQ-778 bo'yicha bu huquq faqat davlatda, hamkorimiz IIV Qo'riqlash departamenti. Jihoz qaysi shartlar bo'yicha tanlanadi?",
    ru: "Каждый из этих шести рисков способен остановить проект, поэтому мы закрыли их до выбора оборудования. Самых тяжёлых два. Первый — зима: в декабре солнца в 4,7 раза меньше, чем в июне, а зарядка LiFePO4 на морозе губит аккумулятор. Второй — положение ЦБ: имущество, не проданное за год, требует резерва в 100%. Правление обычно спрашивает: а если нанять частную охрану? Нельзя, по ЗРУ-778 охрану по договору оказывает только государство, наш партнёр Департамент охраны при МВД. По каким условиям выбираем оборудование?"
  },
  "s-shart": {
    uz: "Yechimni biz ofisda o'ylab topmaymiz, uni obyektning o'zi belgilaydi. Montajchi har obyekt bo'yicha oltita savolga javob yozadi: quvvat qayerdan, kamera qayerga, eshik qanday ochiladi, aloqa qanday, aloqa uzilsa nima bo'ladi va platformaga qaysi protokol bilan ulanadi. Shu olti javob o'nta yechimdan bittasini ko'rsatadi. Beshinchi shartga e'tibor bering: aloqa uzilganda ham hodisa joyida yoziladi va keyin markazga yetadi. Dalil yo'qolmaydi. Endi o'nta yechimning o'zini ko'rsataman.",
    ru: "Решение не придумывается в офисе, его диктует сам объект. Монтажник по каждому объекту отвечает на шесть вопросов: откуда питание, куда ставить камеру, как открывается дверь, какая связь, что будет при обрыве связи и по какому протоколу подключаемся к платформе. Эти шесть ответов указывают на одно из десяти решений. Обратите внимание на пятое условие: даже без связи событие пишется на месте и потом доходит до центра. Доказательства не теряются. Теперь сами десять решений."
  },
  "s-matritsa": {
    uz: "Mana o'nta yechim bitta ekranda. Ular quvvat va aloqaga qarab tartiblangan: batareyali kamera va quyosh-4G'dan boshlab yoqilg'i elementi va mobil minoragacha. Eng arzoni LoRaWAN datchiklari, obyektga 3 mln so'mdan. Eng qimmati EFOY, 170 mln gacha, u faqat chekkadagi qimmat aktiv uchun. O'nta yechimdan yettitasi obyektga 20 mln so'mgacha turadi. Istalgan kartani bossam, sxemasi, ulanishi va narxi ochiladi. Endi har bir yechimni qisqa ko'rib chiqamiz, birinchisidan boshlaymiz.",
    ru: "Вот все десять решений на одном экране. Они упорядочены по питанию и связи: от камеры на батарее и солнечной 4G-камеры до топливного элемента и мобильной вышки. Самое дешёвое — датчики LoRaWAN, от 3 млн сумов на объект. Самое дорогое — EFOY, до 170 млн, оно только для удалённого дорогого актива. Семь решений из десяти укладываются в 20 млн на объект. По клику на карточку открываются схема, подключение и цена. Пройдёмся по каждому коротко, начнём с первого."
  },
  "s-y01": {
    uz: "Birinchi yechim uy, kichik ofis va do'kon uchun. Kabel tortilmaydi: ikki-to'rtta batareyali kamera va video domofon bir kunda o'rnatiladi. Narxi obyektga 8 mln dan 12 mln so'mgacha, o'rnatish bilan. Bir cheklovni ochiq aytaman: Home Hub jonli oqimni 3-5 daqiqa bilan cheklaydi, shuning uchun bu yerda nazorat hodisaga asoslanadi, doimiy video emas. Qattiq qishda kamera bino ichiga qo'yiladi. Elektr ham, bino ham bo'lmagan hovli yoki omborga keyingi yechim mos keladi.",
    ru: "Первое решение — для дома, небольшого офиса и магазина. Кабель не тянем: две-четыре камеры на батарее и видеодомофон ставятся за один день. Цена от 8 до 12 млн сумов на объект с монтажом. Честно скажу об ограничении: Home Hub режет живой поток до 3-5 минут, поэтому здесь контроль строится на событиях, а не на круглосуточном видео. В сильный мороз камеру ставим внутри здания. Для двора или склада, где нет ни света, ни помещения, подходит следующее решение."
  },
  "s-y02": {
    uz: "Ikkinchi yechim elektr ham, kabel ham yo'q ombor va hovli uchun. Hikvision kamerasida quyosh paneli, akkumulyator va SIM-karta bitta komplektda. Obyektga 5-9 mln so'm, komplektning o'zi 3,8-5,2 mln. Asosiy e'tibor qishga: dekabrda quyosh 4,7 marta kam, ixcham model esa faqat 0 °C gacha ishlaydi. Shuning uchun ochiq joyga −20 °C sinfidagi komplekt olamiz. Yetkazuvchilar mahalliy, uchta kompaniya bor. Tenderda narxni tushirish uchun bizga ikkinchi brend kerak, u keyingi slaydda.",
    ru: "Второе решение для склада и двора, где нет ни электричества, ни кабеля. У камеры Hikvision солнечная панель, аккумулятор и SIM-карта в одном комплекте. На объект 5-9 млн сумов, сам комплект 3,8-5,2 млн. Главное здесь зима: в декабре солнца в 4,7 раза меньше, а компактная модель работает только до нуля. Поэтому на открытое место берём комплект класса −20 °C. Поставщики местные, их три. Чтобы на тендере сбить цену, нужен второй бренд, он на следующем слайде."
  },
  "s-y03": {
    uz: "Uchinchi yechim Dahua, Hikvision'ga muqobil. Uni ikki sababga ko'ra kiritdik. Birinchisi raqobat: tenderda ikki brend bo'lsa, narx pasayadi. Ikkinchisi aylanuvchi kamera: katta hudud va perimetrni bitta ustundan ko'radi. Narxi obyektga 7-12 mln so'm. Aloqa uzilsa, kamera SD kartaga yozadi va aloqa tiklangach kliplarni markazga yuboradi. Ogohlantirish bor: ayrim komplektlar akkumulyatori faqat 0 °C dan yuqorida zaryadlanadi, shuning uchun tenderda −20 °C sertifikatini talab qilamiz. Quyosh panelini qo'yib bo'lmasa-chi? Buning yechimi keyingi slaydda.",
    ru: "Третье решение — Dahua, альтернатива Hikvision. Мы включили его по двум причинам. Первая — конкуренция: когда на тендере два бренда, цена падает. Вторая — поворотная камера: она видит большую территорию и периметр с одной опоры. Цена 7-12 млн сумов на объект. При обрыве связи камера пишет на SD-карту и после восстановления отправляет клипы в центр. Есть оговорка: некоторые комплекты заряжаются только выше нуля, поэтому на тендере требуем сертификат на −20 °C. А если панель поставить нельзя? Ответ на следующем слайде."
  },
  "s-y04": {
    uz: "To'rtinchi yechim panel qo'yib bo'lmaydigan obyekt uchun. Oddiy korporativ kameralar almashtiriladigan LiFePO4 shkafidan ishlaydi, servis esa zaryadlangan blokni jadval bo'yicha olib keladi. 30 Vt iste'molda 5 kVt·soatlik shkaf taxminan 6 kun yetadi. Narxi 12-20 mln so'm. Asosiy afzalligi: bitta brendga bog'lanib qolmaymiz, istalgan qismni boshqasiga almashtirsa bo'ladi. Blokni qachon almashtirishni esa taxmin qilmaymiz, zaryad foizini BMS o'zi platformaga yuboradi. Kamerasiz, faqat datchik bilan ishlaydigan yechimga o'tamiz.",
    ru: "Четвёртое решение для объекта, где панель поставить нельзя. Обычные корпоративные камеры питаются от шкафа со сменными блоками LiFePO4, а сервис по графику привозит заряженный блок. При потреблении 30 Вт шкафа на 5 кВт·ч хватает примерно на 6 дней. Цена 12-20 млн сумов. Главный плюс: мы не привязаны к одному бренду, любую часть можно заменить. Когда менять блок, не гадаем, BMS сама передаёт процент заряда в платформу. Дальше решение, где основную работу делают датчики."
  },
  "s-y05": {
    uz: "Beshinchi yechim ofis va qimmat obyekt uchun. Bu yerda asosiy ishni datchiklar qiladi: eshik, harakat, tutun va is gazi. Buzib kirish yoki yong'in haqida xabar birinchi daqiqada keladi, kamera faqat tasdiqlash uchun kerak. Datchiklar o'z batareyasida yillab ishlaydi. Narxi 7-10 mln so'm, hubning o'zi 3,3 mln. Elektr yo'q bo'lsa, yong'in talabi saqlanadimi? Ha, elektr uzilishi javobgarlikni bekor qilmaydi, talab VMQ-649 ning 9-ilovasi bo'yicha aniqlanadi. Keyingi yechim katta omborlar uchun.",
    ru: "Пятое решение для офиса и дорогого объекта. Основную работу здесь делают датчики: дверь, движение, дым и угарный газ. Сообщение о проникновении или пожаре приходит в первую же минуту, камера нужна только для подтверждения. Датчики годами работают на своих батарейках. Цена 7-10 млн сумов, сам хаб 3,3 млн. Если света нет, требование по пожарной безопасности остаётся? Да, отключение электричества ответственность не снимает, требование определяется по приложению 9 к ПКМ-649. Следующее решение — для больших складов."
  },
  "s-y06": {
    uz: "Oltinchi yechim katta ombor va texnik xona uchun, va u eng arzoni: obyektga 3-8 mln so'm. Datchiklar doim ishlaydi, video esa faqat hodisa bo'lganda ochiladi, shuning uchun trafik ham, quvvat ham eng kam sarflanadi. Datchik batareyasi 5 yilgacha yetadi, ya'ni servisga deyarli bormaymiz. Bitta shart bor: shlyuz elektr bor qo'shni nuqtada turadi va bir necha obyektga xizmat qiladi. LoRaWAN chastotasi ruxsat bilan ishlatiladi. Endi aktiv bor-yo'g'i bir necha kun turadigan holatni ko'ramiz.",
    ru: "Шестое решение для большого склада и технического помещения, и оно самое дешёвое: 3-8 млн сумов на объект. Датчики работают постоянно, а видео включается только при событии, поэтому и трафик, и энергия расходуются минимально. Батареи датчиков хватает до 5 лет, то есть на сервис почти не ездим. Одно условие: шлюз стоит в соседней точке, где есть свет, и обслуживает несколько объектов. Частота LoRaWAN используется по разрешению. Теперь случай, когда актив стоит всего несколько дней."
  },
  "s-y07": {
    uz: "Yettinchi yechim qisqa muddatli aktiv uchun: sud yoki ijro jarayonida, sotuvgacha bir-ikki hafta qolganda. Panel qo'yishga vaqt ham, ruxsat ham yo'q. Ko'chma stansiya olib boriladi va nazorat o'sha kuniyoq boshlanadi. Bo'shagan stansiya bazada zaryadlanadi, o'rniga to'lasi qo'yiladi. Narxi 7-16 mln so'm, lekin stansiya bir obyektda qolmaydi, keyingisiga ko'chadi. Moliya uchun bu muhim: xarajat bir obyektga emas, bir necha obyektga bo'linadi. Endi teskari holat, chekkadagi va qimmat obyekt.",
    ru: "Седьмое решение для краткосрочного актива: судебный процесс, исполнительное производство или неделя-две до продажи. Ставить панель нет ни времени, ни разрешения. Привозим портативную станцию, и контроль начинается в тот же день. Разряженную станцию заряжаем на базе, вместо неё ставим полную. Цена 7-16 млн сумов, но станция на объекте не остаётся, она переезжает на следующий. Для финансов это важно: затраты делятся не на один объект, а на несколько. Теперь обратный случай, удалённый и дорогой объект."
  },
  "s-y08": {
    uz: "Sakkizinchi yechim eng qimmati: obyektga 80 mln dan 170 mln so'mgacha. Uni hamma joyga emas, faqat chekkadagi qimmat aktivga taklif qilamiz. EFOY quyoshga bog'liq emas: akkumulyator zaryadi tushganda metanol kartriji o'zi yoqiladi va oylab zaryadlab turadi. Servisga kam boriladi, dekabr ham qo'rqinchli emas. Bu narx o'zini oqlaydimi? Faqat aktivning o'zi qimmat bo'lsa. Metanolni tashish va saqlash tartibini shartnomadan oldin kelishamiz. Katta ochiq maydon uchun keyingi yechim bor.",
    ru: "Восьмое решение самое дорогое: от 80 до 170 млн сумов на объект. Мы предлагаем его не везде, а только для удалённого дорогого актива. EFOY не зависит от солнца: когда заряд аккумулятора падает, метанольный картридж включается сам и месяцами поддерживает заряд. На сервис ездим редко, декабрь не страшен. Окупается ли такая цена? Только если сам актив дорогой. Порядок перевозки и хранения метанола согласуем до договора. Для большой открытой площадки есть следующее решение."
  },
  "s-y09": {
    uz: "To'qqizinchi yechim mobil kuzatuv minorasi: qurilish, katta hovli, ishlab chiqarish maydoni. Tirkama keltiriladi va katta hududni bir kunda qamrab oladi. Narxi 40-120 mln so'm. Lekin moliya nuqtai nazaridan asosiy gap boshqa: obyekt bir yilda sotilishi kerak, minora esa yillab ishlaydi. Shuning uchun uni sotib olib bir joyga qo'ymaymiz. Ijaraga olamiz yoki obyektdan obyektga ko'chiramiz, bu arzonroq. Oxirgi yechim bir-biriga yaqin joylashgan obyektlar uchun.",
    ru: "Девятое решение — мобильная вышка наблюдения: стройка, большой двор, производственная площадка. Привозим прицеп, и большая территория закрыта за день. Цена 40-120 млн сумов. Но с точки зрения финансов главное в другом: объект нужно продать за год, а вышка служит годами. Поэтому покупать её под один объект мы не будем. Берём в аренду или перевозим с объекта на объект, так дешевле. Последнее решение — для объектов, которые стоят рядом друг с другом."
  },
  "s-y10": {
    uz: "O'ninchi yechim klaster shkafi. Bir hududda uchtadan o'ntagacha ombor yoki sex bo'lsa, har biriga alohida router va NVR qo'ymaymiz. Hammasi bitta shkafga ulanadi: yaqinlari kabel bilan, uzoqdagisi radio ko'prik orqali. Narxi 20-40 mln so'm, lekin bu bitta obyektga emas, butun klasterga. Servis ham bitta nuqtada. Jamoa rahbarlari uchun muhim tafsilot: har qurilma o'z device_id sini saqlaydi, platformada har obyekt alohida ko'rinadi. Endi o'nta yechimni narx bo'yicha yonma-yon qo'yamiz.",
    ru: "Десятое решение — кластерный шкаф. Если в одном районе от трёх до десяти складов или цехов, отдельный роутер и NVR на каждый не ставим. Всё подключается к одному шкафу: ближние кабелем, дальние через радиомост. Цена 20-40 млн сумов, но это на весь кластер, а не на один объект. Сервис тоже в одной точке. Деталь для тимлидов: каждое устройство сохраняет свой device_id, и в платформе каждый объект виден отдельно. Теперь поставим десять решений рядом по цене."
  },
  "s-narx": {
    uz: "Asosiy xulosa shu: o'nta yechimdan yettitasi obyektga 20 mln so'mgacha, jihoz va o'rnatish bilan. Qimmat uchtasi, ya'ni klaster, minora va EFOY, alohida holatlar uchun va ular ko'pincha bir nechta obyektga bo'linadi. Bu narxlar qanchalik aniq? Bu bugungi bozor narxlari. Yakuniy narxni tenderda kamida uchta tijorat taklifi belgilaydi. Endi texnik qismga o'tamiz: shuncha xil brend bitta platformada qanday birlashadi?",
    ru: "Главный вывод: семь решений из десяти стоят до 20 млн сумов на объект вместе с оборудованием и монтажом. Три дорогих, то есть кластер, вышка и EFOY, нужны для особых случаев и чаще всего делятся на несколько объектов. Насколько точны эти цифры? Это текущие рыночные цены. Окончательную цену на тендере определят минимум три коммерческих предложения. Переходим к технической части: как столько разных брендов собираются в одной платформе?"
  },
  "s-arx": {
    uz: "Bu slayddagi asosiy fikr: interfeys hech qachon kameraga to'g'ridan-to'g'ri ulanmaydi. Obyektdagi qurilma mahalliy tugunga, u yopiq kanal orqali MKB yadrosiga, yadro esa veb-panel va mobil ilovaga ulanadi. Ochiq internet yo'q, faqat VPN yoki yopiq APN. Brend farqini adapter yo'qotadi. Shuning uchun ertaga yangi brend qo'shilsa, veb-panelni qayta yozmaymiz. Jamoa rahbari so'raydi: yuklama qayerda? Video faqat operator obyektni ochganda oqadi, qolgani yengil hodisa va telemetriya. Endi eng ko'p beriladigan savolga javob beraman.",
    ru: "Главная мысль слайда: интерфейс никогда не подключается к камере напрямую. Устройство на объекте подключается к локальному узлу, оттуда по закрытому каналу в ядро MKB, а ядро отдаёт данные в веб-панель и мобильное приложение. Открытого интернета нет, только VPN или закрытый APN. Разницу между брендами снимает адаптер. Поэтому если завтра появится новый бренд, веб-панель переписывать не придётся. Тимлид спросит: где нагрузка? Видео идёт, только когда оператор открыл объект, остальное — лёгкие события и телеметрия. Теперь отвечу на самый частый вопрос."
  },
  "s-savol": {
    uz: "Eng ko'p so'raladigan savol: yuzta simsiz kamerani bitta ekranda qanday ko'ramiz? Javob: yuzta jonli video emas, yuzta obyekt kartochkasi. Oxirgi kadr, batareya, signal va oxirgi hodisa. Video operator obyektni ochganda yoqiladi. Sababi fizikada: 4G kamera kutish rejimida 80 mVt sarflaydi, ishlaganda 7 Vt gacha. Batareya doimiy videoga yetmaydi. Shuning uchun biz brendni emas, mezonni tanlaymiz: ochiq API, joyida yozuv va −20 °C da ishlash. Bu kartochkalarni nima to'ldiradi? API shartnomasi.",
    ru: "Самый частый вопрос: как увидеть сто беспроводных камер на одном экране? Ответ: не сто живых видео, а сто карточек объектов. Последний кадр, батарея, сигнал и последнее событие. Видео включается, когда оператор открывает объект. Причина в физике: 4G-камера в режиме ожидания тратит 80 мВт, а в работе до 7 Вт. Батареи на постоянное видео не хватит. Поэтому мы выбираем не бренд, а критерии: открытый API, запись на месте и работа при −20 °C. Что наполняет эти карточки? API-контракт."
  },
  "s-api": {
    uz: "Bu slayd jamoa rahbarlari uchun. Qoida bitta: avval shartnoma yoziladi, keyin kod. Adapter ham, veb-panel ham faqat /api/v1 bilan gaplashadi. Hodisa sxemasida brendga xos maydon yo'q, vaqt faqat UTC, klipning SHA-256 xeshi esa dalil sifatida saqlanadi. Tashqi tizimlarga webhook HMAC imzosi bilan boradi. Kutiladigan savol: buyruq ikki marta ketsa, eshik ikki marta ochiladimi? Yo'q, har buyruqda Idempotency-Key majburiy, takror rad etiladi. Keyingi savol: har brend shu sxemaga qanday keladi?",
    ru: "Этот слайд для тимлидов. Правило одно: сначала пишется контракт, потом код. И адаптер, и веб-панель работают только через /api/v1. В схеме события нет полей, привязанных к бренду, время только в UTC, а хеш клипа SHA-256 сохраняется как доказательство. Во внешние системы вебхуки уходят с подписью HMAC. Ожидаемый вопрос: если команда уйдёт дважды, дверь откроется дважды? Нет, у каждой команды обязательный Idempotency-Key, повтор отклоняется. Следующий вопрос: как каждый бренд приводится к этой схеме?"
  },
  "s-adapter": {
    uz: "Adapter brend protokolini yagona sxemaga o'giradi, platformaning qolgan qismi brendni umuman bilmaydi. Shuning uchun yangi brend 1-4 haftada ulanadi: Milesight bir-ikki haftada, Hikvision va Dahua uch-to'rt haftada. Deyarli hammasi bulutsiz ishlaydi, faqat Ajax buyruqlari qisman bulut orqali o'tadi. Adapterni qabul qilish sharti qat'iy: shartnoma testlari, yozib olingan hodisalar va pilotda bir hafta xatosiz ishlash. Jamoa rahbari so'raydi: bitta hodisa ikki marta kelsa? Adapter kalit va 10 daqiqalik oyna bilan takrorni tashlaydi. Videoning yo'li alohida.",
    ru: "Адаптер переводит протокол бренда в единую схему, и остальная платформа о бренде вообще ничего не знает. Поэтому новый бренд подключается за 1-4 недели: Milesight за одну-две, Hikvision и Dahua за три-четыре. Почти всё работает без облака, только команды Ajax частично идут через облако. Условие приёмки адаптера жёсткое: контрактные тесты, записанные события и неделя работы без ошибок на пилоте. Тимлид спросит: а если событие придёт дважды? Адаптер отбрасывает дубли по ключу в окне 10 минут. У видео свой маршрут."
  },
  "s-video": {
    uz: "Video markazga faqat so'ralganda boradi. Operator obyektni ochadi, shlyuz kameraga ulanadi, oyna yopilsa oqim to'xtaydi. Uchta rejimni solishtiring. Faqat hodisa: kameraga oyiga 0,8 GB, eng kichik SIM paket yetadi. Doimiy video: oyiga 166 GB, quyosh-4G kamera bunga chidamaydi. Biz o'rtadagisini tavsiya qilamiz, kuniga 30 daqiqa jonli video bilan oyiga 4,3 GB. Dalil uchun muhim: har klipning xeshi yoziladi, fayl o'zgartirilsa tekshiruvdan o'tmaydi. Bu 100 obyektda ishlaydi, 1 000 da nima bo'ladi? Keyingi slayd.",
    ru: "Видео уходит в центр только по запросу. Оператор открывает объект, шлюз подключается к камере, окно закрыли, поток остановился. Сравните три режима. Только события: 0,8 ГБ в месяц на камеру, хватает самого маленького SIM-пакета. Круглосуточное видео: 166 ГБ в месяц, солнечная 4G-камера такого не выдержит. Мы рекомендуем средний вариант: полчаса живого видео в день, 4,3 ГБ в месяц. Для доказательной базы важно: у каждого клипа пишется хеш, изменённый файл проверку не пройдёт. Это работает на 100 объектах, а что на 1 000? Следующий слайд."
  },
  "s-masshtab": {
    uz: "Qisqa javob: 1 000 obyektda ham arxitektura o'zgarmaydi, eng tez disk o'sadi. Bizning 267 obyekt 300 obyektlik ustunga sig'adi: 1 200 qurilma, 6 ta virtual mashina, kadr va kliplar uchun 90 kunda taxminan 1 TB. Eng tez o'sadigan narsa aynan shu arxiv, u bank ichidagi MinIO'da turadi. Kirish bank AD orqali, alohida parol yo'q. RabbitMQ yoki Kafka? Bank standartiga qarab tanlaymiz, ikkalasi ham uzilishda navbatni saqlaydi. Endi platformadan eshikka o'tamiz: kirish nazorati.",
    ru: "Короткий ответ: и на 1 000 объектах архитектура не меняется, быстрее всего растёт диск. Наши 267 объектов укладываются в колонку на 300: 1 200 устройств, 6 виртуальных машин, около 1 ТБ под кадры и клипы за 90 дней. Быстрее всего растёт именно архив, он хранится в MinIO внутри банка. Вход через AD банка, отдельных паролей нет. RabbitMQ или Kafka? Выберем по стандарту банка, оба сохраняют очередь при обрыве. Теперь от платформы к двери: контроль доступа."
  },
  "s-kirish": {
    uz: "Ko'pchilik domofon eshikni o'zi ochadi deb o'ylaydi. Ochmaydi. Unga elektr qulf va kirish kontrolleri kerak. Jarayon beshta qadam: qo'ng'iroq, operator videoni va obyekt kartochkasini ko'radi, qaror qiladi, rele qulfni ochadi va kadr, vaqt, operator ismi jurnalga tushadi. Bitta nozik joy bor: tok uzilganda evakuatsiya eshigi ochilishi, server va kassa xonasi esa yopiq qolishi kerak. Shuning uchun qulflar har xil tanlanadi. Aloqa uzilsa nima bo'ladi? Shu haqda keyingi slayd.",
    ru: "Многие думают, что домофон сам открывает дверь. Не открывает. Нужны электрозамок и контроллер доступа. Процесс в пять шагов: звонок, оператор видит видео и карточку объекта, принимает решение, реле открывает замок, а кадр, время и имя оператора ложатся в журнал. Есть тонкий момент: при отключении тока эвакуационная дверь должна открыться, а серверная и касса остаться закрытыми. Поэтому замки подбираются разные. А что будет, если пропала связь? Об этом следующий слайд."
  },
  "s-uzilish": {
    uz: "Internet uzilsa ham nazorat to'xtamaydi, chunki dalil obyektning o'zida yoziladi: SD karta, NVR yoki Home Hub'da. Aloqa tiklanganda hodisalar va kerakli kliplar markazga yetib boradi. Routerda ikkita SIM bor, biri uzilsa ikkinchisiga o'tadi. Platforma batareya, xotira, signal va oxirgi aloqa vaqtini kuzatadi va muammoni biz obyektga borishimizdan oldin ko'rsatadi. Xavfsizlik bo'limi uchun: zavod paroli yo'q, hamma kanal TLS va VPN ichida, har amal jurnalda. Endi montajchi tomonga o'tamiz, hammasi joyida ko'rikdan boshlanadi.",
    ru: "Контроль не останавливается даже без интернета, потому что доказательства пишутся на самом объекте: на SD-карту, в NVR или Home Hub. Когда связь восстанавливается, события и нужные клипы доходят до центра. В роутере две SIM-карты, если одна пропала, он переключается на вторую. Платформа следит за батареей, памятью, сигналом и временем последней связи и показывает проблему раньше, чем мы туда поедем. Для службы безопасности: заводских паролей нет, все каналы внутри TLS и VPN, каждое действие в журнале. Теперь к монтажу, и всё начинается с обследования на месте."
  },
  "s-korik": {
    uz: "Bu slayd montajchilar uchun. Obyektga birinchi marta jihoz bilan emas, o'lchov asboblari bilan boriladi. Bir soatlik ko'rik yechimni tanlab beradi. Eng muhimi aloqa: to'rtta operator o'lchanadi, eng kuchlisining SIM-kartasi qo'yiladi. Masalan, −84 dBm a'lo, −115 dan past bo'lsa, qamrov yo'q, unda LoRaWAN yoki yo'ldosh kerak. Keyin dekabrdagi soya, o'rnatish balandligi 3-4 metr, eshik va qulf turi, muhit. Natija platformaga tushadi: 12 ta foto, o'lchovlar va yechim raqami. Endi montajning o'ziga o'tamiz.",
    ru: "Этот слайд для монтажников. В первый раз на объект едут не с оборудованием, а с измерительными приборами. За час обследования мы выбираем решение. Главное — связь: замеряем всех четырёх операторов и ставим SIM самого сильного. Например, −84 дБм — отлично, а ниже −115 покрытия нет, тогда нужен LoRaWAN или спутник. Дальше тень в декабре, высота установки 3-4 метра, тип двери и замка, среда. Результат уходит в платформу: 12 фото, замеры и номер решения. Переходим к самому монтажу."
  },
  "s-montaj": {
    uz: "Montaj har obyektda bir xil oltita qadamdan iborat. Asosiy qoida: qurilma ofisda sozlanadi, obyektda faqat mahkamlanadi va tekshiriladi. Yangi proshivka, zavod paroli o'rniga alohida parol, SIM va APN, QR yorliq, hammasi obyektga borishdan oldin tayyor bo'ladi. Ikki kishilik brigada batareyali kamerani 1-2 soatda, quyosh ustunini 4-6 soatda, shkafni bir kunda o'rnatadi. Montajchi so'raydi: qurilmani obyektga qanday bog'layman? QR'ni skanerlaysiz, platforma takroriy seriya raqamini o'zi rad etadi. Keyingi mavzu quvvat hisobi.",
    ru: "Монтаж на каждом объекте состоит из одних и тех же шести шагов. Главное правило: устройство настраивается в офисе, а на объекте его только крепят и проверяют. Свежая прошивка, свой пароль вместо заводского, SIM и APN, QR-наклейка, всё готово до выезда. Бригада из двух человек ставит камеру на батарее за 1-2 часа, солнечную опору за 4-6 часов, шкаф за день. Монтажник спросит: как привязать устройство к объекту? Сканируете QR, а повторный серийный номер платформа отклонит сама. Дальше расчёт питания."
  },
  "s-quvvat": {
    uz: "Eng ko'p xato shu yerda qilinadi: quvvatni iyunga hisoblashadi. Biz dekabrga hisoblaymiz, chunki quyosh 4,7 marta kam. Misol: 3 vattli 4G kameraga iyun hisobida 14 vattli panel yetardi va dekabrda kamera o'chib qolardi. To'g'ri hisob 80 vattli panel va 40 amper-soatlik blok. Shkaf esa 50 vatt sarflaydi, uni quyosh ko'tarmaydi. U holda obyektni elektrga qayta ulash arzon: 39 600 so'm va uch ish kuni. Hisob hammaga ochiq, kalkulyatorda o'z obyektingizni tekshirishingiz mumkin. Endi obyekt qanday qabul qilinadi.",
    ru: "Самая частая ошибка здесь: питание считают по июню. Мы считаем по декабрю, потому что солнца в 4,7 раза меньше. Пример: для 4G-камеры на 3 Вт по июньскому расчёту хватило бы панели на 14 Вт, и в декабре камера бы отключилась. Правильный расчёт — панель на 80 Вт и блок на 40 А·ч. А шкаф на 50 Вт солнце не вытянет. Тогда дешевле вернуть объекту электричество: 39 600 сумов и три рабочих дня. Расчёт открытый, свой объект можно проверить в калькуляторе. Теперь о том, как объект принимается."
  },
  "s-qabul": {
    uz: "Bank xodimi va montajchi aktni imzolashdan oldin 12 ta tekshiruvni birga o'tkazadi. Masalan, jonli video 15 soniyada ochilishi kerak, SIM 30 daqiqaga olinadi va hodisalar joyida yozilishi tekshiriladi. Qabuldan keyin integrator SLA bo'yicha javob beradi. Obyekt ko'rinmay qolsa, integrator shaharda 4 soatda, chekkada 48 soatda yetib keladi. Oyiga 98% aloqada bo'lish talabi bor, bajarilmasa oylik to'lovning 10% igacha jarima. Moliya bo'limi uchun asosiy savol: bularning hammasi bir obyektga qanchaga tushadi? Keyingi slayd shu haqda.",
    ru: "Перед подписанием акта сотрудник банка и монтажник вместе проходят 12 проверок. Например, живое видео должно открыться за 15 секунд, SIM вынимают на 30 минут и проверяют, что события пишутся на месте. После приёмки интегратор отвечает по SLA. Если объект пропал с экрана, интегратор приезжает в городе за 4 часа, на удалённый объект — за 48. Требование 98% времени на связи в месяц, иначе штраф до 10% месячного платежа. Главный вопрос финансов: во сколько всё это обходится на один объект? Об этом следующий слайд."
  },
  "s-iqtisod": {
    uz: "Asosiy raqam: masofaviy nazorat bir obyektga yiliga 7,4 mln so'm. Bankning o'z qorovuli 145 mln, Qo'riqlash departamenti posti 55 mln. Ya'ni nazorat eng arzon qo'riqlashdan yetti baravar arzon. Bu tejam emas: bugun obyektlar qo'riqlanmaydi, nazorat bank uchun yangi xarajat. 267 obyektga yiliga taxminan 1,6 mlrd so'm, jamoa va serverlar alohida qator. Post qo'yilganda bank 13 mlrd dan ortiq ko'p to'lardi. Ikkinchi jihat zaxira: 800 mln so'mlik obyekt 12 oyda sotilmasa, 800 mln zaxira kerak bo'ladi, komplekt esa shu summaning 1,3% i. Qanday farazlarga tayandik? Komplekt 5 yilda eskiradi, SIM va servis yiliga 3 mln. Keyingi slayd smeta.",
    ru: "Главная цифра: удалённый контроль обходится в 7,4 млн сумов в год на объект. Собственный сторож банка стоит 145 млн, пост Департамента охраны 55 млн. То есть контроль в семь раз дешевле самой дешёвой охраны. Это не экономия: сегодня объекты не охраняются, контроль для банка новый расход. На 267 объектов около 1,6 млрд сумов в год, команда и серверы отдельной строкой. С постами охраны банк платил бы больше чем на 13 млрд. Второй момент — резерв: если объект за 800 млн не продан за 12 месяцев, нужен резерв 800 млн, а комплект — 1,3% от этой суммы. На каких допущениях построен расчёт? Комплект списывается за 5 лет, SIM и сервис 3 млн в год. Теперь смета."
  },
  "s-bom": {
    uz: "Smeta har jihoz bo'yicha alohida tuzilgan, bozor narxida. Bitta umumiy summa yo'q, shuning uchun har qatorni tijorat taklifi bilan solishtirsa bo'ladi. Masalan, Hikvision quyosh-4G kamerasi 3,8-5,2 mln, Ajax hubi 3,3-5,5 mln so'm. Montaj, kabel, SIM va trafik, transport, servis, API integratsiyasi va bojxona alohida qatorda hisoblanadi, jihoz narxiga yashirilmaydi. Nega aniq narx emas, oraliq? Aniq narxni tender beradi, bu yerdagi oraliq uning chegarasi. Endi me'yorlar.",
    ru: "Смета составлена по каждой позиции оборудования отдельно, по рыночным ценам. Одной общей суммы нет, поэтому каждую строку можно сверить с коммерческим предложением. Например, солнечная 4G-камера Hikvision стоит 3,8-5,2 млн, хаб Ajax 3,3-5,5 млн сумов. Монтаж, кабель, SIM и трафик, транспорт, сервис, API-интеграция и таможня считаются отдельными строками и не прячутся в цену оборудования. Почему диапазон, а не точная цена? Точную цену даст тендер, диапазон задаёт её границы. Дальше — нормы."
  },
  "s-meyor": {
    uz: "Bu slayd huquq bo'limi uchun. Yettita hujjatning har biridan loyihada aniq qaror chiqqan. MB 2696 nizomi: kartochkada 12 oylik sanoq bor, to'qqizinchi oyda sotuv bo'limiga ogohlantirish ketadi. O'RQ-778: qo'riqchi yollanmaydi, signal Qo'riqlash departamenti pultiga boradi. O'RQ-1125: yuzni tanish faqat bank serverida, biometrik ma'lumot chet elga chiqmaydi. Huquqchi so'raydi: ogohlantirish belgisi hali qonun emas-ku? To'g'ri, u loyiha, lekin belgini hozirdan qo'yamiz. Qatorni bossam, lex.uz havolasi ochiladi. Endi ishni kim bajarishiga o'tamiz.",
    ru: "Этот слайд для юристов. Из каждого из семи документов в проекте вышло конкретное решение. Положение ЦБ 2696: в карточке идёт отсчёт 12 месяцев, на девятом месяце отдел продаж получает предупреждение. ЗРУ-778: охранника не нанимаем, сигнал уходит на пульт Департамента охраны. ЗРУ-1125: распознавание лиц только на сервере банка, биометрия за рубеж не уходит. Юрист спросит: табличка о видеонаблюдении ведь ещё не закон? Верно, это проект, но табличку ставим уже сейчас. По клику на строку открывается ссылка на lex.uz. Теперь о том, кто делает работу."
  },
  "s-hamkor": {
    uz: "Bank oldida bitta bosh integrator javob beradi. Bu asosiy tamoyil: muammo chiqsa, beshta kompaniya aybni bir-biriga ag'darmaydi. Tor ishlarni, masalan biometrik terminal yoki import jihozni, ixtisoslashgan subpudratchilar qiladi. Mahalliy bozorda kamera, kirish nazorati va tarmoq bo'yicha tajribali besh kompaniyani ko'rib chiqdik. Tanlov tartibi oltita qadam: ko'rik, uchta taklif, pilot, API tekshiruvi, yakuniy smeta va SLA. Nega bitta integrator? Chunki jarima va SLA bitta shartnomada yozilgan. Endi texnikadan sotuvga o'tamiz.",
    ru: "Перед банком отвечает один генеральный интегратор. Это ключевой принцип: если что-то сломалось, пять компаний не будут кивать друг на друга. Узкие работы, например биометрические терминалы или импортное оборудование, выполняют профильные субподрядчики. Мы изучили пять местных компаний с опытом в камерах, контроле доступа и сетях. Отбор идёт в шесть шагов: осмотр, три предложения, пилот, проверка API, итоговая смета и SLA. Почему один интегратор? Потому что штрафы и SLA прописаны в одном договоре. Теперь от техники к продажам."
  },
  "s-sotuv": {
    uz: "Kamera faqat qo'riqlamaydi, u sotuvni ham tezlashtiradi. E'longa shu hafta olingan kadr va 30 soniyalik video qo'yiladi. Xaridor darvozada domofonni bosadi, operator uni videoda ko'rib eshikni ochadi, xodim obyektga bormaydi. Tashriflar haftaning bir kuniga yig'iladi va jurnalga tushadi. Bizning chegara 365 kun, undan keyin aktiv «umidsiz» toifaga o'tadi, maqsad esa undan ancha oldin sotish. Marketing so'raydi: natijani qanday o'lchaymiz? Uchta ko'rsatkich bilan, e'londan shartnomagacha kunlar va ikki konversiya. Kamera yana qayerda ishlaydi?",
    ru: "Камера не только охраняет, она ещё и ускоряет продажу. В объявление идут кадры этой недели и 30-секундное видео. Покупатель звонит в домофон у ворот, оператор видит его и открывает дверь, сотруднику ехать не нужно. Показы собираются в один день недели и попадают в журнал. Наш предел — 365 дней, после этого актив становится «безнадёжным», а цель продать намного раньше. Маркетинг спросит: как мерить результат? Тремя показателями: дни от объявления до договора и две конверсии. Где ещё работает камера?"
  },
  "s-istiqbol": {
    uz: "Bir marta o'rnatilgan jihoz nazoratdan tashqari ham ishlaydi. Sug'urta: AQShda pultga ulangan signalizatsiya polisni 5-20% arzonlashtiradi, bizda esa bu sug'urtachi bilan muzokara mavzusi. Sotuv: kamera joyida turibdi, bitta tashrifda 360° skan olsak, xaridor binoga bormasdan ichkarini ko'radi. Daromad: sotilguncha omborni arzon ijaraga berish mumkin. Eng katta istiqbol: PQ-142 banklarga kamida 4 trln so'mlik shunday mulkni sotish vazifasini qo'ygan. Bu platformani keyinchalik boshqa banklarga xizmat sifatida taklif qilish mumkin. Bularning hammasi bugun ishlab turgan platformaga tayanadi.",
    ru: "Установленное оборудование работает не только на контроль. Страховка: в США сигнализация с выводом на пульт удешевляет полис на 5-20%, у нас это предмет переговоров со страховщиком. Продажа: камера уже на месте, и если за один выезд снять 360°, покупатель увидит здание изнутри, не приезжая. Доход: до продажи склад можно недорого сдать в аренду. Самая большая перспектива: постановление ПП-142 обязывает банки продать такого имущества минимум на 4 трлн сумов. Эту платформу потом можно предлагать другим банкам как услугу. Всё это опирается на платформу, которая работает уже сегодня."
  },
  "s-platforma": {
    uz: "Bu maket emas: reyestr, obyekt kartochkasi va boshqaruv paneli bugun ishlab turibdi, bitta bazada. Qurilma ulanganda hodisalar aynan shu ekranlarda paydo bo'ladi, alohida dastur sotib olish shart emas. Qurilmalarni ulash uchun media shlyuz, hodisa shinasi va adapterlar pilotda quriladi, buning uchun jamoa kerak. Obyekt kartochkasida balansga olingan sana va 12 oylik sanoq ham shu yerda turadi. Bunga qancha vaqt ketadi? Yo'l xaritasi keyingi slaydda.",
    ru: "Это не макет: реестр, карточка объекта и панель управления уже работают, в одной базе. Когда устройство подключено, события появляются именно на этих экранах, отдельную программу покупать не нужно. Для подключения устройств в пилоте строятся медиашлюз, шина событий и адаптеры, для этого нужна команда. В карточке объекта здесь же видны дата принятия на баланс и отсчёт 12 месяцев. Сколько на это уйдёт времени? Дорожная карта на следующем слайде."
  },
  "s-yol": {
    uz: "267 obyekt to'qqiz oyda, keyin har yangi aktiv 10 ish kunida ulanadi. Reja to'rt bosqich, har biri darvoza bilan tugaydi: ko'rsatkich bajarilmasa, keyingi bosqich boshlanmaydi. Avval 10 obyektda pilot, uptime kamida 98%. Keyin 50 ta eng qimmat va chekka obyekt, yolg'on signal oyiga to'rttadan oshmasligi kerak. Keyin butun balans, obyekt narxi smetadan 10% dan ortiq oshmasligi sharti bilan. Jamoa yetti kishi, montajga ikki kishilik brigadalar. Rahbariyat uchun eng muhimi: har bosqichda to'xtash nuqtasi bor. Pilot qanday o'tishini ko'rsataman.",
    ru: "267 объектов за девять месяцев, дальше каждый новый актив подключается за 10 рабочих дней. План из четырёх этапов, каждый заканчивается контрольной точкой: не выполнен показатель, следующий этап не начинается. Сначала пилот на 10 объектах, время на связи не ниже 98%. Потом 50 самых дорогих и удалённых объектов, ложных срабатываний не больше четырёх в месяц. Потом весь баланс, при условии, что цена объекта не выходит за смету больше чем на 10%. Команда — семь человек, на монтаже бригады по двое. Для правления главное: на каждом этапе есть точка остановки. Покажу, как пройдёт пилот."
  },
  "s-pilot": {
    uz: "Pilot 10 obyektda, 6 haftada. Birinchi hafta audit, keyin 3-4 yechim yonma-yon o'rnatiladi, integratsiya qilinadi va beshinchi haftada o'lchanadi: ishlash vaqti, avtonomlik, yolg'on signal, trafik, javob tezligi. Oltinchi haftada smeta, SLA va 267 obyekt uchun standart tayyor bo'ladi. Pilot muvaffaqiyatli, agar uptime 98% dan past bo'lmasa, yolg'on signal obyektga oyiga to'rttadan oshmasa, javob besh daqiqada bo'lsa va smeta 10% dan oshmasa. Sizdan bugun to'rtta qaror so'rayman: 10 ta pilot obyekt, jihoz uchun 30 dan 200 mln so'mgacha byudjet, jamoa va server alohida qator, bosh integrator modeli va MKB platformasiga ulanish standarti. Nega darhol hammasiga emas? Chunki xato bo'lsa, u 10 obyekt byudjetida qoladi. Oxirida savollaringizga javob beraman.",
    ru: "Пилот на 10 объектах за 6 недель. Первая неделя — аудит, потом ставим три-четыре решения рядом, интегрируем и на пятой неделе замеряем: время работы, автономность, ложные срабатывания, трафик, скорость реакции. На шестой неделе готовы смета, SLA и стандарт для 267 объектов. Пилот успешен, если uptime не ниже 98%, ложных тревог не больше четырёх на объект в месяц, реакция в пределах пяти минут, а смета превышена не больше чем на 10%. Сегодня прошу вас утвердить четыре пункта: 10 пилотных объектов, бюджет на оборудование от 30 до 200 млн сумов, команда и серверы отдельной строкой, модель генерального интегратора и стандарт подключения к платформе MKB. Почему не сразу на все? Потому что если ошибёмся, ошибка останется в бюджете 10 объектов. Дальше готов ответить на вопросы."
  },
  "s-faq": {
    uz: "Qiyin savollarga javoblar tayyor, ular auditoriya bo'yicha tabga ajratilgan. Eng ko'p so'raladiganlari: kamera o'g'irlansa-chi? O'g'rining kadri kamera yechilishidan oldin serverga ketadi, jihoz 3-4 metr balandlikda va sug'urtalangan. Tunda signalni kim ko'radi? Bankning navbatchi operatori, kerak bo'lsa Qo'riqlash departamenti chiqadi. Obyekt sotilgach jihoz-chi? Yechiladi va keyingi obyektga qo'yiladi, tarix saqlanadi. Savollaringizni eshitishga tayyorman. Qarorlar ro'yxati pilot slaydida turibdi, xohlasangiz o'shanga qaytamiz.",
    ru: "Ответы на трудные вопросы подготовлены и разложены по вкладкам для каждой аудитории. Самые частые: а если камеру украдут? Кадр вора уходит на сервер раньше, чем камеру снимут, к тому же она висит на высоте 3-4 метра и застрахована. Кто ночью видит тревогу? Дежурный оператор банка, при необходимости выезжает Департамент охраны. Что с оборудованием после продажи объекта? Снимаем и ставим на следующий, история сохраняется. Готов ответить на ваши вопросы. Пункты на утверждение — на слайде пилота, можем к нему вернуться."
  }
};
