/* ---------------------------------------------------------------------------
   taqdimot-yechim.js — elektrsiz obyektni nazorat qilishning o'n bir yo'li.

   Har bir yechim bo'yicha: qanday ishlaydi, integratsiyasi (dasturchi uchun
   protokol darajasida), ko'p obyektda qanday masshtablanadi, masofadan nima
   qilinadi, narxi, qayerdan olinadi, kim o'rnatadi va kamchiligi.

   Narxlar 2026-yil sentabr holatiga. Manba havolasi har bandda.
   --------------------------------------------------------------------------- */
(function () {
  "use strict";

  const YECHIM = [
    /* ---------------------------------------------------------------- 01 */
    {
      qisqa: "Plomba va NFC teg",
      nom: "Quvvatsiz bazaviy qatlam: mexanik plomba va NFC teg",
      tavsif: "Uch yuz obyektning hammasiga kamera qo'yish shart emas va foydali ham emas. Obyektlarning katta qismi uchun bankka bitta savolga javob kerak: eshik ochildimi yoki yo'q. Bu javobni elektrsiz olsa bo'ladi.",
      ishlashi: "Eshik va darvozaga bir martalik raqamli plomba o'rnatiladi, yoniga NFC teg yopishtiriladi. Inspektor ko'rikka kelganda telefonini tegga tekkizadi: ilova plomba raqamini, vaqtni va joylashuvni qayd etadi. Plomba butun bo'lsa ko'rik o'n soniyada yakunlanadi; uzilgan bo'lsa hodisa ochiladi. Quvvat umuman talab qilinmaydi, batareya yo'q, qishdan ta'sirlanmaydi.",
      integratsiya: "NFC teg NTAG213/216 standartida, ichida faqat noyob UID va obyekt raqami bo'ladi. Mobil ilova tegni o'qib, tizimga imzolangan so'rov yuboradi. Aloqa bo'lmagan joyda yozuv telefonda navbatga qo'yiladi va tarmoq paydo bo'lgach yuboriladi.",
      kod: "POST /api/v1/korik\nAuthorization: Bearer <xodim_tokeni>\n{\n  \"obyekt_id\": \"AK-2026/0141\",\n  \"teg_uid\":   \"04A3B2C1D5E680\",\n  \"plomba\":    \"MKB-0034719\",\n  \"holat\":     \"butun\",\n  \"vaqt\":      \"2026-12-14T11:20:03+05:00\",\n  \"joy\":       {\"lat\": 41.3111, \"lng\": 69.2401, \"aniqlik\": 8},\n  \"surat\":     \"<base64 yoki yuklangan fayl havolasi>\"\n}",
      masshtab: "Cheklov yo'q. Uch yuz obyekt uchun taxminan to'qqiz yuz teg kerak bo'ladi va ular bitta qutiga sig'adi. Tizim har bir obyekt bo'yicha oxirgi ko'rik sanasini yuritadi va muddati o'tganlarni ko'rik rejasiga o'zi qo'shadi.",
      masofadan: "Yo'q. Bu qatlam masofadan kuzatish emas, ko'rikni hujjatlashtirish vositasi. Uning qiymati shundaki, sug'urta polisidagi «davriy ko'rik» sharti aynan shunday yozuv bilan bajariladi.",
      narx: "Teg — 1 300 so'm atrofida, plomba — 2 000 so'mdan. Uch yuz obyekt uchun taxminan 3 mln so'm.",
      qayerdan: "NFC teglar — olx.uz va xalqaro yetkazib beruvchilar; plombalar — mahalliy ishlab chiqaruvchilar",
      kim: "O'rnatish malaka talab qilmaydi, obyekt menejeri o'zi bajaradi",
      quvvat: "Talab qilinmaydi",
      kimga: "Barcha obyektlarga, istisnosiz",
      kamchilik: "Hodisa sodir bo'lgan payt emas, keyingi ko'rikda ma'lum bo'ladi. Ya'ni bu qatlam o'g'irlikning oldini olmaydi, faqat uni inkor qilib bo'lmaydigan qilib qayd etadi.",
      manba: "https://www.olx.uz/",
    },
    /* ---------------------------------------------------------------- 02 */
    {
      qisqa: "Tarmoqqa qayta ulanish",
      nom: "Elektr tarmog'iga qayta ulanish",
      tavsif: "Eng kam e'tibor beriladigan, lekin ko'p obyekt uchun eng arzon yechim. Nazorat uzeli bor-yo'g'i 40–60 vatt tortadi. Bu maishiy choynakdan o'n barobar kam.",
      ishlashi: "Obyektga 220 volt qaytariladi. Ulanish quvvati 20 kilovattdan past bo'lgani uchun soddalashtirilgan reglament amal qiladi: texnik shart yagona portal orqali uch ish kunida beriladi. Shundan keyin batareya ham, quyosh ham, qish ham masala bo'lmay qoladi.",
      integratsiya: "Obyekt standart tarmoq arxitekturasiga o'tadi va integratsiya muammosi butunlay yo'qoladi. Kamera quvvatni kabel orqali oladi, ONVIF Profile S va T beradi, oqim to'g'ridan-to'g'ri markaziy tizimga tushadi. Hisoblagichning o'zi ham nazoratga qo'shiladi: iste'mol keskin oshsa, demak obyektda kimdir bor.",
      kod: "Video:  rtsp://<login>:<parol>@<IP>:554/Streaming/Channels/101   (Hikvision)\n        rtsp://<login>:<parol>@<IP>:554/cam/realmonitor?channel=1&subtype=0  (Dahua)\nVoqea:  ONVIF CreatePullPointSubscription -> PullMessages\n        tns1:VideoSource/MotionAlarm\nQuvvat: Modbus RTU, RS-485, 9600 8N1, slave 1\n        0x0000 kuchlanish, 0x0008 jami energiya\n        RS-485 -> Modbus TCP (502) -> markazdan 5 daqiqada so'rov",
      masshtab: "Yagona variant, unda uch yuz obyekt bir xil, standart va almashtiriladigan konfiguratsiyaga tushadi. Har obyekt markazga yopiq tunnel orqali ulanadi, markazda bitta konsentrator turadi.",
      masofadan: "To'liq: qayta yuklash, proshivka yangilash, aylantirish, ikki tomonlama ovoz, sozlamalarni markazdan tarqatish. Hech qanday cheklov yo'q.",
      narx: "Texnik shart 39 600 so'm, uch ish kuni. Tarif 1 100 so'm/kVt·soat, oyiga taxminan 38 500 so'm. Ichki simlash va shchitni tiklash alohida hisoblanadi.",
      qayerdan: "my.gov.uz, 172-xizmat; het.uz, 1154",
      kim: "Hisoblagichni faqat tarmoq tashkiloti xodimi o'rnatadi. Ichki tarmoqni litsenziyalangan elektromontaj tashkiloti tiklaydi.",
      quvvat: "Tarmoqdan, cheklovsiz",
      kimga: "Simlash saqlanib qolgan va qarzdorligi yopilgan obyektlarga",
      kamchilik: "Garov obyektida eski simlash ko'pincha yaroqsiz, ba'zan mis o'g'irlangan. Sobiq egasining qarzi bo'lsa ulanish tiklanmaydi. Obyekt sotilgan kuni shartnomani yopish kerak — uch yuz obyektda bu doimiy ma'muriy oqim.",
      manba: "https://my.gov.uz/uz/service/172",
    },
    /* ---------------------------------------------------------------- 03 */
    {
      qisqa: "Professional quyosh-4G",
      nom: "Professional avtonom kamera: quyosh va 4G bitta korpusda",
      tavsif: "Bank darajasidagi to'liq protokol to'plamini beradigan yagona sinf. Qimmat, shuning uchun faqat eng qimmat obyektlarga qo'yiladi.",
      ishlashi: "Kamera, 80 vattli panel va 360 vatt-soatlik batareya bitta korpusda keladi. Ishlash harorati -20 darajagacha. Odam va transportni qurilmaning o'zi ajratadi, shuning uchun shamol yoki daraxt sababli behuda signal bermaydi. Bulutli kunlarda zaxira besh kunga yetadi.",
      integratsiya: "Bu sinfning asosiy afzalligi — u yopiq ekotizim emas. ONVIF Profile S, G va T sertifikati bor, RTSP oqimini ishlab chiqaruvchi bulutisiz beradi, voqealarni ham ONVIF orqali, ham o'z HTTP interfeysi orqali uzatadi.",
      kod: "Oqim:  rtsp://<login>:<parol>@<IP>:554/Streaming/Channels/101\nVoqea: GET /ISAPI/Event/notification/alertStream  (uzun ulanish, multipart)\n       <EventNotificationAlert><eventType>VMD</eventType>...\nONVIF: WS-Discovery UDP 3702 -> GetCapabilities -> Events\n       CreatePullPointSubscription -> PullMessages\nHolat: GET /ISAPI/System/status  (batareya, quvvat, harorat)",
      masshtab: "Markazda uch yuz jonli oyna emas, uch yuz obyekt kartochkasi turadi: oxirgi kadr, batareya, signal va oxirgi hodisa vaqti. Video faqat operator obyektni bosganda ochiladi va bir-uch daqiqadan keyin yopiladi.",
      masofadan: "To'liq, professional kameradagi hamma narsa: aylantirish, masshtab, prozhektor, ovoz, qayta yuklash, proshivka.",
      narx: "Komplekt 2 030 dollardan; olib kelish, bojxona va o'rnatish bilan 2 600 – 3 300 dollar atrofida.",
      qayerdan: "uzhikvision.uz — rasmiy distribyutor, kafolat va hujjat bilan",
      kim: "Litsenziyaga ega xavfsizlik integratori: SAT Solutions, KSS, videonablyudeniya.uz",
      quvvat: "Quyosh, 360 Vt·soat zaxira",
      kimga: "Qiymati 5 mlrd so'mdan yuqori obyektlar, taxminan 20–40 ta",
      kamchilik: "Narxi eng yuqori. Panel va batareya bo'sh obyektda o'g'irlanadigan likvid mol, shuning uchun ustun balandligi va antivandal quti majburiy.",
      manba: "https://www.hikvision.com/",
    },
    /* ---------------------------------------------------------------- 04 */
    {
      qisqa: "O'rta toifa kamera",
      nom: "O'rta toifa: -20 darajada ishlaydigan 4G kamera",
      tavsif: "Professional komplektdan besh-olti barobar arzon, lekin qishda ishlashi tasdiqlangan. Ko'pchilik obyekt uchun ayni shu toifa yetarli.",
      ishlashi: "Aylanuvchi kamera, o'z batareyasi va kichik quyosh paneli bilan. Harakat datchigi va qurilmadagi odam aniqlash tufayli behuda signal bermaydi. Xotira kartasi 512 gigabaytgacha: aloqa uzilsa yozuv joyda saqlanadi va tiklangach yuboriladi.",
      integratsiya: "Diqqat: bu toifada model tanlashda protokol hal qiluvchi. Ochiq platforma interfeysi bo'lgan modellar tanlanadi, faqat ishlab chiqaruvchi ilovasi bilan ishlaydiganlari rad etiladi. Texnik topshiriqqa shu band yoziladi va u bozordagi yaroqsiz takliflarning yarmini avtomatik filtrlaydi.",
      kod: "TEXNIK TOPSHIRIQ BANDI:\n«Qurilma ONVIF Profile S sertifikatiga ega bo'lishi, RTSP orqali\n ishlab chiqaruvchi bulutisiz lokal oqim berishi va voqealarni\n ONVIF Events yoki HTTP webhook orqali uzatishi shart»\n\nVoqea: POST <bank_url>/api/v1/hodisa\n       {\"qurilma\":\"...\",\"tur\":\"harakat\",\"vaqt\":\"...\",\"kadr\":\"...\"}",
      masshtab: "Voqea markazlashtiriladi, video emas. Uch yuz obyektdan kelayotgan voqea oqimi bir kunda bir necha ming yozuvni tashkil qiladi va bu oddiy ma'lumotlar bazasi uchun yuk emas.",
      masofadan: "Sozlash, qayta yuklash va kadr so'rash mumkin. Jonli oqimni uzoq ochib turish batareyani tez tugatadi, shuning uchun u talab bo'yicha ishlatiladi.",
      narx: "Kamera 1,9 mln so'm atrofida; quyosh paneli va mahkamlagich bilan obyekt boshiga 250 – 600 dollar.",
      qayerdan: "asaxiy.uz, texnomart.uz, olx.uz; EZVIZ va Imou bo'yicha O'zbekistonda rasmiy vakolatxona bor",
      kim: "Har qanday xavfsizlik integratori; montaj bir necha soat",
      quvvat: "Quyosh va batareya",
      kimga: "Do'kon, ofis, ustaxona — taxminan 100–150 ta obyekt",
      kamchilik: "Litiy batareya nol darajadan past haroratda zaryad olmaydi. Ya'ni dekabrda quyosh porlab tursa ham batareya to'lmaydi. Shu sabab batareya izolyatsiyalangan qutiga joylashtiriladi va qish uchun zaxira ortiqcha olinadi.",
      manba: "https://www.ezviz.com/product/eb8+4g/46565",
    },
    /* ---------------------------------------------------------------- 05 */
    {
      qisqa: "Videosiz datchiklar",
      nom: "Videosiz yechim: faqat voqea datchiklari",
      tavsif: "Bo'sh uy yoki yer uchastkasida video kerak emas. Bankka ikki savolga javob kerak: kimdir kirdimi va quvur yorildimi. Bu javob videodan yuz barobar arzon.",
      ishlashi: "Eshik ochilishi, vibratsiya, suv bosishi va harorat datchiklari o'z batareyasida ishlaydi. Batareya muddati uch-besh yil, ya'ni ular ko'rik oralig'ida almashtirilmaydi. Datchiklar obyektdagi markazga simsiz ulanadi, markaz esa 4G orqali bankka bog'lanadi.",
      integratsiya: "Signalizatsiya markazi qo'riqlash sanoatining standart protokoli bilan gaplashadi. Shu tufayli bitta hodisa bir vaqtda ham davlat qo'riqlash pultiga, ham bank tizimiga tushadi — ikkita alohida tizim qurish shart emas.",
      kod: "SIA DC-09 ramkasi (TCP/UDP, shifrlangan):\n\"ADM-CID\" 0018 \"#123456|1130 01 003\"\n   1130 — trevoga,  01 — bo'lim,  003 — zona raqami\n\nYoki markaz API si orqali:\nPOST /api/v1/hodisa   {\"zona\":3,\"tur\":\"eshik\",\"vaqt\":\"...\"}",
      masshtab: "Yechimning kuchli tomoni aynan shu: markazlashtirilgan dastur ellik mingtagacha obyektni qo'llab-quvvatlaydi va O'zbekistonda rasmiy distribyutori bor. Uch yuz obyekt bu miqyosda hech qanday muammo emas.",
      masofadan: "Zona sezuvchanligini sozlash, tizimni qo'riqlashga qo'yish va yechish, batareya holatini ko'rish. Video yo'q, shuning uchun tasvir so'ralmaydi.",
      narx: "Obyekt boshiga 80 – 200 dollar, ya'ni o'rta toifa kameradan uch barobar arzon.",
      qayerdan: "asaxiy.uz va Ajax ning O'zbekistondagi rasmiy distribyutori",
      kim: "Qo'riqlash signalizatsiyasi litsenziyasiga ega montaj tashkiloti",
      quvvat: "Datchiklar batareyada, markaz kichik quyosh panelida",
      kimga: "Bo'sh uy, yer uchastkasi, past xatarli obyektlar — 100–150 ta",
      kamchilik: "Dalil sifatida surat bo'lmaydi. Signal keldi, lekin kim kirgani noma'lum. Shu sabab yuqori xatarli obyektlarda bu qatlam kamera bilan birga ishlatiladi.",
      manba: "https://ajax.systems/",
    },
    /* ---------------------------------------------------------------- 06 */
    {
      qisqa: "Batareyali komplekt",
      nom: "Batareyali kamera to'plami: Ugreen misoli va uning haqiqati",
      tavsif: "Bozorda eng ko'p reklama qilinadigan sinf: to'rt kamera va domofon bitta qutida, batareyasi yiliga bir marta almashtiriladi. Bank uchun bu jozibador ko'rinadi, lekin bitta texnik haqiqat hammasini o'zgartiradi.",
      ishlashi: "Kamera doimo uxlab yotadi. Uyqu rejimida u 0,03 vatt, oqim berayotganda 2,6–4,9 vatt tortadi — farq yuz barobardan ortiq. Shuning uchun batareyali kamera doimiy video bera olmaydi: bu mahsulot kamchiligi emas, fizika.",
      integratsiya: "Bu sinfning aksariyati bank tizimiga umuman ulanmaydi. Ishlab chiqaruvchilarning o'zi hujjatda yozadi: batareyali kameralar apparat cheklovi tufayli standart protokollarni bermaydi. Ishlaydigan yagona sxema — obyektda markaz (hub) bo'lishi, o'shanda protokol ochiladi, lekin bitta ulanish besh daqiqadan oshmaydi va markazning o'zi doimiy quvvat talab qiladi.",
      kod: "Hub orqali (yagona ishlaydigan yo'l):\nrtsp://<login>:<parol>@<HUB_IP>:554/Preview_01_sub\n\nTUZOQ: interfeysda kanal 0 dan, RTSP da 1 dan sanaladi.\nAPI dagi channel=2  ->  RTSP da Preview_03_main\n\nSessiya 5 daqiqadan oshmaydi, keyin kamera uxlaydi.\nVMS da RTSP timeout kamida 20 soniya qilinadi.",
      masshtab: "Uch yuz obyekt uchun uch yuz markaz kerak bo'ladi, ya'ni quvvat masalasi yo'qolmaydi, faqat kichrayadi. Uch yuz oqimni bir vaqtda dekodlash iqtisodiy jihatdan imkonsiz, shuning uchun arxitektura baribir voqeaga asoslanadi.",
      masofadan: "Sezilarli cheklangan. Aylantirish va jonli ko'rish har safar batareyani yeydi. «Hozir ko'rsat» so'rovi uch-sakkiz soniya kechikadi, kamera chuqur uyquda bo'lsa umuman javob bermasligi mumkin.",
      narx: "Xalqaro chakana 250 – 330 dollar, markaz alohida. O'zbekistonda rasmiy narx yo'q.",
      qayerdan: "O'zbekistonda rasmiy distribyutor yo'q, faqat olib kelinganlari",
      kim: "Montaj oddiy, lekin markaz va tunnel sozlashni integrator qiladi",
      quvvat: "Batareya, markaz uchun doimiy quvvat kerak",
      kimga: "Bank miqyosida tavsiya etilmaydi",
      kamchilik: "Ugreen ning yangi kuzatuv qatori hali sotuvda emas: u 2026-yilning ikkinchi yarmiga va'da qilingan va protokollari e'lon qilinmagan. Ya'ni bugun uni smetaga kiritib bo'lmaydi. Ikkinchi jiddiy kamchilik: batareyani almashtirish uchun uch yuz obyektga yiliga o'n ikki martagacha odam borishi kerak, va kamera batareyasi tugagan payt aynan obyekt himoyasiz qolgan payt bo'ladi.",
      manba: "https://support.reolink.com/articles/900000617826-Which-Reolink-Products-Support-CGI-RTSP-ONVIF/",
    },
    /* ---------------------------------------------------------------- 07 */
    {
      qisqa: "Almashtiriladigan batareya",
      nom: "Almashtiriladigan quvvat bloki",
      tavsif: "Zaryadlagichni obyektga olib bormaydilar. Zaryadlangan blokni olib borib, bo'shini olib qaytadilar. Tashrif uch daqiqa davom etadi.",
      ishlashi: "Obyektda ikkita uya bo'ladi: biri ishlaydi, ikkinchisi zaxira. Ko'rikka kelgan xodim blokni almashtiradi va obyekt bir soniya ham nazoratsiz qolmaydi. Bu sxema faqat batareyasi mexanik yechiladigan modellarda ishlaydi.",
      integratsiya: "Muhim nozik joy: batareya darajasi standart kamera protokolida umuman yo'q. Shuning uchun quvvat holati alohida kanal bilan olinadi — batareya klemmasiga mustaqil voltmetr datchigi qo'yiladi. Shunda kamera o'lgan taqdirda ham signal keladi. Almashtirish fakti esa blokdagi teg orqali qayd etiladi.",
      kod: "POST /api/v1/batareya-almashtirish\n{\n  \"obyekt_id\":  \"AK-2026/0141\",\n  \"eski_teg\":   \"04A3B2C1D5E680\",\n  \"yangi_teg\":  \"04F1E2D3C4B590\",\n  \"kuchlanish\": 12.9,\n  \"vaqt\":       \"2026-12-14T11:24:11+05:00\",\n  \"joy\":        {\"lat\": 41.3111, \"lng\": 69.2401}\n}",
      masshtab: "Uch yuz obyekt uchun aylanma fond: har obyektga ikki komplekt va o'n foiz zaxira, jami olti yuz oltmishga yaqin blok. Tizim kuchlanish pasayish tezligiga qarab keyingi almashtirish sanasini oldindan aytadi va uni ko'rik marshrutiga qo'shadi.",
      masofadan: "Almashtirishning o'zi qo'l mehnati. Masofadan faqat bashorat qilinadi: qaysi obyekt keyingi yetti kunda o'chadi.",
      narx: "Zaxira blok 25 – 35 dollar; NFC teg yuz donasi 10 dollar atrofida.",
      qayerdan: "Quyosh jihozlari sotuvchilari: glotr.uz, prom.uz, olx.uz",
      kim: "Birinchi o'rnatishni integrator, keyingi almashtirishlarni bank xodimi bajaradi",
      quvvat: "Almashtiriladigan blok",
      kimga: "Ko'rik marshrutiga tushadigan, aloqa yaxshi obyektlar",
      kamchilik: "Batareyasi yechiladigan modellar ro'yxati qisqa va ular eski avlod. «Almashtiriladigan» va «ochiq protokolli» xususiyatlari bitta modelda kamdan-kam uchraydi. Yechiladigan batareya — o'g'irlanadigan batareya, korpus qulfi shart.",
      manba: "https://support.reolink.com/articles/900000587166-How-to-Replace-the-Battery-of-Reolink-Cameras/",
    },
    /* ---------------------------------------------------------------- 08 */
    {
      qisqa: "Ko'chma minora",
      nom: "Ko'chma quyosh nazorat minorasi",
      tavsif: "Obyektni doimiy emas, muddatli himoya qiladi: sotuvdan oldingi uch oy yoki xavf keskin oshgan davr. Bir soatda ko'chiriladi va o'rnatish ishini talab qilmaydi.",
      ishlashi: "Tirkamadagi cho'ziladigan ustun, aylanuvchi kamera, quyosh panellari, akkumulyator bloki, 4G modem va prozhektor. Obyekt sotilgach minora keyingisiga ko'chadi — ya'ni jihoz bo'sh qolmaydi.",
      integratsiya: "Ijara shartnomasida ochiq protokol kirish huquqi ALOHIDA band bilan yozilishi shart. Ko'p provayder faqat o'z ilovasini beradi, bu esa bank tizimiga integratsiyani imkonsiz qiladi. Band bo'lmasa yechim rad etiladi.",
      kod: "SHARTNOMA BANDI:\n«Ijaraga beruvchi buyurtmachiga kameralarga RTSP orqali\n to'g'ridan-to'g'ri kirish va voqealarni HTTP webhook orqali\n olish imkonini beradi»\n\nVoqea: POST /api/v1/hodisa\n{\"qurilma\":\"MIN-04\",\"tur\":\"kirish\",\"vaqt\":\"...\",\n \"kadr\":\"https://...\",\"joy\":{\"lat\":...,\"lng\":...}}",
      masshtab: "Uch yuz minora iqtisodiy jihatdan mumkin emas. Real model — o'n-yigirma minorani eng yuqori xatarli obyektlar bo'yicha aylantirib ishlatish. Tizimda minora ko'chma aktiv sifatida yuritiladi va joylashuvi bo'yicha joriy obyektga o'zi bog'lanadi.",
      masofadan: "Aylantirish, prozhektor, ovozli ogohlantirish, qayta yuklash — to'liq. Lekin bu boshqaruv odatda provayder tizimida qoladi.",
      narx: "Xalqaro ijara oyiga 800 – 2 500 dollar. Mahalliy yig'ish ancha arzon: tirkama, quyosh komplekti va 4G kamera.",
      qayerdan: "O'zbekistonda ijara bozori yo'q. Amaliy yo'l — mahalliy integratorga yig'dirish.",
      kim: "Metall konstruksiya ustaxonasi, quyosh montajchisi va videonazorat integratori birgalikda",
      quvvat: "Quyosh va akkumulyator bloki",
      kimga: "Sotuv arafasidagi yoki xavfi keskin oshgan obyektlar",
      kamchilik: "Minoraning o'zi yirik, ko'rinadigan va qimmat aktiv. Qorovulsiz obyektda uni himoya qilish alohida masala.",
      manba: "https://www.wcctv.co.uk/our-sectors/vacant-property-security/",
    },
    /* ---------------------------------------------------------------- 09 */
    {
      qisqa: "Generator",
      nom: "Yonilg'i yoki gaz generatori",
      tavsif: "To'liqlik uchun ko'rib chiqildi va bank sharoitida rad etildi. Sabablarini ochiq aytish kerak, chunki bu variant har doim taklif qilinadi.",
      ishlashi: "Ikki kilovattli generator nazorat uzeli uchun ellik barobar ortiqcha. Yonilg'i sarfi yukka deyarli bog'liq emas: sutkada yigirma litrgacha. Bak hajmi o'n besh-yigirma besh litr, ya'ni har kuni odam kelib yonilg'i quyishi kerak.",
      integratsiya: "Texnik jihatdan generator avtomatik ulash kontrolleri orqali tizimga ulanadi va kuchlanish, chastota hamda ishlagan soat masofadan o'qiladi. Ammo bu integratsiya amalda ma'nosiz, chunki generator bo'sh obyektda uzoq ishlay olmaydi.",
      kod: "Kontroller: Modbus RTU, RS-485\n  kuchlanish, chastota, ishlagan soat, yonilg'i darajasi\n  -> Modbus TCP (502) -> markaz\n\nLekin: yonilg'i quyishni masofadan qilib bo'lmaydi.",
      masshtab: "Uch yuz obyektga generator qo'yish uch yuz ta yonilg'i marshruti degani.",
      masofadan: "Ishga tushirish va o'chirish mumkin, yonilg'i quyish — yo'q. Shu omil yechimni butunlay chegaralaydi.",
      narx: "Generator 5,8 mln so'mdan. Yonilg'i oyiga 7 mln so'mgacha — ya'ni bir oylik yonilg'i generatorning o'zidan qimmat.",
      qayerdan: "olx.uz, prom.uz, glotr.uz, ikarvon.uz",
      kim: "Elektromontaj tashkiloti",
      quvvat: "Yonilg'i",
      kimga: "Faqat ta'mir yoki baholash paytidagi bir necha kunlik vaqtinchalik quvvat",
      kamchilik: "Generator va yonilg'i bakining o'zi o'g'irlanadi. Turar-joy massivida shovqin shikoyat keltiradi. Bo'sh binoda yong'in va is gazi xavfi bank uchun qabul qilib bo'lmaydigan javobgarlik. Gaz varianti umuman ishlamaydi, chunki obyektlarda gaz ham uzilgan.",
      manba: "https://www.olx.uz/oz/elektronika/q-generator/",
    },
    /* ---------------------------------------------------------------- 10 */
    {
      qisqa: "Shamol turbinasi",
      nom: "Shamol mikroturbinasi",
      tavsif: "Ko'p taqdimotda chiroyli ko'rinadi, lekin O'zbekiston shamol resursi bu yechimni deyarli barcha obyekt uchun rad etadi.",
      ishlashi: "Turbina quvvati shamol tezligining kubiga proporsional. To'rt yuz vattli turbina nominal quvvatini o'n bir metr/soniyada beradi. O'zbekistonda o'n metr balandlikda o'rtacha yillik tezlik uch-besh metr/soniya. Uch metr/soniyada turbina nominalning ikki foizini, ya'ni sakkiz vattni beradi — bu bitta kamerani ham to'liq quvvatlantirmaydi.",
      integratsiya: "Turbina zaryad kontrolleri orqali quyosh paneli bilan bir xil shinaga ulanadi, shuning uchun dasturchi uchun u alohida protokol emas: monitoring qatlami quyoshdagi bilan aynan bir xil.",
      kod: "Kontroller: RS-485 Modbus RTU yoki MQTT\n  N/<portal_id>/solarcharger/<id>/Yield/Power\n  N/<portal_id>/battery/<id>/Dc/0/Voltage\n\nYa'ni turbina — quvvat manbai, integratsiya nuqtasi emas.",
      masshtab: "Massaviy qo'llash uchun yaroqsiz.",
      masofadan: "Monitoring mumkin, mexanik qismni masofadan xizmat ko'rsatib bo'lmaydi. Podshipnik har ikki-uch yilda ko'rikdan o'tadi.",
      narx: "Turbina va kontroller 300 – 600 dollar, lekin machta, fundament va montaj turbinaning o'zidan qimmatga tushadi.",
      qayerdan: "O'zbekistonda maxsus sotuvchi topilmadi",
      kim: "Machta uchun qurilish tashkiloti, elektr qismi uchun montajchi",
      quvvat: "Shamol, quyosh bilan gibrid holda",
      kimga: "Faqat Qoraqalpog'iston va Buxoro yo'nalishidagi ayrim obyektlar",
      kamchilik: "Harakatlanuvchi qismlar ishonchlilikni pasaytiradi, shovqin va vibratsiya turar-joy hududida muammo tug'diradi, machta esa yana bitta o'g'irlanadigan metall konstruksiya.",
      manba: "https://cyberleninka.ru/article/n/wind-resources-of-tashkent-region-and-their-utilization-opportunities-for-sustainable-energy-development",
    },
    /* ---------------------------------------------------------------- 11 */
    {
      qisqa: "Markaziy platforma",
      nom: "Markaziy qatlam: uch yuz obyektni bitta ekranga yig'ish",
      tavsif: "Qurilma tanlash yechimning yarmi. Ikkinchi yarmi — ularni bitta joyda ko'rsatadigan qatlam. Busiz uch yuz obyekt uch yuz ta alohida ilova bo'lib qoladi.",
      ishlashi: "Markazda ikki narsa turadi: video tizimi va voqea shinasi. Video tizimi oqimlarni ro'yxatga oladi va talab bo'yicha ochadi. Voqea shinasi esa barcha ishlab chiqaruvchidan kelgan signalni bitta ko'rinishga keltiradi va bank tizimiga uzatadi.",
      integratsiya: "Ochiq tizimda voqealar aniq mavzularga chiqadi va ularni o'qish uchun maxsus dastur kerak emas. Bank tizimi shinaga obuna bo'ladi va hodisani obyekt kartochkasiga bog'laydi.",
      kod: "MQTT mavzulari (Frigate misolida):\n  frigate/events              — barcha voqealar\n  frigate/<kamera>/motion     — harakat\n  frigate/<kamera>/status     — qurilma holati\n  frigate/stats               — tizim yuki\n\nREST: GET /api/events?after=<ts>   (JWT bilan)\nBank tomoni: shinaga obuna -> normalizatsiya -> reyestr",
      masshtab: "Bu qatlamda uch yuz ham, uch ming obyekt ham bir xil ishlaydi, chunki markazga video emas, voqea keladi. Yuk oqimlar soniga emas, hodisalar soniga bog'liq.",
      masofadan: "Barcha obyektlar bo'yicha yagona boshqaruv: sozlama shabloni, proshivka to'lqini, qurilma holati va aloqa yo'qolganini avtomatik aniqlash.",
      narx: "Ochiq tizim litsenziyasiz. Tijorat tizimlarida litsenziya kamera boshiga hisoblanadi va uch yuz obyektda asosiy xarajat moddasiga aylanadi.",
      qayerdan: "Bank o'z serverida joylashtiradi",
      kim: "Bank axborot texnologiyalari bo'limi tizim integratori bilan birgalikda",
      quvvat: "Bank serverxonasi",
      kimga: "Butun tarmoqqa, bitta nusxada",
      kamchilik: "Bu qatlam kechiktirilsa, har bir yetkazib beruvchi o'z ilovasini olib keladi va bir yildan keyin bankda o'nlab bog'lanmagan tizim paydo bo'ladi. Uni keyin birlashtirish boshidan qurishdan qimmatroq turadi.",
      manba: "https://docs.frigate.video/integrations/mqtt/",
    },
  ];

  window.MKB_YECHIM = { YECHIM };
})();
