/* ============================================================
   tizim-lugat.js — chuqur sahifalar matnining ruscha tarjimasi.
   Kalit — o'zbekcha matn tugunining aynan o'zi (taqdimot-lugat.js bilan bir xil qoida).
   Uzun batafsil matnlari bu yerda emas: ular yozuvning "ru" maydonida turadi.
   ============================================================ */
window.MKB_LUGAT = Object.assign(window.MKB_LUGAT || {}, {

/* --- sarlavha qatori va yo'lakcha --- */
"Taqdimotga qaytish": "Вернуться к презентации",
"Integratsiya slaydi": "Слайд об интеграции",
"Platforma slaydi": "Слайд о платформе",
"Til": "Язык",
"Chop etish": "Печать",
"Bo'limlar": "Разделы",
"Sahifa boshiga": "В начало страницы",
"Bitta hodisaning 41 soniyasi": "41 секунда одного события",
"Olti qatlam": "Шесть слоёв",
"Adapter brend bilan nima qiladi": "Что адаптер делает с брендом",
"Uchta buzilish": "Три отказа",
"Bir obyektning bir kuni": "Сутки одного объекта",
"Uchta ekran": "Три экрана",
"Kim nima qiladi": "Кто что делает",
"Indeks va muddatlar": "Индекс и сроки",
"10 dan 1 000 obyektgacha": "От 10 до 1 000 объектов",
"Xavfsizlik va ma'lumot joyi": "Безопасность и место данных",
"Bank o'zi yuritadigan qism": "Что банк ведёт сам",

/* --- tizim-ishlashi: bosh maydon --- */
"Tizim ishlashi · chuqur sahifa": "Как работает система · подробная страница",
"Dekabr kechasidagi signal bank qaroriga qanday aylanadi": "Как декабрьский ночной сигнал становится решением банка",
"Qarshidagi ombor darvozasi oldida soat 03:12 da harakat qayd etiladi. Elektr yo'q, qo'riqchi yo'q, eng yaqin xodim 60 kilometr narida. Quyida shu signalning datchikdan operator ekranigacha, ekrandan obyekt kartochkasidagi yozuvgacha bo'lgan yo'li soniyama-soniya yozilgan.": "У ворот склада под Карши в 03:12 фиксируется движение. Электричества нет, сторожа нет, ближайший сотрудник в 60 километрах. Ниже посекундно расписан путь этого сигнала: от датчика до экрана оператора и от экрана до записи в карточке объекта.",
"Har blok bosiladi: hisob-kitob va sabab shu yerda ochiladi": "Любой блок кликается: расчёт и причина открываются здесь же",
"Raqamlar taqdimotdagi slaydlar bilan bir xil": "Цифры совпадают со слайдами презентации",
"soniya": "секунды",
"Datchik ishlaganidan operator jonli videoni ko'rgunicha": "От срабатывания датчика до живого видео у оператора",
"Shundan platformaning o'z ulushi. Qolgani qurilma, modem va odam": "Из них доля самой платформы. Остальное — устройство, модем и человек",
"KB": "КБ",
"Bitta hodisa markazga olib keladigan ma'lumot: kadr va JSON": "Данные, которые одно событие приносит в центр: кадр и JSON",
"qatlam": "слоёв",
"Qurilmadan ish joyigacha. Har qatlamning egasi boshqa": "От устройства до рабочего места. У каждого слоя свой владелец",

/* --- hodisaning yo'li --- */
"Vaqtlar Hikvision va Reolink batareyali kameralarining datasheet ko'rsatkichlari, 4G modemning PSM rejimidan chiqish vaqti va operator markazidagi o'lchovlardan olingan. Har qadam alohida ochiladi: nima ishlaydi, nima kechiktiradi, nima buzilishi mumkin.": "Значения взяты из даташитов батарейных камер Hikvision и Reolink, времени выхода 4G-модема из PSM и замеров в операторском центре. Каждый шаг открывается отдельно: что работает, что задерживает, что может сломаться.",
"Qurilma": "Устройство",
"PIR datchik odamni darvozadan 8 metrda ko'radi": "PIR-датчик видит человека в 8 метрах от ворот",
"Kamera uyquda: protsessor o'chgan, faqat piroelektrik sensor va soat ishlayapti. 4G modemli tashqi kamerada kutish sarfi": "Камера спит: процессор выключен, работают только пироэлектрический датчик и часы. У наружной камеры с 4G-модемом расход в ожидании",
 "mVt — Wi-Fi bilan hub'ga ulanadigan Argus sinfidagi kamerada to'rt barobar kam, chunki radioni hub ushlab turadi. Sensor": "мВт — у камеры класса Argus, подключённой к хабу по Wi-Fi, он вчетверо ниже, потому что радио держит хаб. Датчик на фоне",
"mVt. Sensor": "мВт. Датчик на фоне",
"°C fonda": "°C фиксирует смещение тёплого тела температурой",
"°C issiq jismning siljishini qayd etadi va uzilish signali beradi.": "°C и подаёт сигнал прерывания.",
"mVt kutish": "мВт в ожидании",
"m masofa": "м дальность",
"ko'rish burchagi": "угол обзора",
"Kamera uyg'onadi va birinchi kadrni SD kartaga yozadi": "Камера просыпается и пишет первый кадр на SD-карту",
"IR-filtr ko'chadi,": "Сдвигается ИК-фильтр, загорается подсветка",
"nm yoritgich yonadi, sensor ekspozitsiyani qorong'ilikka moslaydi. Yozuv obyektning o'zida boshlanadi: aloqa keyin uzilsa ham, dalil SD kartada qoladi.": "нм, сенсор подстраивает экспозицию под темноту. Запись начинается на самом объекте: даже если связь потом оборвётся, доказательство останется на SD-карте.",
"s uyg'onish": "с на пробуждение",
"Mbit/s asosiy oqim": "Мбит/с основной поток",
"kadr/s": "кадр/с",
"Kameraning o'zi «odam» deb ajratadi, ishonch": "Камера сама определяет класс «человек», уверенность",
"Tasnif kamera ichidagi neyroprotsessorda bajariladi: markazga hech narsa yuborilmaydi. Shamolda tebrangan shox, it va yorug'lik o'zgarishi shu yerda chiqarib tashlanadi — aks holda operator tunda o'nlab bo'sh signal oladi.": "Классификация идёт на нейропроцессоре внутри камеры: в центр ничего не отправляется. Качнувшаяся на ветру ветка, собака и перепад освещения отсеиваются здесь же — иначе оператор за ночь получит десятки пустых тревог.",
"Sinf:": "Класс:",
"odam": "человек",
"Ishonch": "Уверенность",
"Chegara": "Порог",
"Kanal": "Канал",
"Modem energiya tejash rejimidan chiqadi va tarmoqqa ulanadi": "Модем выходит из режима энергосбережения и подключается к сети",
"Bu zanjirdagi eng uzun texnik qadam. PSM dan chiqish, RRC sessiyasini tiklash va autentifikatsiya": "Самый длинный технический шаг в цепочке. Выход из PSM, восстановление RRC-сессии и аутентификация при сигнале",
"dBm signalda": "дБм занимают",
"soniya oladi. Modemni doim uyg'oq tutish mumkin, lekin u holda kunlik sarf": "секунды. Модем можно держать активным постоянно, но тогда суточный расход вырастет в",
"barobar oshadi.": "раза.",
"dBm": "дБм",
"dB": "дБ",
"TLS sessiyasi tiklanadi,": "Возобновляется TLS-сессия, отправляется",
"yuboriladi": "",
"Shlyuz bank CA imzolagan mijoz sertifikati bilan tanishtiriladi. Sessiya kaliti oldingi ulanishdan saqlangani uchun qisqartirilgan tiklash bajariladi:": "Шлюз предъявляет клиентский сертификат, подписанный CA банка. Ключ сессии сохранён с прошлого подключения, поэтому выполняется укороченное возобновление:",
"soniya. Javob": "секунды. Ответ",
"— hodisa navbatga tushdi, ammo hali ko'rilmadi.": "— событие принято в очередь, но ещё не рассмотрено.",
"bayt": "байт",
"Javob": "Ответ",
"Kalit kadr yuklanadi:": "Загружается ключевой кадр:",
"Kadr": "Кадр",
", sifat": ", качество",
". Zaif signalda yuklanish tezligi taxminan": ". При слабом сигнале скорость отдачи падает примерно до",
"Mbit/s ga tushadi. Video klip darrov yuborilmaydi: u SD kartada qoladi va operator so'raganda yoki tong otgach kelib tushadi.": "Мбит/с. Видеоклип сразу не уходит: он остаётся на SD-карте и приходит по запросу оператора или утром.",
"Klip talab bo'yicha": "Клип по запросу",
"SHA-256 imzosi bilan": "С хешем SHA-256",
"Adapter brend formatini yagona sxemaga o'giradi": "Адаптер переводит формат бренда в единую схему",
"deb yozgan hodisa yagona sxemada": "в единой схеме становится",
"bo'ladi, mahalliy vaqt UTC ga keltiriladi, brendga xos yigirmadan ortiq maydon tashlanadi. Shu joydan narida platformaning hech bir qismi kameraning kim ishlab chiqarganini bilmaydi.": ", местное время приводится к UTC, два десятка фирменных полей отбрасываются. Дальше этой точки ни одна часть платформы не знает, кто изготовил камеру.",
"Takror oynasi": "Окно повторов",
"daqiqa": "минут",
"Kalit:": "Ключ:",
"Yadro": "Ядро",
"Qoidalar xizmati hodisani voqeaga aylantiradi": "Сервис правил превращает событие в инцидент",
"Obyekt tungi rejimda": "Объект стоит на ночной охране в интервале",
"oralig'ida qo'riqda turadi, sinf «odam», ishonch chegaradan yuqori — demak bu tekshirishga arziydigan voqea. Tizim voqea yaratadi, unga": ", класс «человек», уверенность выше порога — значит, случай стоит проверки. Система создаёт инцидент, ставит на него",
"daqiqalik javob muddatini qo'yadi va navbatchini biriktiradi.": "минут на ответ и назначает дежурного.",
"Voqea": "Инцидент",
"Muddat": "Срок",
"Daraja:": "Уровень:",
"yuqori": "высокий",
"Ish joyi": "Рабочее место",
"Navbatchining telefonida xabarnoma yonadi": "На телефоне дежурного загорается уведомление",
"Xabarnomada kadr, obyekt nomi va ikki tugma bor: «Ko'rish» va «Yolg'on signal». Agar xabarnoma": "В уведомлении кадр, название объекта и две кнопки: «Смотреть» и «Ложная тревога». Если уведомление не открыли за",
"soniyada ochilmasa, tizim SMS yuboradi va smena boshlig'iga dublyaj qiladi.": "секунд, система отправляет SMS и дублирует начальнику смены.",
"s": "с",
"SMS zaxira": "SMS-резерв",
"Odam": "Человек",
"Navbatchi obyekt kartochkasini ochadi": "Дежурный открывает карточку объекта",
"Zanjirdagi eng uzun bo'lak — mana shu. Tungi smenada telefonni olish, ekranni ochish va kartochkani bosish o'rtacha": "Вот самая длинная часть цепочки. В ночную смену взять телефон, открыть экран и нажать на карточку — в среднем",
"soniya oladi. Texnikani yana ikki soniyaga tezlashtirishdan ko'ra, navbatchi jadvalini to'g'rilash ko'proq foyda beradi.": "секунды. Поправить график дежурств выгоднее, чем ускорить технику ещё на две секунды.",
"O'rtacha": "В среднем",
"Pilotda o'lchanadi": "Измеряется на пилоте",
"Jonli video ochiladi: media shlyuz kameraga endi ulanadi": "Открывается живое видео: медиашлюз только теперь подключается к камере",
"Kamera hodisadan keyin": "После события камера остаётся активной ещё",
"soniya uyg'oq turadi. Oyna 40 soniya bo'lganda navbatchi o'rtacha 24 soniyada ulgurardi, lekin 30 soniyada ochganida kamera allaqachon uxlagan bo'lardi va birinchi kadr 1,4 soniya kechikardi. Media shlyuz sub-oqimni oladi va brauzerga WebRTC bilan uzatadi: kechikish sekunddan kam; operator oynani yopsa, kamera yana uyquga ketadi.": "секунд. Будь окно 40 секунд, дежурный со своими средними 24 секундами успевал бы, но при открытии на 30-й секунде камера уже спит и первый кадр опаздывает на 1,4 секунды. Медиашлюз забирает субпоток и отдаёт в браузер по WebRTC: задержка меньше секунды; когда оператор закрывает окно, камера снова засыпает.",
"Birinchi kadr": "Первый кадр",
"kbit/s sub-oqim": "кбит/с субпоток",
"Sessiya": "Сессия",
"s tokeni": "с по токену",
"Navbatchi sirenani yoqadi va qo'riqlashga xabar beradi": "Дежурный включает сирену и сообщает охране",
"Ikki odam darvoza oldida — operator sirena va projektor buyrug'ini beradi. Buyruq": "Двое у ворот — оператор отдаёт команду на сирену и прожектор. Команда уходит с заголовком",
"bilan ketadi: tugma ikki marta bosilsa ham, sirena bir marta ishlaydi. Har buyruq jurnalga kim, qachon va qaysi obyektda deb yoziladi.": ": даже если кнопку нажали дважды, сирена сработает один раз. Каждая команда пишется в журнал: кто, когда и на каком объекте.",
"Jurnal o'zgarmas": "Журнал неизменяем",
"ertasi kuni": "на следующий день",
"Bank": "Банк",
"Hodisa obyekt kartochkasidagi yozuvga aylanadi": "Событие становится записью в карточке объекта",
"Tunda yozilgan klip tong otgach yuklanadi, voqea yopiladi, inspektorga joyida ko'rik topshirig'i tushadi. Ko'rik dalolatnomasi imzolangach, obyektning nazorat indeksi va keyingi ko'rik muddati qayta hisoblanadi. Shu yerdan boshlab bu — bankning hujjati, texnik signal emas.": "Записанный ночью клип загружается утром, инцидент закрывается, инспектор получает задание на выездной осмотр. После подписания акта пересчитываются индекс контроля объекта и срок следующего осмотра. С этого момента это документ банка, а не технический сигнал.",
"Klip": "Клип",
"MB": "МБ",
"Dalolatnoma": "Акт",
"Indeks qayta hisoblanadi": "Индекс пересчитывается",
"Vaqt qayerga ketadi": "Куда уходит время",
"soniya, kanal": "секунды, канал",
", platforma": ", платформа",
", qurilma": ", устройство",
"Qirq bir soniyaning yarmidan ko'pi navbatchining telefonni olishiga ketadi. Server tomonidagi normallashtirish, qoida va xabarnoma birgalikda roppa-rosa ikki soniya oladi; qolgan to'rt soniya — media shlyuz kameradan birinchi kadrni olguncha. Tezlashtirish kerak bo'lsa, birinchi navbatda modem rejimi va smena tartibi ko'riladi, kod emas.": "Больше половины из сорока одной секунды уходит на то, чтобы дежурный взял телефон. Нормализация, правила и уведомление на стороне сервера вместе занимают ровно две секунды; оставшиеся четыре — пока медиашлюз получит из камеры первый кадр. Если нужно ускоряться, сначала смотрят режим модема и организацию смен, а не код.",
"soniya · datchikdan jonli videogacha": "секунды · от датчика до живого видео",
"Nimasi kafolatlanmaydi": "Что не гарантируется",
"Bu vaqt signal yaxshi bo'lgan obyekt uchun": "Это время для объекта с хорошим сигналом",
"dBm dan past bo'lgan obyektda modemning ulanishi": "дБм подключение модема растягивается до",
"soniyagacha cho'ziladi, kadr esa": "секунд, а кадр загружается за",
"soniyada yuklanadi. Shuning uchun har obyektda signal montajdan oldin o'lchanadi va natija montaj varag'iga yoziladi. Pilotning vazifasi — shu vaqtlarni o'nta haqiqiy obyektda o'lchab, SLA ga aniq raqam qo'yish.": "секунд. Поэтому на каждом объекте сигнал измеряется до монтажа, а результат вносится в лист монтажа. Задача пилота — перемерить эти значения на десяти реальных объектах и поставить в SLA точную цифру.",
"daqiqa · javob muddati SLA da": "минут · срок ответа в SLA",

/* --- olti qatlam --- */
"Olti qatlam va ularning egalari": "Шесть слоёв и их владельцы",
"Tizim bitta mahsulot emas: oltita qatlam bir-biriga shartnoma orqali ulanadi. Qaysi qatlam buzilsa, kim tuzatishi shu jadvalda hal qilinadi. Sxemadagi har bir ustunni bosing.": "Система — не один продукт: шесть слоёв соединены между собой договорами. Кто чинит отказавший слой, определяется этой таблицей. Нажмите на любую колонку схемы.",
"QATLAM 1": "СЛОЙ 1",
"QATLAM 2": "СЛОЙ 2",
"QATLAM 3": "СЛОЙ 3",
"QATLAM 4": "СЛОЙ 4",
"QATLAM 5": "СЛОЙ 5",
"QATLAM 6": "СЛОЙ 6",
"Kamera, datchik,": "Камера, датчик,",
"domofon, qulf": "домофон, замок",
"Aniqlaydi, yozadi,": "Обнаруживает, пишет,",
"saqlaydi": "хранит",
"Egasi: yetkazuvchi": "Владелец: поставщик",
"Mahalliy": "Локальный",
"tugun": "узел",
"Shlyuz, NVR, router": "Шлюз, NVR, роутер",
"Yig'adi, navbatda": "Собирает, держит",
"ushlab turadi": "в очереди",
"Egasi: integrator": "Владелец: интегратор",
"Yopiq APN, VPN,": "Закрытый APN, VPN,",
"ikki SIM": "две SIM",
"Shifrlaydi, uzilsa": "Шифрует, при обрыве",
"boshqasiga o'tadi": "переходит на вторую",
"Egasi: operator": "Владелец: оператор связи",
"Brend tili → bitta": "Язык бренда → одна",
"sxema": "схема",
"O'giradi, takrorni": "Переводит, отсекает",
"tashlaydi": "повторы",
"Egasi: bank jamoasi": "Владелец: команда банка",
"Shina, reyestr,": "Шина, реестр,",
"media, buyruq": "медиа, команды",
"Qaror qabul qiladi,": "Принимает решения,",
"jurnal yuritadi": "ведёт журнал",
"Egasi: bank": "Владелец: банк",
"Panel, mobil ilova,": "Панель, мобильное",
"hisobot": "приложение, отчёты",
"Ko'rsatadi, buyruq": "Показывает, отдаёт",
"beradi": "команды",
"OBYEKTDA": "НА ОБЪЕКТЕ",
"BANK KONTURIDA": "В КОНТУРЕ БАНКА",
"Hodisa va telemetriya: doim yuqoriga": "События и телеметрия: всегда вверх",
"Buyruq va sozlama: doim pastga, jurnal bilan": "Команды и настройки: всегда вниз, с журналом",
"Video: faqat operator so'raganda, sessiya tokeni bilan": "Видео: только по запросу оператора, по сессионному токену",
"Har ustunni bosing: qatlam nimani bajaradi, nima buzilishi mumkin va shartnomada kimning javobgarligi turadi.": "Нажмите на колонку: что слой делает, что в нём ломается и чья это ответственность по договору.",
"Olti qatlam: qurilma, mahalliy tugun, kanal, adapter, yadro, ish joyi": "Шесть слоёв: устройство, локальный узел, канал, адаптер, ядро, рабочее место",
"Birinchi qatlam: qurilma": "Первый слой: устройство",
"Ikkinchi qatlam: mahalliy tugun": "Второй слой: локальный узел",
"Uchinchi qatlam: kanal": "Третий слой: канал",
"To'rtinchi qatlam: adapter": "Четвёртый слой: адаптер",
"Beshinchi qatlam: integratsiya yadrosi": "Пятый слой: интеграционное ядро",
"Oltinchi qatlam: ish joyi": "Шестой слой: рабочее место",
"Qatlam": "Слой",
"Ishlaydigan qism": "Что работает",
"Buzilganda belgisi": "Признак отказа",
"Kim tuzatadi": "Кто чинит",
"Tiklash muddati": "Срок восстановления",
"Aniqlash, joyida yozuv, batareya": "Обнаружение, запись на месте, батарея",
"Telemetriya kelmay qoldi yoki batareya": "Перестала приходить телеметрия или батарея ниже",
"dan past": "",
"Servis brigadasi": "Сервисная бригада",
"Yig'ish, navbat, VPN": "Сбор, очередь, VPN",
"chegaradan oshdi": "превысил порог",
"SIM, APN, VPN tunneli": "SIM, APN, VPN-туннель",
"Ikkala SIM ham ulanmayapti": "Не подключаются обе SIM",
"Aloqa operatori": "Оператор связи",
"Normallashtirish, takrorni tashlash": "Нормализация, отсечение повторов",
"Navbat o'smoqda, hodisa sxemasi rad etilyapti": "Растёт очередь, события отклоняются по схеме",
"Bank jamoasi": "Команда банка",
"Shina, baza, media, buyruq": "Шина, база, медиа, команды",
"Grafana ogohlantirishi, navbat": "Предупреждение Grafana, очередь больше",
"dan oshdi": "",
"Panel, mobil ilova, hisobot": "Панель, мобильное приложение, отчёты",
"Foydalanuvchi shikoyati, xato jurnali": "Жалоба пользователя, журнал ошибок",
"— obyektga chiqmasdan hal qilinadigan nosozlik uchun. Joyiga borish talab qilinsa, chekka tumanlardagi obyektga yetib borish": "— для отказа, который решается без выезда на объект. Если выезд нужен, дорога до объекта в отдалённом районе занимает до",
"ish kunigacha cho'ziladi va bu shartnomada alohida yoziladi.": "рабочих дней, и это отдельно оговаривается в договоре."

});

/* --- hodisa sxemasi, adapterlar, buzilishlar, bir kunlik hisob --- */
window.MKB_LUGAT = Object.assign(window.MKB_LUGAT || {}, {

"Yagona hodisa sxemasi: yigirma yildan keyin ham o'qiladigan yozuv": "Единая схема события: запись, которую прочтут и через двадцать лет",
"Hodisa — tizimdagi eng muhim yozuv. U sud ishida dalil, zaxira hisobida asos, servis shartnomasida ko'rsatkich bo'lib xizmat qiladi. Shuning uchun sxema brendga bog'lanmaydi va faqat qo'shimcha maydon bilan kengayadi.": "Событие — самая важная запись в системе. Оно служит доказательством в суде, основанием в расчёте резерва и показателем в сервисном договоре. Поэтому схема не привязана к бренду и расширяется только добавлением полей.",
"Yagona hodisa ·": "Единое событие ·",
"Namuna yozuv. Haqiqiy obyekt raqamlari va nomlari taqdimotda ishlatilmaydi.": "Образец записи. Настоящие номера и названия объектов в презентации не используются.",
"Maydon": "Поле",
"Kim to'ldiradi": "Кто заполняет",
"Bo'lmasa nima bo'ladi": "Что будет, если его нет",
"Yozuv rad etiladi: versiyasiz hodisa qabul qilinmaydi": "Запись отклоняется: событие без версии не принимается",
"Qurilma yoki adapter": "Устройство или адаптер",
"Takror xabar ikkinchi voqea yaratadi": "Повторное сообщение создаст второй инцидент",
"Reyestr, qurilmani ulashda": "Реестр, при подключении устройства",
"Hodisa kimning aktivi ekani noma'lum qoladi": "Останется неизвестным, к какому активу относится событие",
"Qurilma, NTP bo'yicha": "Устройство, по NTP",
"Tartib buziladi, dalil sifatida zaiflashadi": "Нарушается порядок, запись слабеет как доказательство",
"Yolg'on signal filtri ishlamaydi": "Не работает фильтр ложных тревог",
"Adapter, yuklagandan keyin": "Адаптер, после загрузки",
"Operator ko'rmasdan qaror qabul qiladi": "Оператор принимает решение, не видя картинки",
"Shlyuz, yozish paytida": "Шлюз, в момент записи",
"Fayl o'zgartirilmaganini isbotlab bo'lmaydi": "Нельзя доказать, что файл не изменён",
"Nosozlik oldindan ko'rinmaydi, servis kech chiqadi": "Отказ не виден заранее, сервис выезжает поздно",
"Versiya": "Версия",
"Sxema faqat qo'shimcha bilan o'zgaradi": "Схема меняется только добавлением",
"Yangi maydon qo'shish mumkin, eskisini olib tashlash yoki ma'nosini o'zgartirish mumkin emas. Buzuvchi o'zgarish kerak bo'lsa,": "Новое поле добавить можно, старое убрать или переосмыслить — нельзя. Если нужно ломающее изменение, выходит",
"chiqadi va ikki versiya kamida olti oy yonma-yon ishlaydi.": ", и две версии работают параллельно минимум полгода.",
"Takror": "Повтор",
"Bitta hodisa ikki marta kelishi normal holat": "Одно событие дважды — это норма",
"Aloqa uzilib-ulangan shlyuz xabarni qayta yuboradi. Platforma": "Шлюз, у которого рвалась связь, отправляет сообщение повторно. Платформа отсекает повтор по",
"bo'yicha takrorni tashlaydi, lekin uni jurnalda qoldiradi: takror soni kanal sifatining ko'rsatkichi.": ", но оставляет его в журнале: число повторов — показатель качества канала.",
"Dalil": "Доказательство",
"Kadr va klip o'zgartirilmaganini xesh isbotlaydi": "Неизменность кадра и клипа доказывает хеш",
"Fayl obyektda yozilganda SHA-256 hisoblanadi va hodisa bilan birga yuboriladi. Markazda yozilgan fayl xeshi qayta hisoblanib solishtiriladi; nomuvofiqlik bo'lsa, fayl «tekshirilmagan» belgisini oladi.": "SHA-256 считается в момент записи файла на объекте и отправляется вместе с событием. В центре хеш пересчитывается и сверяется; при расхождении файл получает пометку «не проверен».",

"Hikvision hodisani XML oqimida, Ajax — SIA DC-09 kodida, Milesight shlyuzi MQTT mavzusida yuboradi. Uchalasi ham yadroga bir xil ko'rinishda kirib kelishi kerak. Adapterning butun ishi shunda.": "Hikvision отдаёт событие потоком XML, Ajax — кодом SIA DC-09, шлюз Milesight — топиком MQTT. В ядро все три должны прийти в одном виде. В этом вся работа адаптера.",
"Hodisa qayerdan olinadi": "Откуда берётся событие",
"Brend nomi": "Название у бренда",
"Yagona sxemada": "В единой схеме",
"Ishlab chiqish": "Разработка",
", doimiy HTTP oqim": ", постоянный HTTP-поток",
", obuna": ", подписка",
"Home Hub, HTTP API va ONVIF": "Home Hub, HTTP API и ONVIF",
"Markaziy stansiya kanali,": "Канал пультовой станции,",
"(burglary alarm)": "(burglary alarm)",
"LoRaWAN shlyuzi, MQTT mavzusi": "Шлюз LoRaWAN, топик MQTT",
"Profile S va T,": "Profile S и T,",
"obunasi": "подписка",
"Qadam 1": "Шаг 1",
"Qadam 2": "Шаг 2",
"Qadam 3": "Шаг 3",
"Qadam 4": "Шаг 4",
"Qabul": "Приём",
"Adapter kameraga o'zi ulanadi yoki obunani ochib qo'yadi. Ulanish uzilsa,": "Адаптер сам подключается к камере или открывает подписку. При обрыве повторные попытки идут с задержкой от",
"soniyadan boshlab ikki barobar oshib boruvchi kechikish bilan qayta uriniladi.": "секунд с удвоением.",
"Normallashtirish": "Нормализация",
"Brend maydonlari yagona sxemaga solinadi, vaqt UTC ga keltiriladi, qurilma soati": "Поля бренда укладываются в единую схему, время приводится к UTC, а если часы устройства разошлись больше чем на",
"daqiqadan ko'p adashgan bo'lsa yozuvga belgi qo'yiladi.": "минуты, запись получает пометку.",
"Takrorni tashlash": "Отсечение повторов",
"Bitta kameradan": "События одного типа с одной камеры, пришедшие за",
"daqiqa ichida kelgan bir xil turdagi hodisalar bitta voqeaga yig'iladi. Hisoblagich saqlanadi: «": "минут, склеиваются в один инцидент. Счётчик сохраняется: «повторено",
"marta takrorlandi».": "раз».",
"Shinaga uzatish": "Передача в шину",
"Yozuv": "Запись",
"kaliti bilan navbatga qo'yiladi. Iste'molchi to'xtab qolsa ham, hodisa navbatda kutadi va yo'qolmaydi.": "ставится в очередь с ключом. Даже если потребитель остановился, событие ждёт в очереди и не теряется.",
"Yangi brendni ulash": "Подключение нового бренда",
"Ish hajmini hujjatning sifati belgilaydi": "Объём работы задаёт качество документации",
"Ochiq ONVIF yoki hujjatlashtirilgan HTTP API bo'lsa, adapter ikki-uch haftada tayyor bo'ladi. Vaqtning yarmi kamerani to'rtta buzuq holatga solib sinashga ketadi: aloqa uzilgan, batareya past, soat adashgan, ikkita hodisa bir vaqtda kelgan.": "Если есть открытый ONVIF или документированный HTTP API, адаптер готов за две-три недели. Половина времени уходит на прогон камеры через четыре нештатных состояния: связь оборвана, батарея на нуле, часы ушли, два события пришли одновременно.",
"hafta · bitta brend uchun": "недели · на один бренд",
"Qabul sharti": "Условие приёмки",
"Adapter pilotda bir hafta xatosiz ishlashi kerak": "Адаптер должен неделю отработать на пилоте без ошибок",
"Qabul uch bosqichda: yozib olingan hodisalar to'plamida shartnoma testlari, sun'iy uzilish bilan sinov, keyin o'nta obyektda bir haftalik ish. Uchta ko'rsatkich o'lchanadi: yo'qolgan hodisa, takror va o'rtacha kechikish.": "Приёмка в три этапа: контрактные тесты на наборе записанных событий, испытание с искусственным обрывом, затем неделя работы на десяти объектах. Измеряются три показателя: потерянные события, повторы и средняя задержка.",
"yo'qolgan hodisa · qabul chegarasi": "потерянных событий · порог приёмки",

"Uchta buzilish: aloqa, batareya, yolg'on signal": "Три отказа: связь, батарея, ложная тревога",
"Bu uchtasi 267 obyektda har oy takrorlanadi. Tizimning qiymati ular bo'lmasligida emas — ular sezilmay qolmasligida va har biriga oldindan javob tayyorligida.": "На 267 объектах эти три повторяются каждый месяц. Ценность системы не в том, что их не будет, а в том, что они не останутся незамеченными и на каждый заранее есть ответ.",
"Buzilish 1": "Отказ 1",
"Buzilish 2": "Отказ 2",
"Buzilish 3": "Отказ 3",
"Aloqa uzildi": "Связь оборвалась",
"Qanday bilinadi.": "Как узнаём.",
"Elektrli tugun": "Узел с электропитанием шлёт импульс раз в",
"soniyada, batareyali kamera": "секунд, батарейная камера — раз в",
"daqiqada puls yuboradi. Uchta puls kelmasa, qurilma «aloqada emas» holatiga o'tadi: birinchisida": "минут. Если не пришли три импульса, устройство переходит в состояние «нет связи»: в первом случае через",
", ikkinchisida": ", во втором через",
"daqiqada.": "минут.",
"Tizim nima qiladi.": "Что делает система.",
"Shlyuz hodisalarni o'z navbatiga yozadi va ikkinchi SIM ga o'tadi. Kamera esa yozishni davom ettiradi: dalil obyektda qoladi.": "Шлюз складывает события в свою очередь и переходит на вторую SIM. Камера продолжает писать: доказательство остаётся на объекте.",
"Nima oldini oladi.": "Что это предотвращает.",
"Ikki operator SIM, tashqi antenna va aloqa sifatini montajdan oldin o'lchash.": "Две SIM разных операторов, внешняя антенна и замер качества связи до монтажа.",
"daqiqa · aloqasizlikni e'lon qilish": "минут · объявление потери связи",
"Batareya o'ldi": "Батарея села",
"Zaryad darajasi har o'lchovda yuboriladi.": "Уровень заряда приходит с каждым замером. На",
"da servis arizasi ochiladi,": "открывается сервисная заявка, на",
"da obyektning nazorat indeksi tushadi.": "снижается индекс контроля объекта.",
"Qurilma tejash rejimiga o'tadi: yozuv qoladi, jonli video o'chadi. Operator bu obyektda videoni so'ray olmasligini ekranda ko'radi.": "Устройство переходит в режим экономии: запись остаётся, живое видео отключается. Оператор видит на экране, что запросить видео с этого объекта нельзя.",
"Dekabr quyoshiga qarab hisoblangan panel va akkumulyator, past haroratli BMS, kuzda o'tkaziladigan profilaktika.": "Панель и аккумулятор, рассчитанные по декабрьскому солнцу, BMS с низкотемпературной защитой и осенняя профилактика.",
"zaryad · servis arizasi ochiladi": "заряда · открывается сервисная заявка",
"Yolg'on signal keldi": "Пришла ложная тревога",
"Operator xabarnomada «Yolg'on signal» tugmasini bosadi. Sabab ro'yxatdan tanlanadi: hayvon, shamol, yorug'lik, yomg'ir, texnika.": "Оператор нажимает в уведомлении «Ложная тревога». Причина выбирается из списка: животное, ветер, свет, дождь, техника.",
"Voqea yopiladi, kadr sabab bilan saqlanadi. Bitta kamera oyiga to'rtdan ko'p yolg'on signal bersa, u sozlash ro'yxatiga tushadi.": "Инцидент закрывается, кадр сохраняется вместе с причиной. Камера, давшая больше четырёх ложных тревог за месяц, попадает в список на настройку.",
"Kamerani to'g'ri burchakka qo'yish, sezish zonasini kesish, sinfga qarab filtr va ishonch chegarasi.": "Правильный угол установки камеры, обрезка зоны обнаружения, фильтр по классу и порог уверенности.",
"yolg'on signal · obyektga oyiga": "ложных тревог · на объект в месяц",
"Eng xavfli holat — buzilish emas, sukut.": "Опаснее отказа — тишина.",
"Ikki kun hech narsa yubormagan kamera «tinch obyekt» kabi ko'rinishi mumkin. Shuning uchun nazorat hodisaga emas, pulsga quriladi: signal yo'qligi ham voqea hisoblanadi va o'sha": "Камера, не приславшая ничего двое суток, выглядит как «спокойный объект». Поэтому контроль строится не на событиях, а на импульсах: отсутствие сигнала тоже считается инцидентом и попадает к дежурному с тем же сроком в",
"daqiqalik muddat bilan navbatchiga tushadi.": "минут.",

"Bir obyektning bir kuni: trafik, energiya, yozuv": "Сутки одного объекта: трафик, энергия, записи",
"Quyidagi hisob bitta 4G kamera va bitta eshik datchigi o'rnatilgan ombor uchun. Raqamlar dekabr kuni bo'yicha olingan: kun qisqa, harorat past, hodisa kam.": "Расчёт ниже — для склада с одной 4G-камерой и одним датчиком двери. Цифры взяты по декабрьским суткам: день короткий, температура низкая, событий мало.",
"Trafik": "Трафик",
"Kuniga": "В сутки",
"Hodisa kadrlari": "Кадры событий —",
"MB, operator ochgan yarim daqiqalik video": "МБ, полминуты видео, открытого оператором, —",
"MB, haftada bir marta so'raladigan klip va": "МБ, клип по запросу раз в неделю и",
"ta puls. Oyiga": "импульсов. В месяц",
"GB — eng arzon M2M tarifi ham bemalol qoplaydi.": "ГБ — это покрывает даже самый дешёвый M2M-тариф.",
"GB · oyiga, bitta obyekt": "ГБ · в месяц на объект",
"Energiya": "Энергия",
"Vt·soat": "Вт·ч",
"Kutish rejimi sutkaga": "Режим ожидания за сутки —",
"Vt·soat,": "Вт·ч,",
"ta uyg'onish": "пробуждений —",
", puls va telemetriya": ", импульсы и телеметрия —",
", jonli video": ", живое видео —",
". Panel va akkumulyator o'lchami esa quyoshsiz kunlar ketma-ketligidan hisoblanadi.": ". А размер панели и аккумулятора считается от числа пасмурных суток подряд.",
"Vt·soat · dekabr kuni": "Вт·ч · декабрьские сутки",
"qator": "строк",
"hodisa,": "событий,",
"hodisa va": "событий и",
 "telemetriya o'lchovi; operator amallari audit jurnaliga alohida yoziladi. Puls bazaga tushmaydi — u faqat qurilmaning holat maydonini yangilaydi. Yozilganda 267 obyektda kuniga bir yarim milliondan ortiq keraksiz qator to'planardi.": "замеров телеметрии; действия оператора пишутся отдельно в журнал аудита. Импульс в базу не попадает — он лишь обновляет поле состояния устройства. Если бы он писался, на 267 объектах за сутки набегало бы больше полутора миллионов ненужных строк.",
"kun · dalil saqlash muddati": "дней · срок хранения доказательств",
"Shuning uchun tizim doimiy keng kanalsiz ham ishlaydi.": "Поэтому система работает и без постоянного широкого канала.",
"Markazga video emas, hodisa va kadr boradi. Bitta obyekt oyiga bir SIM tarifining kichik qismini ishlatadi, video esa faqat operator obyektni ochgan soniyalarda oqadi.": "В центр идёт не видео, а событие и кадр. Один объект расходует за месяц малую часть SIM-тарифа, а видео течёт только те секунды, пока оператор держит объект открытым.",

"Davomi": "Продолжение",
"Chuqur sahifa": "Подробная страница",
"Slayd": "Слайд",
"Ekranlar, rollar va o'sish": "Экраны, роли и рост",
"Kim nima ko'radi, nazorat indeksi qanday qayta hisoblanadi, 10 dan 1 000 obyektgacha": "Кто что видит, как пересчитывается индекс контроля, от 10 до 1 000 объектов",
"API shartnomasi": "Контракт API",
"REST, webhook va MQTT: brend har xil, API bitta": "REST, webhook и MQTT: брендов много, API один",
"Barqarorlik": "Устойчивость",
"Internet uzilsa ham nazorat to'xtamaydi: oltita tamoyil": "Даже при обрыве интернета контроль не прекращается: шесть принципов",
"O'nta yechim": "Десять решений",
"Qaysi obyektga qaysi komplekt mos keladi": "Какому объекту подходит какой комплект",
"MKBANK · Aktivlar nazorati dasturi ·": "MKBANK · Программа контроля активов ·",
"Ichki foydalanish uchun": "Для внутреннего пользования",
"Raqamlar taqdimot slaydlari bilan solishtirilgan": "Цифры сверены со слайдами презентации",
"Hodisa yo'li va olti qatlam": "Путь события и шесть слоёв",
"Dekabr kechasidagi signal soniyama-soniya: qurilmadan operator ekranigacha": "Декабрьский ночной сигнал посекундно: от устройства до экрана оператора",
"Masshtab": "Масштаб",
"To'qqizta komponent va 1 000 obyektdagi hisob": "Девять компонентов и расчёт на 1 000 объектов",
"Kirish nazorati": "Контроль доступа",
"Video → qaror → rele → jurnal": "Видео → решение → реле → журнал",
"Yo'l xaritasi": "Дорожная карта",
"267 obyekt 9 oyda, har yangi aktiv 10 kunda": "267 объектов за 9 месяцев, каждый новый актив за 10 дней",
"Ekran suratlari namoyish ma'lumotida olingan": "Снимки экранов сделаны на демонстрационных данных"

});

/* --- tizim-boshqaruv: ekranlar, rollar, indeks, masshtab, xavfsizlik --- */
window.MKB_LUGAT = Object.assign(window.MKB_LUGAT || {}, {

"Boshqaruv · chuqur sahifa": "Управление · подробная страница",
"Signal keldi. Endi u kimning ish kuniga tushadi": "Сигнал пришёл. Теперь он попадает в чей-то рабочий день",
"Kamera qo'yish oson qism. Qiyin qismi — kelgan ma'lumotni har kuni kimdir ko'rishi, unga javob berishi va u bankning hisobiga to'g'ri tushishi. Bu sahifada ekranlar, rollar, nazorat indeksining arifmetikasi va platformaning o'sish yo'li yozilgan.": "Поставить камеру — простая часть. Трудная в том, чтобы кто-то каждый день смотрел пришедшие данные, отвечал на них и чтобы они верно легли в учёт банка. На этой странице — экраны, роли, арифметика индекса контроля и путь роста платформы.",
"Har blok bosiladi: qoida va hisob shu yerda ochiladi": "Любой блок кликается: правило и расчёт открываются здесь же",
"tekshiruv": "проверок",
"Nazorat indeksi shulardan yig'iladi, qurilmalar ulushi —": "Индекс контроля складывается из них, доля устройств —",
"ball": "баллов",
"rol": "ролей",
"Bitta obyekt kartochkasini yetti xil odam boshqa maqsadda ochadi": "Одну карточку объекта семь разных людей открывают с разными целями",
"virtual mashina": "виртуальных машины",
"obyekt uchun. Pilot bitta serverda ishlaydi": "объектов. Пилот работает на одном сервере",
"bayt": "байт",
"Bank konturidan tashqariga chiqadigan kadr va klip": "Кадров и клипов уходит за контур банка",

"Uchta ekran: bugun ishlab turgan qism": "Три экрана: часть, работающая уже сегодня",
"Reyestr, obyekt kartochkasi va boshqaruv paneli allaqachon bitta bazada ishlayapti. Qurilmalar ulangach, ularga kamera bloki, oxirgi kadr va hodisalar tasmasi qo'shiladi — yangi tizim qurilmaydi.": "Реестр, карточка объекта и панель управления уже работают на одной базе. После подключения устройств в них добавятся блок камер, последний кадр и лента событий — новую систему строить не нужно.",
"Namuna ma'lumot": "Демонстрационные данные",
"Boshqaruv paneli · rahbariyat va obyekt menejeri uchun": "Панель управления · для правления и менеджера объекта",
"Balans va zaxira bitta ekranda, qarorlar navbati bir bosishda tasdiqlanadi, 12 oylik sanoq aktiv umidsiz toifaga o'tishidan oldin ogohlantiradi. Qurilmalar ulangach shu yerga «aloqada emas» obyektlar hisobi chiqadi.": "Баланс и резерв на одном экране, очередь решений утверждается одним нажатием, счётчик 12 месяцев предупреждает до перехода актива в безнадёжную категорию. После подключения устройств сюда выйдет счётчик объектов «нет связи».",
"Obyektlar reyestri": "Реестр объектов",
"Boshqaruv paneli": "Панель управления",
"Balansdagi har bir aktiv: surat, qiymat, bosqich, hudud va nazorat indeksi. Montaj marshrutini shu yerdan tuziladi — xaritada yonma-yon turgan obyektlar bitta brigadaga beriladi.": "Каждый актив на балансе: фото, стоимость, этап, регион и индекс контроля. Отсюда строится маршрут монтажа — стоящие рядом на карте объекты отдаются одной бригаде.",
"Obyekt kartochkasi": "Карточка объекта",
"Hujjat, ko'rik, xarajat, sug'urta va tarix bitta sahifada. Tungi hodisa ertalab shu kartochkaning «Ko'riklar» va «Tarix» bo'limida hujjat bo'lib turadi.": "Документы, осмотры, расходы, страхование и история на одной странице. Утром ночное происшествие лежит здесь документом — в разделах «Осмотры» и «История».",
"Ekranlarni tirik holda ochish uchun taqdimotdagi": "Чтобы открыть экраны вживую, используется ссылка",
"«Tizimni ochish»": "«Открыть систему»",
"havolasi ishlatiladi: u namoyish hisobi bilan kiradi va haqiqiy bank ma'lumotini ko'rsatmaydi.": "в презентации: она входит под демонстрационной учётной записью и настоящих данных банка не показывает.",

"Kim nima qiladi va kim nimani ko'rmaydi": "Кто что делает и кто чего не видит",
"Rol bank AD guruhidan olinadi: tizimda alohida parol yaratilmaydi. Xodim boshqa bo'limga o'tsa, huquqi AD da o'zgaradi va ertasiga tizimda ham o'zgaradi.": "Роль берётся из группы AD банка: отдельный пароль в системе не заводится. Перешёл сотрудник в другое подразделение — права меняются в AD, и на следующий день они меняются в системе.",
"Rol": "Роль",
"Nimani ochadi": "Что открывает",
"Nima qila oladi": "Что может",
"Nima qila olmaydi": "Чего не может",
"Nima bilan o'lchanadi": "Чем измеряется",
"Rahbariyat": "Правление",
"Boshqaruv paneli, oylik hisobot": "Панель управления, месячный отчёт",
"Qarorni tasdiqlash, limitni o'zgartirish": "Утвердить решение, изменить лимит",
"Eshik ochish, yozuvni o'chirish": "Открыть дверь, удалить запись",
"Zaxira va realizatsiya rejasi": "Резерв и план реализации",
"Obyekt menejeri": "Менеджер объекта",
"Reyestr, obyekt kartochkasi": "Реестр, карточка объекта",
"Servis arizasi, xarajat, montaj topshirig'i": "Сервисная заявка, расход, задание на монтаж",
"Baholash hisobotini o'zgartirish": "Изменить отчёт об оценке",
"Nazorat indeksi va muddatlar": "Индекс контроля и сроки",
"Ko'rik va xavfsizlik inspektori": "Инспектор по осмотрам и безопасности",
"Ko'rik rejasi, hodisalar": "План осмотров, события",
"Ko'rik dalolatnomasi, masofaviy ko'rik": "Акт осмотра, дистанционный осмотр",
"Obyektni balansdan chiqarish": "Списать объект с баланса",
"Muddati o'tgan ko'riklar soni": "Число просроченных осмотров",
"Xavfsizlik xizmati": "Служба безопасности",
"Hodisalar navbati, jonli video": "Очередь инцидентов, живое видео",
"Sirena, eshik, qo'riqlashga xabar": "Сирена, дверь, вызов охраны",
"Obyekt qiymatini ko'rish": "Видеть стоимость объекта",
"Javob vaqti va yolg'on signal": "Время ответа и ложные тревоги",
"Buxgalteriya va risk": "Бухгалтерия и риск",
"Zaxira, xarajat, MB hisoboti": "Резерв, расходы, отчёт для ЦБ",
"Toifani belgilash, hisobotni yopish": "Установить категорию, закрыть отчёт",
"Qurilmaga buyruq berish": "Отдать команду устройству",
"Zaxira aniqligi va hisobot muddati": "Точность резерва и срок отчётности",
"Realizatsiya mutaxassisi": "Специалист по реализации",
"Lotlar, e'lonlar, tashriflar": "Лоты, объявления, визиты",
"E'longa kadr qo'yish, tashrif belgilash": "Поставить кадр в объявление, назначить визит",
"Odam tushgan yozuvni e'longa qo'yish": "Поставить в объявление запись с людьми",
"E'londan shartnomagacha kun": "Дней от объявления до договора",
"Administrator": "Администратор",
"Qurilmalar, sertifikatlar, jurnal": "Устройства, сертификаты, журнал",
"Qurilma ulash, rol berish, adapter sozlash": "Подключить устройство, выдать роль, настроить адаптер",
"Audit jurnalini tahrirlash": "Редактировать журнал аудита",
"Aloqada bo'lish foizi": "Процент времени на связи",
"Tungi hodisa": "Ночное происшествие",
"Soat 03:12 dagi signal kimga boradi": "Кому уходит сигнал в 03:12",
"Tungi vaqtda faqat navbatchi xavfsizlik xodimiga. Obyekt menejeri va inspektor ertalabki ro'yxatda ko'radi, rahbariyat esa oylik hisobotda faqat jamlangan raqamni oladi. Bitta hodisa yetti kishini uyg'otmaydi.": "Ночью — только дежурному сотруднику охраны. Менеджер объекта и инспектор увидят его в утреннем списке, правление получит в месячном отчёте лишь сводную цифру. Одно событие не будит семерых.",
"odam · tunda xabar oladi": "человек · получает уведомление ночью",
"Jurnal": "Журнал",
"Har bir ko'rish va har bir buyruq yoziladi": "Каждый просмотр и каждая команда записываются",
"Jonli videoni kim ochgani, qaysi obyektda va necha soniya turgani jurnalga tushadi. Eshik buyrug'i, sirena, arxivdan kadr olish ham shunday. Jurnal tahrirlanmaydi: audit uchun ham, xodimni asossiz ayblashdan himoya qilish uchun ham.": "Кто открыл живое видео, по какому объекту и сколько секунд смотрел — попадает в журнал. Так же фиксируются команда на дверь, сирена и выгрузка кадра из архива. Журнал не редактируется: и ради аудита, и ради защиты сотрудника от необоснованного обвинения.",
"yil · jurnalni saqlash muddati": "лет · срок хранения журнала",

"Nazorat indeksi: qurilma qo'yish bir necha ballni qanday ko'taradi": "Индекс контроля: на сколько баллов его поднимает установка устройств",
"Indeks 0 dan 100 gacha ball, beshta tekshiruvdan yig'iladi va hech qayerda saqlanmaydi — har ochilganda joriy ma'lumotdan qayta hisoblanadi. Shuning uchun uni «yaxshilab qo'yib» bo'lmaydi: faqat haqiqiy hujjat, polis yoki ishlayotgan qurilma ko'taradi.": "Индекс — балл от 0 до 100, складывается из пяти проверок и нигде не хранится: при каждом открытии он пересчитывается из текущих данных. Поэтому его нельзя «подправить»: поднимают только настоящий документ, полис или работающее устройство.",
"Tekshiruv": "Проверка",
"Og'irligi": "Вес",
"Me'yor": "Норма",
"Namunadagi holat": "Состояние в примере",
"Ulush": "Доля",
"Ball": "Балл",
"Ko'rik dolzarbligi": "Актуальность осмотра",
"Binoga har": "Для здания каждые",
"kunda": "дней",
"Oxirgi ko'rik": "Последний осмотр",
"kun oldin": "дней назад",
"Sug'urta himoyasi": "Страховая защита",
"Summa bahodan kam emas": "Сумма не ниже оценки",
"Polis amalda,": "Полис действует, осталось",
"kun qoldi": "дней",
"Baho dolzarbligi": "Актуальность оценки",
"Har": "Каждые",
"oyda": "месяцев",
"Baholangan": "Оценён",
"Hujjatlar to'liqligi": "Полнота документов",
"Bosqichga ko'ra majburiy ro'yxat": "Обязательный список по этапу",
"tadan": ", из них",
"tasi bor": "в наличии",
"Qo'riqlash va qurilmalar": "Охрана и устройства",
"Shartnoma va onlayn qurilmalar": "Договор и устройства на связи",
"Shartnoma yo'q;": "Договора нет;",
"qurilma onlayn": "устройства на связи",
"Hisob": "Расчёт",
"Namunadagi obyekt:": "Объект из примера:",
"Beshta ball qo'shiladi:": "Пять баллов складываются:",
". Ekranda butun songa yaxlitlanadi. Eng ko'p ball yo'qotilgan joy — ko'rik muddati va qurilmalar.": ". На экране округляется до целого. Больше всего баллов потеряно на сроке осмотра и устройствах.",
"ball · yaxlitlangach 70": "балла · после округления 70",
"Servis chiqqandan keyin": "После выезда сервиса",
"To'rtinchi qurilma tiklandi:": "Четвёртое устройство восстановлено:",
"Aloqadagi qurilmalar ulushi": "Доля устройств на связи растёт с",
"dan": "до",
"ga, batareyasi joyidagilar ulushi": ", доля с нормальным зарядом — с",
"ga ko'tariladi. Himoya bandi": ". Пункт защиты поднимается с",
"ballga chiqadi.": "баллов.",
"ball · bir servis tashrifidan keyin": "балла · после одного выезда сервиса",
"Qurilmalar yolg'iz": "Одни устройства не дают больше",
"balldan oshmaydi": "балла",
"Himoya bandining yarmi qo'riqlash shartnomasiga tegishli. Qurilma qanchalik yaxshi ishlamasin, shartnomasiz bu band to'liq yopilmaydi. Bu ataylab shunday: kamera signal beradi, javobni esa odam beradi.": "Половина пункта защиты отведена договору охраны. Как бы хорошо ни работали устройства, без договора этот пункт полностью не закрывается. Так сделано намеренно: камера подаёт сигнал, а отвечает человек.",
"ball · shartnoma va qurilma birga": "баллов · договор и устройства вместе",
"Nimadan boshlanadi": "С чего начинается",
"Oshib ketsa": "Если превышен",
"Ko'rik davri": "Периодичность осмотра",
"Oxirgi imzolangan dalolatnoma sanasi": "Дата последнего подписанного акта",
"kun": "дней",
"ga, ikki baravar oshsa": ", а при превышении вдвое — до",
"ga tushadi": "",
"Baholash muddati": "Срок оценки",
"Hisobot sanasi": "Дата отчёта",
"oy": "месяцев",
"kun qolganda ogohlantiriladi, keyin ball tushadi": "дней до конца — предупреждение, затем балл снижается",
"Sug'urta polisi": "Страховой полис",
"Polis tugash sanasi": "Дата окончания полиса",
"Muddati o'tsa,": "Если срок истёк, из",
"balldan": "баллов остаётся",
"tasi qoladi": "",
"Balansda turish": "Нахождение на балансе",
"Balansga qabul sanasi": "Дата приёма на баланс",
"Undiruv mulki umidsiz toifaga o'tadi: zaxira": "Имущество от взыскания уходит в безнадёжную категорию: резерв",
"Hodisaga javob": "Ответ на инцидент",
"Voqea yaratilgan soniya": "Секунда создания инцидента",
"Smena boshlig'iga dublyaj, SLA hisobotiga tushadi": "Дублирование начальнику смены, запись в отчёт по SLA",
"Ko'rik davri va baholash muddati": "Периодичность осмотра и срок оценки",
"— bankning ichki me'yori, ular sozlamalarda o'zgartiriladi. Zaxira muddatlari esa Markaziy bank hujjatlaridan keladi va tizimda o'zgartirilmaydi.": "— внутренняя норма банка, они меняются в настройках. А сроки по резерву приходят из документов Центрального банка и в системе не изменяются.",

"10 dan 1 000 obyektgacha: nima o'zgaradi, nima o'zgarmaydi": "От 10 до 1 000 объектов: что меняется, а что нет",
"Arxitektura uch marta qayta yozilmaydi. Pilot bitta serverda ishlaydi, 267 obyekt oltita virtual mashinaga sig'adi, ming obyektda esa faqat nusxa soni va disk hajmi ortadi. Eng tez o'sadigan narsa — kadr va klip arxivi.": "Архитектуру не придётся переписывать трижды. Пилот работает на одном сервере, 267 объектов помещаются в шесть виртуальных машин, а на тысяче растут только число экземпляров и объём диска. Быстрее всего растёт архив кадров и клипов.",
"Ko'rsatkich": "Показатель",
"10 obyekt · pilot": "10 объектов · пилот",
"300 obyekt · balans": "300 объектов · баланс",
"1 000 obyekt": "1 000 объектов",
"Qurilmalar": "Устройства",
"Puls, soniyasiga": "Импульсов в секунду",
"Hodisa, kuniga": "Событий в сутки",
"Jonli video, cho'qqida": "Живое видео на пике",
"Kadr va klip,": "Кадры и клипы,",
"Markaz kanali": "Канал центра",
"Serverlar": "Серверы",
"Navbatchi smenasi": "Дежурная смена",
"Birinchi torlik": "Первое узкое место",
"Disk, kod emas": "Диск, а не код",
"Ming obyektda ham soniyasiga o'rtacha": "Даже на тысяче объектов приходит в среднем",
"hodisa keladi — bu bitta oddiy server uchun kichik yuk. Muammo boshqa joyda: kadr va klip arxivi har chorakda": "событий в секунду — для обычного сервера это небольшая нагрузка. Проблема в другом: архив кадров и клипов прибавляет каждый квартал",
"TB ga o'sib boradi va uni kengaytirish oldindan rejalashtiriladi.": "ТБ, и его расширение планируется заранее.",
"Ikkinchi torlik": "Второе узкое место",
"Bir vaqtda ochilgan video": "Одновременно открытое видео",
"Media shlyuz uchun ahamiyatli raqam — obyektlar soni emas, bir paytda ochilgan oqimlar soni. O'nta operator to'rttadan oqim ochsa, bu": "Для медиашлюза значима не численность объектов, а число одновременно открытых потоков. Десять операторов по четыре потока — это",
"Mbit/s va bitta shlyuz uchun chegara. Keyingisi — ikkinchi nusxa.": "Мбит/с и предел для одного шлюза. Дальше — второй экземпляр.",
"Uchinchi torlik": "Третье узкое место",
"Navbatchining e'tibori": "Внимание дежурного",
"Bir kishi tunda": "За ночь один человек не разберёт качественно больше",
"tadan ortiq hodisani sifatli ko'ra olmaydi. Shuning uchun filtr va takrorni yig'ish server uchun emas, odam uchun kerak: navbatga kuniga": "инцидентов. Поэтому фильтры и склейка нужны не серверу, а человеку: из",
"hodisadan": "событий в сутки в очередь выходит меньше",
"dan kami chiqadi.": ".",

"Xavfsizlik va ma'lumotning joyi": "Безопасность и место хранения данных",
"Obyektlarning kadrlari, kliplari va reyestri bankning o'z serverida qoladi. Yetkazuvchi buluti orqali ishlaydigan yechim tanlanganda ham, dalil sifatida faqat bank konturidagi nusxa ishlatiladi.": "Кадры, клипы и реестр объектов остаются на собственном сервере банка. Даже если выбрано решение, работающее через облако поставщика, доказательством служит только копия внутри контура банка.",
"Qurilmadan markazga": "От устройства к центру",
"Ochiq internetda hech narsa yurmaydi": "По открытому интернету ничего не ходит",
"SIM kartalar yopiq APN ga ulanadi, shlyuzda bank CA imzolagan mijoz sertifikati turadi. Sertifikat yiliga almashtiriladi; o'g'irlangan qurilma sertifikati bekor qilinadi va u o'sha soniyadan boshlab markazga ulanmaydi.": "SIM-карты подключаются к закрытому APN, на шлюзе лежит клиентский сертификат, подписанный CA банка. Сертификат меняется раз в год; у украденного устройства он отзывается, и с этой секунды оно к центру не подключится.",
"Xodim tomonidan": "Со стороны сотрудника",
"Tizimda alohida parol yaratilmaydi": "Отдельный пароль в системе не заводится",
"Kirish bank AD hisobi orqali, rol AD guruhidan olinadi. Buyruq beradigan rollar uchun ikkinchi omil talab qilinadi. Sessiya": "Вход через учётную запись AD банка, роль берётся из группы AD. Для ролей с правом команд требуется второй фактор. Сессия",
"soatdan keyin tugaydi va qayta kirish so'raladi.": "часов, после чего она завершается и требуется повторный вход.",
"Ma'lumot qayerda": "Где лежат данные",
"Kadr, klip va reyestr — bank serverida": "Кадры, клипы и реестр — на сервере банка",
"Obyekt ombori bank ma'lumotlar markazida turadi. Shaxsga doir ma'lumot O'zbekiston hududidagi bazada qayta ishlanishi talabi shu tarzda bajariladi; yetkazuvchi buluti faqat qurilmani sozlash uchun ishlatiladi va dalil u yerdan olinmaydi.": "Объектное хранилище стоит в дата-центре банка. Так выполняется требование обрабатывать персональные данные в базе на территории Узбекистана; облако поставщика используется только для настройки устройства, и доказательства оттуда не берутся.",
"Qurilmaning o'zi": "Само устройство",
"Zavod paroli bilan qolgan kamera — ochiq eshik": "Камера с заводским паролем — открытая дверь",
"Montaj varag'ida uchta majburiy band bor: parolni almashtirish, keraksiz xizmatlarni o'chirish, proshivkani yetkazuvchi saytidan yangilash. Bu bajarilmagan qurilma tizimga ulanmaydi va qabul dalolatnomasi imzolanmaydi.": "В листе монтажа три обязательных пункта: сменить пароль, отключить лишние службы, обновить прошивку с сайта поставщика. Устройство, где это не сделано, к системе не подключается и акт приёмки не подписывается.",
"Nima qilinmaydi.": "Чего система не делает.",
"Yuzni tanish bazasi yuritilmaydi, doimiy jonli translyatsiya telefonlarga berilmaydi, klip messenjerga yuborilmaydi. Yozuv tizimdan faqat rasmiy eksport orqali chiqadi: suv belgisi, vaqt tamg'asi va jurnaldagi yozuv bilan. Obyekt kirishiga videokuzatuv haqida ogohlantirish lavhasi osiladi.": "База распознавания лиц не ведётся, постоянная трансляция на телефоны не выдаётся, клип в мессенджер не отправляется. Запись выходит из системы только официальной выгрузкой: с водяным знаком, отметкой времени и записью в журнале. На входе на объект вешается табличка о видеонаблюдении.",

"Montaj, jihoz kafolati va aloqa kanali pudratchida qoladi. Quyidagi ishlar esa shartnomaga o'tkazilmaydi: ular bajarilmasa, bir yildan keyin tizim ishlayotgandek ko'rinadi, lekin ishonchli bo'lmaydi.": "Монтаж, гарантия на оборудование и канал связи остаются у подрядчика. А перечисленные ниже работы на договор не передаются: если их не делать, через год система будет выглядеть работающей, но перестанет быть надёжной.",
"Ish": "Работа",
"Kim bajaradi": "Кто выполняет",
"Davriyligi": "Периодичность",
"Bajarilmasa": "Если не выполняется",
"Kun-tun": "Круглосуточно",
"Hodisa keladi, javob bermaydi: tizimning ma'nosi yo'qoladi": "Событие приходит, ответа нет: система теряет смысл",
"Qurilma va SIM reyestri": "Реестр устройств и SIM",
"Har ulanishda": "При каждом подключении",
"Qaysi kamera qaysi obyektda ekani chalkashadi": "Путается, какая камера на каком объекте",
"Sertifikat almashtirish": "Смена сертификатов",
"AT departamenti": "Департамент ИТ",
"Yiliga": "Раз в год",
"Muddati o'tgan kunda o'nlab obyekt birdan uziladi": "В день истечения разом отваливаются десятки объектов",
"Zaxiradan tiklash sinovi": "Учебное восстановление из копии",
"Oyiga": "Раз в месяц",
"Zaxira bor deb o'ylanadi, kerak bo'lganda ochilmaydi": "Копия считается рабочей, а в нужный момент не открывается",
"Adapter va proshivka yangilash": "Обновление адаптеров и прошивок",
"Chiqqanda, sinovdan keyin": "По выходу, после испытаний",
"Brend API ni o'zgartiradi, hodisalar kelmay qoladi": "Бренд меняет API, события перестают приходить",
"Yolg'on signal tahlili": "Разбор ложных тревог",
"Inspektor": "Инспектор",
"Haftasiga": "Раз в неделю",
"Navbatchi signalga ishonmay qo'yadi": "Дежурный перестаёт доверять сигналу",
"SLA va uptime hisoboti": "Отчёт по SLA и доступности",
"AT va xavfsizlik": "ИТ и безопасность",
"Pudratchi bilan bahsda dalil bo'lmaydi": "В споре с подрядчиком не будет доказательств",
"Jamoa": "Команда",
"Doimiy tarkib:": "Постоянный состав:",
"kishi": "человек",
"Backend": "Backend",
", frontend": ", frontend",
", DevOps": ", DevOps",
", QA": ", QA",
", integratsiya muhandisi": ", инженер по интеграции",
", loyiha menejeri": ", руководитель проекта",
". Joriy etish tugagach, tarkib kamayadi va qo'llab-quvvatlash rejimiga o'tadi.": ". После завершения внедрения состав сокращается и переходит в режим поддержки.",
"oy · 100+ obyektga tayyor versiya": "месяца · версия для 100+ объектов",
"Eng katta tavakkal": "Самый большой риск",
"Jihoz o'rnatiladi, javob beruvchi tayinlanmaydi": "Оборудование поставили, ответственного не назначили",
"Texnik jihatdan to'g'ri qurilgan tizim ham, navbatchisi va haftalik tahlili bo'lmasa, olti oyda «ishlamaydi» deb baholanadi. Shuning uchun pilot qaroriga faqat jihoz byudjeti emas, mas'ul bo'linma va smena jadvali ham kiritiladi.": "Даже технически правильно построенная система без дежурного и недельного разбора через полгода будет признана «неработающей». Поэтому в решение по пилоту вносится не только бюджет на оборудование, но и ответственное подразделение с графиком смен.",
"aloqada bo'lish · pilot darvozasi": "на связи · порог пилота",
/* --- taqdimot lug'atidan olingan umumiy atamalar (bir xil yozilishi uchun) --- */
"Yagona hodisa sxemasi": "Единая схема события",
"Yopiq APN": "Закрытый APN",
"Adapter": "Адаптер",
"Buyruq": "Команда",
"Mahalliy tugun": "Локальный узел",
"Brend": "Бренд",
"Yopish (Esc)": "Закрыть (Esc)",
"Oldingi": "Предыдущий",
"Keyingi": "Следующий",
"Kengaytirish": "Развернуть",
"Yig'ish": "Свернуть",
"Batafsil": "Подробно",
"Manba": "Источник",

/* --- sahifa qobig'i (chuqur.js) --- */
"Tizim ishlashi": "Как работает система",
"Ekranlar va rollar": "Экраны и роли",
"Slaydga qaytish ·": "Вернуться к слайду ·",
"ta batafsil": "подробных справок",
"Yashil belgili har bir blok bosiladi": "Кликается любой блок с зелёной меткой",
"Tushunarli": "Понятно",
"MKBANK · Aktivlar nazorati": "MKBANK · Контроль активов",
"Elektr va aloqasi yo'q obyekt: nazorat shu sharoitga moslab quriladi.": "Объект без электричества и связи: контроль строится именно под эти условия.",
"Navbatchining ish joyi: obyekt kartochkasi, hodisalar navbati va jonli video.": "Рабочее место дежурного: карточка объекта, очередь инцидентов и живое видео.",
"Qabul.": "Приём.",
"Normallashtirish.": "Нормализация.",
"Takrorni tashlash.": "Отсечение повторов.",
"Shinaga uzatish.": "Передача в шину.",
"daqiqa ichida kelgan bir xil turdagi hodisalar bitta voqeaga yig'iladi va takror soni saqlanadi.": "минут, склеиваются в один инцидент, а число повторов сохраняется.",
"Nima oldini oladi": "Что это предотвращает",

/* --- batafsil sarlavhalari: blokning aria-label matni shu yerdan o'giriladi --- */
"41 soniya: har bir bo'lak qayerdan olingan": "41 секунда: откуда взята каждая часть",
"Jamoa rahbarlari uchun": "Для тимлида",
"Platformaning ulushi olti soniya. Nega uni qisqartirish shoshilinch emas": "Доля платформы — шесть секунд. Почему её сокращение не срочно",
"148 kilobayt: bitta hodisaning tannarxi": "148 килобайт: себестоимость одного события",
"Moliya va aloqa uchun": "Для финансов и связи",
"Olti qatlam — olti xil shartnoma": "Шесть слоёв — шесть разных договоров",
"Rahbariyat uchun": "Для правления",
"PIR datchik: nimani ko'radi va nimani ko'rmaydi": "PIR-датчик: что он видит и чего не видит",
"Montajchilar uchun": "Для монтажников",
"Nega yozuv avval obyektda boshlanadi": "Почему запись начинается на объекте",
"Tasnif kamerada bajariladi, markazda emas": "Классификация выполняется в камере, а не в центре",
"PSM: modem nega darhol javob bermaydi": "PSM: почему модем отвечает не сразу",
"mTLS: qurilma o'zini tanishtiradi, markaz ham": "mTLS: устройство предъявляет себя, центр тоже",
"Xavfsizlik uchun": "Для безопасности",
"Kadr o'lchami va zaif signal": "Размер кадра и слабый сигнал",
"Aloqa uchun": "Для связи",
"Adapter nimani tashlaydi va nimani qo'shadi": "Что адаптер отбрасывает и что добавляет",
"Qoidalar: qaysi hodisa navbatchini uyg'otadi": "Правила: какое событие будит дежурного",
"Xabarnoma: uch kanal va dublyaj": "Уведомление: три канала и эскалация",
"24 soniya: zanjirdagi eng qimmat bo'lak": "24 секунды: самая дорогая часть цепочки",
"Media shlyuz: oqim faqat so'ralganda ochiladi": "Медиашлюз: поток открывается только по запросу",
"Buyruq: ikki marta bosilsa ham bir marta bajariladi": "Команда: нажали дважды — выполнится один раз",
"Tungi hodisadan qaysi hujjat qoladi": "Какой документ остаётся после ночного события",
"Obyekt menejeri uchun": "Для менеджера объекта",
"Vaqt taqsimoti nimani ko'rsatadi": "Что показывает распределение времени",
"Zaif signalli obyektda vaqt qanday o'zgaradi": "Как меняется время на объекте со слабым сигналом",
"Qurilma: energiya va dalil shu yerda hal bo'ladi": "Устройство: здесь решаются энергия и доказательство",
"Qatlam 1": "Слой 1",
"Mahalliy tugun: aloqa yo'q paytdagi xotira": "Локальный узел: память на время без связи",
"Qatlam 2": "Слой 2",
"Kanal: yopiq APN va ikki SIM": "Канал: закрытый APN и две SIM",
"Qatlam 3": "Слой 3",
"Adapter: bankni brendga bog'lanishdan saqlaydigan qatlam": "Адаптер: слой, который не даёт банку привязаться к бренду",
"Qatlam 4": "Слой 4",
"Yadro: bank o'zi yozadigan va o'zida saqlaydigan qism": "Ядро: то, что банк пишет сам и держит у себя",
"Qatlam 5": "Слой 5",
"Ish joyi: ekranda nima ko'rinishi kerak": "Рабочее место: что должно быть на экране",
"Qatlam 6": "Слой 6",
"Qurilma nosozligi: 72 soatlik muddat qayerdan": "Отказ устройства: откуда взялись 72 часа",
"Servis uchun": "Для сервиса",
"last_seen: aloqasizlik qachon e'lon qilinadi": "last_seen: когда объявляется потеря связи",
"Operator bilan SLA: nimani talab qilish mumkin": "SLA с оператором: что можно требовать",
"Adapter to'xtaganda nima bo'ladi": "Что происходит, когда адаптер останавливается",
"Yadro nosozligi: bir soatlik muddat qayerdan": "Отказ ядра: откуда взялся один час",
"Interfeys xatosi: nega bir ish kuni": "Ошибка интерфейса: почему один рабочий день",
"sxema: versiyasi yo'q yozuv qabul qilinmaydi": "sxema: запись без версии не принимается",
"hodisa_id: takrorni tashlashning kaliti": "hodisa_id: ключ для отсечения повторов",
"obyekt_id: qurilma aktivga qanday bog'lanadi": "obyekt_id: как устройство привязывается к активу",
"vaqt: UTC va NTP, boshqa variant yo'q": "vaqt: UTC и NTP, других вариантов нет",
"ishonch: raqam bilan filtr, his-tuyg'u bilan emas": "ishonch: фильтр по числу, а не по ощущению",
"kadr_url: rasm qayerda saqlanadi": "kadr_url: где хранится изображение",
"sha256: dalilning butunligini nima isbotlaydi": "sha256: чем доказывается целостность",
"Yuristlar uchun": "Для юристов",
"batareya va signal: nosozlikni oldindan ko'rish": "batareya и signal: увидеть отказ заранее",
"Sxemani o'zgartirish tartibi": "Порядок изменения схемы",
"Takror hodisa: sabab va o'lchov": "Повторное событие: причина и измерение",
"Dalil zanjiri: kadrdan sud ishigacha": "Цепочка доказательства: от кадра до судебного дела",
"Hikvision: ochiq oqim, lekin uzilishni o'zi aytmaydi": "Hikvision: открытый поток, но об обрыве не сообщает",
"Dahua: obuna oqimi va nomlar farqi": "Dahua: поток подписки и разница в названиях",
"Reolink: Home Hub orqali ishlash sharti": "Reolink: работа только через Home Hub",
"Ajax: signalizatsiya tili, video emas": "Ajax: язык сигнализации, а не видео",
"Milesight: eng arzon adapter, eng kam ma'lumot": "Milesight: самый дешёвый адаптер и меньше всего данных",
"ONVIF: umumiy til, lekin har brendda o'z shevasi": "ONVIF: общий язык, но у каждого бренда свой диалект",
"Qabul: obuna uzilganini qanday bilish mumkin": "Приём: как узнать, что подписка оборвалась",
"Normallashtirish: nomlar jadvali kodda emas, sozlamada": "Нормализация: таблица имён в настройках, а не в коде",
"Takrorni yig'ish: nega 10 daqiqa": "Склейка повторов: почему десять минут",
"Shina: nega hodisa to'g'ridan-to'g'ri bazaga yozilmaydi": "Шина: почему событие не пишется сразу в базу",
"Yangi brendni ulash: ish rejasi": "Подключение нового бренда: план работ",
"Qabul sinovlari: aniq nima o'lchanadi": "Приёмочные испытания: что именно измеряется",
"Aloqa uzilishi: eng ko'p uchraydigan nosozlik": "Обрыв связи: самый частый отказ",
"Batareya: o'lim belgilari uch hafta oldin ko'rinadi": "Батарея: признаки смерти видны за три недели",
"Yolg'on signal: sabablari va davosi": "Ложная тревога: причины и лечение",
"Sukut nazorati: signal yo'qligi ham hodisa": "Контроль тишины: отсутствие сигнала — тоже событие",
"Bir kunlik trafik: qayerdan yig'iladi": "Суточный трафик: из чего складывается",
"Dekabr kunidagi energiya balansi": "Энергобаланс декабрьских суток",
"Bazaga nima yoziladi, nima yozilmaydi": "Что пишется в базу, а что нет",
"Nega bu sxema doimiy keng kanalsiz ishlaydi": "Почему эта схема работает без постоянного широкого канала",
"Beshta tekshiruv va ularning og'irliklari": "Пять проверок и их веса",
"Bitta kartochka, yetti xil maqsad": "Одна карточка, семь разных задач",
"Oltita virtual mashina nimaga ketadi": "На что уходят шесть виртуальных машин",
"Ma'lumot bank konturidan chiqmaydi": "Данные не выходят за контур банка",
"Boshqaruv paneli: bitta ekranda nima turadi": "Панель управления: что стоит на одном экране",
"Reyestr: montaj marshruti shu yerdan tuziladi": "Реестр: отсюда строится маршрут монтажа",
"Obyekt kartochkasi: hodisa qayerda ko'rinadi": "Карточка объекта: где виден инцидент",
"Rahbariyat: oyiga o'n daqiqalik ekran": "Правление: экран на десять минут в месяц",
"Obyekt menejeri: kunlik ish ro'yxati": "Менеджер объекта: ежедневный список работ",
"Inspektor: masofaviy ko'rik nimani almashtiradi": "Инспектор: что заменяет дистанционный осмотр",
"Inspektor uchun": "Для инспектора",
"Xavfsizlik xizmati: yagona rol, buyruq bera oladi": "Служба безопасности: единственная роль с правом команд",
"Buxgalteriya: nazorat zaxira hisobiga qanday tegadi": "Бухгалтерия: как контроль влияет на расчёт резерва",
"Moliya uchun": "Для финансов",
"Realizatsiya: kamera sotuvga qanday yordam beradi": "Реализация: чем камера помогает продаже",
"Marketing uchun": "Для маркетинга",
"Administrator: reyestrni to'g'ri tutish": "Администратор: держать реестр в соответствии с реальностью",
"Administrator uchun": "Для администратора",
"Tungi xabarnoma kimga va qanday tartibda boradi": "Кому и в каком порядке уходит ночное уведомление",
"Jurnal: nima yoziladi va kim o'chira olmaydi": "Журнал: что пишется и кто не может стереть",
"Auditorlar uchun": "Для аудиторов",
"Ko'rik dolzarbligi: 25 ball qanday taqsimlanadi": "Актуальность осмотра: как распределяются 25 баллов",
"Sug'urta: 25 ball nimaga bog'liq": "Страхование: от чего зависят 25 баллов",
"Baho dolzarbligi: 20 ball va 12 oylik muddat": "Актуальность оценки: 20 баллов и срок в 12 месяцев",
"Hujjatlar to'liqligi: ro'yxat bosqichga bog'liq": "Полнота документов: список зависит от этапа",
"Qo'riqlash va qurilmalar: 15 ballning formulasi": "Охрана и устройства: формула 15 баллов",
"Indeks qachon qayta hisoblanadi": "Когда индекс пересчитывается",
"Bir servis tashrifining ball qiymati": "Сколько баллов стоит один выезд сервиса",
"Nega qurilmalar yolg'iz 7,5 balldan oshmaydi": "Почему одни устройства не дают больше 7,5 балла",
"Ko'rik davri: 90 kun qayerdan va u qanday sanaladi": "Периодичность осмотра: откуда 90 дней и как они считаются",
"Baholash muddati va 30 kunlik ogohlantirish": "Срок оценки и предупреждение за 30 дней",
"Polis muddati: nega 30 kun oldin ogohlantiriladi": "Срок полиса: почему предупреждение за 30 дней",
"Balansda turish muddati va zaxira toifalari": "Срок нахождения на балансе и категории резерва",
"Javob muddati: besh daqiqa qanday sanaladi": "Срок ответа: как считаются пять минут",
"Obyektga o'rtacha to'rtta qurilma": "В среднем четыре устройства на объект",
"Puls oqimi: hisob yuqori chegara bo'yicha": "Поток импульсов: расчёт по верхней границе",
"Kuniga 36 000 hodisa, navbatga 300 tasi": "36 000 событий в сутки, в очередь попадает 300",
"Jonli video: obyekt soni emas, ochilgan oqim soni muhim": "Живое видео: важно не число объектов, а число открытых потоков",
"Dalil arxivi: eng tez o'sadigan hajm": "Архив доказательств: самый быстрорастущий объём",
"Markaz kanali: nimadan yig'iladi": "Канал центра: из чего складывается",
"Serverlar: pilotdan ming obyektgacha": "Серверы: от пилота до тысячи объектов",
"Navbatchi smenasi: nechta odam kerak": "Дежурная смена: сколько нужно людей",
"Disk: o'sish rejasi birinchi yildan tuziladi": "Диск: план роста составляется с первого года",
"Media shlyuz: ikkinchi nusxa qachon kerak": "Медиашлюз: когда нужен второй экземпляр",
"Navbatchining e'tibori: haqiqiy chegara": "Внимание дежурного: настоящее ограничение",
"Qurilmadan markazgacha bo'lgan yo'lning himoyasi": "Защита пути от устройства до центра",
"Xodim tomonidan kirish: AD, rol va ikkinchi omil": "Доступ сотрудника: AD, роль и второй фактор",
"Ma'lumot qayerda saqlanadi va nega bu talab": "Где хранятся данные и почему это требование",
"Qurilmani himoyalash: montaj varag'idagi majburiy bandlar": "Защита устройства: обязательные пункты листа монтажа",
"Taqiqlar ro'yxati va ularning sababi": "Список запретов и причины",
"Navbatchi smenasi: bu ishni pudratchiga berib bo'lmaydi": "Дежурная смена: эту работу нельзя отдать подрядчику",
"Reyestr: ma'lumot eskirsa, hamma narsa buziladi": "Реестр: устарел он — ломается всё остальное",
"Sertifikat almashtirish: bir kunda yuzta obyekt uzilmasligi uchun": "Смена сертификатов: чтобы за один день не отвалилась сотня объектов",
"Zaxira nusxa: sinalmagan zaxira mavjud emas": "Резервные копии: непроверенной копии не существует",
"Proshivka yangilash: sinovdan keyin va ish kunida": "Обновление прошивок: после испытаний и в рабочий день",
"Haftalik tahlil: o'n besh daqiqalik ish, katta natija": "Недельный разбор: пятнадцать минут работы, большой эффект",
"Oylik hisobot: pudratchi bilan bahsdagi dalil": "Месячный отчёт: аргумент в споре с подрядчиком",
"Jamoa tarkibi va u nima bilan band": "Состав команды и чем она занята",
"Eng katta tavakkal texnik emas": "Самый большой риск — не технический"
,

/* --- tizim xaritasi: kontur, band, pill, oqim va izoh matnlari --- */
"Ko'rsatadi va buyruq beradi": "Показывает и отдаёт команду",
"Qaror qiladi, jurnal yuritadi": "Решает, ведёт журнал",
"Bitta sxemaga o'giradi": "Приводит к одной схеме",
"Shifrlaydi, zaxirasiga o'tadi": "Шифрует, уходит на резерв",
"Yig'adi va navbatda ushlaydi": "Собирает и держит в очереди",
"Integrator": "Интегратор",
"Sezadi, yozadi, xabar beradi": "Замечает, пишет, сообщает",
"Yetkazuvchi": "Поставщик",
"Nazorat paneli": "Панель контроля",
"Mobil ilova (oflayn)": "Мобильное приложение",
"Kengash hisoboti": "Отчёт правлению",
"Eksport: XLSX, PDF": "Экспорт: XLSX, PDF",
"Obyekt reyestri": "Реестр объектов",
"Media shlyuz, WebRTC": "Медиашлюз, WebRTC",
"Qoidalar mexanizmi": "Механизм правил",
"O'zgarmas jurnal": "Неизменяемый журнал",
"Takror: 10 daqiqa": "Повтор: окно 10 минут",
"LTE Cat-1, RSRP −89 dBm": "LTE Cat-1, RSRP −89 дБм",
"Ikki operator SIM": "SIM двух операторов",
"Oyiga 4,3 GB": "4,3 ГБ в месяц",
"LoRaWAN shlyuz": "Шлюз LoRaWAN",
"NVR, 2 TB arxiv": "NVR, архив 2 ТБ",
"Uzilishda 72 soat navbat": "Очередь 72 часа",
"NTP: farq < 2 daqiqa": "NTP: расхождение < 2 мин",
"Batareyali kamera, 4G": "Батарейная камера, 4G",
"PIR: 8 m, 110°": "PIR: 8 м, 110°",
"Kutishda 0,08 Vt": "В ожидании 0,08 Вт",
"Bank konturi": "Контур банка",
"Bankning o'z markazi · ma'lumot mamlakat ichida · kirish AD orqali": "Собственный центр банка · данные внутри страны · вход через AD",
"Aloqa operatori tarmog'i": "Сеть оператора связи",
"Bankka tegishli emas · shartnoma, SLA va yopiq APN bilan boshqariladi": "Банку не принадлежит · управляется договором, SLA и закрытым APN",
"Obyekt konturi": "Контур объекта",
"Elektr yo'q · internet yo'q · qo'riqchi yo'q · 267 obyekt": "Нет электричества · нет интернета · нет охраны · 267 объектов",
"Hodisa va telemetriya": "События и телеметрия",
"Buyruq va sozlama": "Команды и настройки",
"Video — so'rov bo'yicha": "Видео — по запросу",
"Hodisa va telemetriya: doim pastdan yuqoriga": "События и телеметрия: всегда снизу вверх",
"Buyruq va sozlama: yuqoridan pastga, jurnal bilan": "Команды и настройки: сверху вниз, с журналом",
"Yashil belgili band, kontur va oqim bosiladi": "Слой, контур и поток с зелёной меткой кликаются",
"Tizim xaritasi: uchta kontur, olti qatlam va uchta oqim": "Карта системы: три контура, шесть слоёв и три потока",
"Egasi": "Владелец",
"Shartli belgilar": "Условные обозначения",

/* --- xarita bo'limining sarlavhasi, lidi va izohi --- */
"Tizim xaritasi": "Карта системы",
"Tizim xaritasi: uch kontur, olti qatlam, uch oqim": "Карта системы: три контура, шесть слоёв, три потока",
"Tizim bitta mahsulot emas: oltita qatlam bir-biriga shartnoma orqali ulanadi va ularning uchtasi umuman bankka tegishli emas. Quyidagi xarita shuni ko'rsatadi — qaysi qatlam qaysi konturda turadi, orasidan qanday oqim o'tadi va buzilganda kim tuzatadi.": "Система — не один продукт: шесть слоёв связаны между собой договорами, и три из них банку вообще не принадлежат. Карта ниже показывает именно это — какой слой в каком контуре стоит, какой поток идёт между ними и кто чинит при отказе.",
"Xaritada uchta kontur, oltita qatlam va uchta oqim bor. Bandni bosing — qatlam nimani bajaradi va nima buziladi; konturni bosing — chegaradan nima o'tadi va kim javob beradi; oqim chizig'ini bosing — qanday protokol va qanday muddat bilan.": "На карте три контура, шесть слоёв и три потока. Нажмите на слой — что он делает и что в нём ломается; на контур — что проходит через границу и кто отвечает; на линию потока — по какому протоколу и в какой срок.",

/* --- adapter xaritasi --- */
"IP kamera, elektr bor": "IP-камера, есть питание",
"Qo'riqlash paneli": "Охранная панель",
"LoRaWAN datchik shlyuzi": "Шлюз датчиков LoRaWAN",
"Ulanadi yoki obuna ochadi; uzilsa qayta uriniladi.": "Подключается или подписывается, повторяет при обрыве.",
"Maydonlar bitta sxemaga tushadi, vaqt UTC ga o'tadi.": "Поля ложатся в одну схему, время уходит в UTC.",
"O'n daqiqadagi bir xil hodisalar bitta voqeaga qo'shiladi.": "Одинаковые события за десять минут — один инцидент.",
"Navbatga qo'yiladi; iste'molchi to'xtasa ham yo'qolmaydi.": "Ставится в очередь; не пропадёт при остановке потребителя.",
"Bildirishnoma xizmati": "Служба уведомлений",
"Adapter xaritasi: uchta brend tili, to'rtta bosqich va bitta yozuv": "Карта адаптера: три языка брендов, четыре шага и одна запись",
"har brendga bitta modul": "по одному модулю на бренд",
"Chiqishda: bitta yozuv": "На выходе: одна запись",
"Brend nomi ham saqlanadi: kelib chiqishi yo'qolmaydi": "Имя бренда тоже сохраняется: происхождение не теряется",
"Kim oladi": "Кто забирает",
"Shina, kalit obyekt_id · kamida bir marta yetkaziladi": "Шина, ключ obyekt_id · доставка не менее одного раза",
"Chapdagi uchta quti — uchta boshqa til: Hikvision uzluksiz HTTP oqim beradi, Ajax to'qqiz baytlik signal kodi yuboradi, Milesight MQTT mavzusiga JSON qo'yadi. O'rtadagi to'rt bosqich ularni bitta yozuvga aylantiradi. Har bir quti bosiladi.": "Три коробки слева — три разных языка: Hikvision даёт непрерывный HTTP-поток, Ajax шлёт девятибайтный код тревоги, Milesight кладёт JSON в тему MQTT. Четыре шага в центре превращают их в одну запись. Каждая коробка кликается.",

/* --- yo'naltirish xaritasi (tizim-boshqaruv) --- */
"Darhol": "Сразу же",
"41 soniyada": "за 41 секунду",
"Ertalab, 08:00": "Утром, 08:00",
"kunlik ro'yxatda": "в суточном списке",
"kunlik ekran": "суточный экран",
"Oy oxirida": "В конце месяца",
"jamlangan raqamda": "в сводном числе",
"oylik hisobot": "месячный отчёт",
"Navbatchi xavfsizlik xodimi": "Дежурный сотрудник охраны",
"Jonli videoni ochadi": "Открывает живое видео",
"Sirena, eshik": "Сирена, дверь",
"Qo'riqlashga xabar": "Сообщение в охрану",
"Ko'rik inspektori": "Инспектор осмотра",
"Servis arizasi": "Заявка в сервис",
"Ko'rik muddati": "Срок осмотра",
"Xarajat yozuvi": "Запись расхода",
"Zaxira toifasi": "Категория резерва",
"KPI va xarajat": "KPI и расходы",
"Realizatsiya rejasi": "План реализации",
"Yo'naltirish xaritasi: bitta hodisa qaysi rolga qachon boradi": "Карта маршрутизации: к какой роли и когда приходит одно событие",
"Bitta hodisa": "Одно событие",
"Qarshi tumanidagi ombor, dekabr kechasi": "Склад в Каршинском районе, декабрьская ночь",
"Kimga, qachon va qaysi kanal bilan borishini shu hal qiladi": "Решает, кому, когда и по какому каналу уйдёт",
"Vaqt: 20:00–08:00": "Время: 20:00–08:00",
"Sinf: odam": "Класс: человек",
"Obyekt: qo'riqlanmaydi": "Объект: без охраны",
"Muddat: 5 daqiqa": "Срок: 5 минут",
"Kim ko'radi": "Кто видит",
"Nima qiladi": "Что делает",
"Kim umuman ko'rmaydi": "Кто не видит вовсе",
"Realizatsiya mutaxassisiga bu hodisa chiqmaydi: unga faqat e'longa yaroqli, odam tushmagan kadr beriladi.": "Специалисту по реализации это событие не выходит: ему достаётся только кадр без людей, пригодный для объявления.",
"Uchala yo'nalishda ham har bir ko'rish va har bir buyruq shu yerga tushadi va besh yil saqlanadi.": "По всем трём направлениям каждый просмотр и каждая команда попадают сюда и хранятся пять лет.",
"Xarita bitta tungi hodisaning yo'lini ko'rsatadi: qoidalar mexanizmi uni uch pog'onaga ajratadi va tunda faqat bitta odamni uyg'otadi. Har bir qutini bosing — kim nimani ko'radi, qaysi kanal bilan va nima qila oladi.": "Карта показывает путь одного ночного события: механизм правил разводит его на три ступени и ночью будит только одного человека. Нажмите на любую коробку — кто что видит, по какому каналу и что может сделать.",

/* --- adapter bosqichlaridagi chiplar --- */
"Backoff 5 s → 5 daqiqa": "Backoff 5 с → 5 минут",
"Har brendga o'z moduli": "Свой модуль на бренд",
"Vaqt → UTC": "Время → UTC",
"Soat farqi > 2 daq → belgi": "Расхождение > 2 мин → метка",
"Oyna 10 daqiqa": "Окно 10 минут",
"Takror soni saqlanadi": "Число повторов сохраняется",
"Kalit: obyekt_id": "Ключ: obyekt_id",
"Kamida bir marta": "Не менее одного раза",

/* --- buzilish xaritasi --- */
"Buzilish": "Отказ",
"Qanday bilinadi": "Как обнаруживается",
"Tizim nima qiladi": "Что делает система",
"Odam nima qiladi": "Что делает человек",
"Uchta puls ketma-ket kelmadi: elektrli tugunda uch daqiqa, batareyali kamerada qirq besh daqiqa ichida bilinadi.": "Три пульса подряд не пришли: на узле с питанием это видно за три минуты, на батарейной камере — за сорок пять.",
"Shlyuz hodisalarni o'z navbatiga yozadi va ikkinchi operator SIM ga o'tadi. Kamera yozishni to'xtatmaydi: dalil obyektda qoladi.": "Шлюз пишет события в свою очередь и уходит на SIM второго оператора. Камера продолжает запись: доказательство остаётся на объекте.",
"Servis arizasi yetmish ikki soatlik muddat bilan ochiladi. Obyektning nazorat indeksi tushadi va u ko'rik rejasining boshiga chiqadi.": "Открывается заявка в сервис со сроком семьдесят два часа. Индекс контроля объекта падает, и он поднимается в начало плана осмотров.",
"Ikki operator SIM, tashqi antenna va montajdan oldin o'lchangan RSRP. O'lchov montaj varag'ida saqlanadi.": "Две SIM разных операторов, внешняя антенна и RSRP, замеренный до монтажа. Замер хранится в листе монтажа.",
"Zaryad darajasi har telemetriya o'lchovida yuboriladi: o'ttiz foizda ariza ochiladi, yigirma foizda nazorat indeksi tushadi.": "Уровень заряда уходит с каждым замером телеметрии: на тридцати процентах открывается заявка, на двадцати падает индекс контроля.",
"Qurilma tejash rejimiga o'tadi: yozuv qoladi, jonli video o'chadi va operator ekranida tugma faolsiz bo'lib qoladi.": "Устройство уходит в режим экономии: запись остаётся, живое видео отключается, а кнопка на экране оператора становится неактивной.",
"Obyekt kuzgi profilaktika ro'yxatiga tushadi. Zaxira akkumulyator viloyat omborida turadi, obyektda emas.": "Объект попадает в список осенней профилактики. Запасной аккумулятор лежит на областном складе, а не на объекте.",
"Dekabr quyoshiga qarab hisoblangan panel, past haroratda zaryadni to'xtatuvchi BMS va besh sutkalik zaxira.": "Панель, посчитанная по декабрьскому солнцу, BMS с запретом заряда на холоде и запас на пять суток.",
"Operator xabarnomada sababni ro'yxatdan tanlaydi: hayvon, shamol, yorug'lik o'zgarishi, yomg'ir yoki texnika.": "Оператор выбирает причину из списка в уведомлении: животное, ветер, смена освещения, дождь или техника.",
"Voqea yopiladi, kadr sabab bilan birga saqlanadi. Bitta kamera oyiga to'rtdan ko'p bersa, u sozlash ro'yxatiga tushadi.": "Инцидент закрывается, кадр сохраняется вместе с причиной. Если по одной камере их больше четырёх в месяц, она попадает в список настройки.",
"Haftalik o'n besh daqiqalik tahlilda burchak, sezish zonasi va ishonch chegarasi qayta qo'yiladi.": "На недельном пятнадцатиминутном разборе заново выставляются угол, зона детекции и порог уверенности.",
"To'g'ri burchak, sezish zonasini kesish, sinf bo'yicha filtr va nol butun yetmish ishonch chegarasi.": "Верный угол, вырезанная зона детекции, фильтр по классу и порог уверенности ноль целых семьдесят.",
"72 soat navbat": "72 часа очереди",
"30% da ariza": "заявка на 30%",
"oyiga 4 tadan ko'p": "больше 4 в месяц",
"Buzilish xaritasi: uchta nosozlik va ularning oxirigacha yuritilgan yo'li": "Карта отказов: три неисправности и их путь до конца",
"Eng xavfli holat — sukut: ikki kun hech narsa yubormagan kamera ekranda tinch obyekt kabi ko'rinadi. Shuning uchun nazorat pulsga quriladi va signalning yo'qligi ham voqea hisoblanadi.": "Самое опасное состояние — молчание: камера, ничего не приславшая двое суток, на экране выглядит как спокойный объект. Поэтому контроль строится на пульсе, и отсутствие сигнала само считается событием.",
"Har bir qator chapdan o'ngga oxirigacha yuritilgan: nosozlik qanday bilinadi, tizim o'zi nima qiladi, odam nima qiladi va buni oldindan nima to'xtatadi. Qatorni bosing — raqamlar, muddatlar va shartnomadagi bandlar ochiladi.": "Каждая строка проведена слева направо до конца: как обнаруживается отказ, что делает сама система, что делает человек и что останавливает это заранее. Нажмите на строку — откроются цифры, сроки и пункты договора.",

/* --- masshtab xaritasi --- */
"Kadr va klip arxivi": "Архив кадров и клипов",
"Disk, 90 kunlik saqlash": "Диск, хранение 90 дней",
"chorakda +0,8 TB": "плюс 0,8 ТБ в квартал",
"Bir vaqtdagi jonli oqim": "Одновременные живые потоки",
"Media shlyuz, cho'qqidagi yuk": "Медиашлюз, пиковая нагрузка",
"ikkinchi nusxa kerak": "нужен второй экземпляр",
"Tunda ishlaydigan odam soni": "Людей в ночной смене",
"ikkinchi navbatchi": "второй дежурный",
"Arxitektura": "Архитектура",
"Hodisa sxemasi": "Схема события",
"Adapter kodi": "Код адаптера",
"Rollar va ekranlar": "Роли и экраны",
"Montaj tartibi": "Порядок монтажа",
"Shartnoma shakli": "Форма договора",
"Masshtab xaritasi: o'n obyektdan ming obyektgacha": "Карта масштаба: от десяти объектов до тысячи",
"obyekt · pilot": "объектов · пилот",
"obyekt · balans": "объектов · баланс",
"O'n barobar o'sganda ham o'zgarmaydi": "Не меняется даже при росте в десять раз",
"O'q logarifmik: o'ndan minggacha bo'lgan yo'l bir ekranga sig'adi. Uchta chiziq uchta torlikni ko'rsatadi — disk birinchi bo'lib, media shlyuz mingga yaqin, navbatchi smenasi esa uch yuzda torlik qiladi. Har qatorni bosing.": "Шкала логарифмическая: путь от десяти до тысячи умещается в один экран. Три линии — три узких места: диск упирается первым, медиашлюз — ближе к тысяче, а дежурная смена — уже на трёхстах. Нажмите на любую строку.",

/* --- masshtab jadvalidagi birliklar --- */
"5 Mbit/s": "5 Мбит/с",
"36 Mbit/s": "36 Мбит/с",
"110 Mbit/s": "110 Мбит/с",
"1 VM": "1 ВМ",
"6 VM": "6 ВМ",
"12 VM": "12 ВМ",

/* --- masshtab xaritasidagi qiymatlar --- */
"0,03 TB": "0,03 ТБ",
"0,32 TB": "0,32 ТБ",
"0,97 TB": "0,97 ТБ",
"3,24 TB": "3,24 ТБ",
"2,0 Mbit/s": "2,0 Мбит/с",
"4,1 Mbit/s": "4,1 Мбит/с",
"8,2 Mbit/s": "8,2 Мбит/с",
"20,5 Mbit/s": "20,5 Мбит/с",
"1 kishi": "1 человек",
"2 kishi": "2 человека",
"4 kishi": "4 человека",
"1 ish kuni": "1 рабочий день",
"1–2 hafta": "1–2 недели",
"2–3 hafta": "2–3 недели",
"3–4 hafta": "3–4 недели",
"mkb.hodisa.v1 · 412 bayt": "mkb.hodisa.v1 · 412 байт"

});
