/* Tizim xaritalaridagi matnlarning ruscha tarjimasi (yechim-01…05).
   Kalit — xaritadagi o'zbekcha matn tugunining aynan o'zi.
   Sof texnik belgilar (ISUP 7660, AES-128, WireGuard, RTSP 554, 10.8.0.0/24 va
   shunga o'xshash) bu yerda yo'q: ular ikkala tilda ham bir xil yoziladi. */
window.MKB_LUGAT = Object.assign(window.MKB_LUGAT || {}, {

/* --- hudud nomlari va afsona --- */
"OBYEKTDA": "НА ОБЪЕКТЕ",
"OPERATOR TARMOG'IDA": "В СЕТИ ОПЕРАТОРА",
"BANK TARMOG'IDA": "В СЕТИ БАНКА",
"BANK TARMOG'I": "СЕТЬ БАНКА",
"tarmoq toki yo'q, kabel interneti yo'q, qorovul yo'q": "нет сетевого питания, нет кабельного интернета, нет сторожа",
"uchinchi tomon — bank bu yerda hech narsani boshqarmaydi": "третья сторона — банк здесь ничем не управляет",
"DMZ · tashqaridan port ochilmaydi": "DMZ · снаружи не открывается ни один порт",
"Hudud chegarasi": "Граница зоны",
"Har tugunni bosing": "Нажмите на любой узел",
"Har yo'lni va uning oxirini bosing": "Нажмите на путь и на его конец",
"Har qadamni bosing": "Нажмите на любой шаг",
"Har qatorni bosing": "Нажмите на любую строку",
"Har datchikni bosing": "Нажмите на любой датчик",

/* ============================ Yechim 01 ============================ */
"Ma'lumot: kameradan platformaga": "Данные: от камеры к платформе",
"12 V quvvat shinasi": "Силовая шина 12 В",
"Platformadan qaytadigan buyruq": "Команда, возвращаемая платформой",
"12 V DC · doimiy 6,5 Vt": "12 В DC · постоянные 6,5 Вт",
"Kameralar bu shinadan quvvat olmaydi:": "Камеры от этой шины не питаются:",
"ular o'z akkumulyatorida qishni o'tkazadi": "зиму они проводят на собственном аккумуляторе",
"Wi-Fi 2,4 GGs · WPA2": "Wi-Fi 2,4 ГГц · WPA2",
"Ethernet 100 Mbit/s": "Ethernet 100 Мбит/с",
"operator yadrosi": "ядро оператора",
"10.8.0.0/24 ichki manzil": "внутренний адрес 10.8.0.0/24",
"yagona hodisa sxemasi": "единая схема события",
"20 soniyalik klip ≈ 3,5 MB": "20-секундный клип ≈ 3,5 МБ",
"faqat shu obyekt uchun": "только для этого объекта",
"ichki shina · HTTPS": "внутренняя шина · HTTPS",
"RSRP −95 dBm": "RSRP −95 дБм",
"WireGuard UDP 51820 · 25 soniyalik keepalive": "WireGuard UDP 51820 · keepalive 25 секунд",
"Qaytish — o'sha tunnel: oqim, sozlama, proshivka · 1,5 soniya": "Обратно — тот же туннель: поток, настройка, прошивка · 1,5 секунды",
"Kamera × 3": "Камера × 3",
"Argus 4 Pro · 5 000 mA·soat": "Argus 4 Pro · 5 000 мА·ч",
"PIR uyg'otadi — 0,6 soniya": "ИК-датчик будит — 0,6 секунды",
"uyquda 20 mVt": "во сне 20 мВт",
"sakkiz kameragacha": "до восьми камер",
"2 × microSD, 1 TB gacha": "2 × microSD, до 1 ТБ",
"yozuv shu yerda qoladi": "запись остаётся здесь",
"4G router": "4G-роутер",
"ikki SIM · avtoalmashuv": "две SIM · автопереключение",
"tashqi antenna, 5 dBi": "внешняя антенна, 5 дБи",
"o'rtacha 3,2 Vt": "в среднем 3,2 Вт",
"12 V quvvat shkafi": "Силовой шкаф 12 В",
"LiFePO4 12 V 100 A·soat · 100 Vt panel · MPPT": "LiFePO4 12 В 100 А·ч · панель 100 Вт · MPPT",
"LTE bazasi": "Базовая станция LTE",
"3–7 km, ko'rinishi shart": "3–7 км, нужна прямая видимость",
"Operator NAT'i": "NAT оператора",
"kulrang IP: kirib bo'lmaydi": "серый IP: войти нельзя",
"VPN konsentrator": "VPN-концентратор",
"bank DMZ'ida turadi": "стоит в DMZ банка",
"har obyektga alohida kalit": "отдельный ключ на каждый объект",
"kalit bekor qilinsa — uziladi": "ключ отозван — объект отключён",
"MKB adapteri": "Адаптер МКБ",
"api.cgi · TCP push 9000": "api.cgi · TCP push 9000",
"yagona sxemaga o'giradi": "приводит к единой схеме",
"brend almashsa — shu blok": "сменился бренд — этот блок",
"MKB platformasi": "Платформа МКБ",
"obyekt kartasi, hodisa, vazifa": "карточка объекта, событие, задача",
"267 obyekt bitta ro'yxatda": "267 объектов в одном списке",
"nazorat indeksi qayta hisoblanadi": "индекс контроля пересчитывается",
"Reolink yechimida kameradan MKB platformasigacha bo'lgan yo'l": "Путь от камеры до платформы МКБ в решении Reolink",
"Yo'lda beshta chegara bor va ularning uchtasi bank ixtiyoridan tashqarida: kameraning Wi-Fi radiusi, LTE qoplamasi va operatorning NAT'i.": "На пути пять границ, и три из них вне распоряжения банка: радиус Wi-Fi камеры, покрытие LTE и NAT оператора.",
"Bank nazorat qiladigan yagona joy — tunnelning ikki uchi:": "Единственное, чем банк управляет, — два конца туннеля:",
"obyektdagi router va DMZ'dagi konsentrator. Shuning uchun ulanishni har doim obyekt boshlaydi, bankning tashqi perimetrida esa bu yechim uchun birorta port ochilmaydi.": "роутер на объекте и концентратор в DMZ. Поэтому соединение всегда начинает объект, а на внешнем периметре банка для этого решения не открывается ни один порт.",

/* ============================ Yechim 02 ============================ */
"Kamera boshlaydigan ulanish": "Соединение начинает камера",
"Adapter boshlaydigan so'rov": "Запрос начинает адаптер",
"chiquvchi": "исходящее",
"1,8 KB/hodisa": "1,8 КБ на событие",
"APN tunneli": "туннель APN",
"YO'L 01": "ПУТЬ 01",
"YO'L 02": "ПУТЬ 02",
"YO'L 03": "ПУТЬ 03",
"pilot bosqichi uchun": "для этапа пилота",
"oddiy SIM yetadi": "хватает обычной SIM",
"Kamera": "Камера",
"ISUP rejimi yoqilgan": "включён режим ISUP",
"oddiy SIM, sozlash 10 daqiqa": "обычная SIM, настройка 10 минут",
"kulrang IP, o'tib ketadi": "серый IP, проходит насквозь",
"sozlash talab qilinmaydi": "настройка не требуется",
"ISUP qabul qiluvchi": "Приёмник ISUP",
"kamera o'zi ro'yxatdan o'tadi": "камера регистрируется сама",
"video ham shu kanalda": "видео идёт тем же каналом",
"Korporativ APN": "Корпоративный APN",
"yuz obyektdan keyin": "после сотни объектов",
"arzonlashadi": "становится дешевле",
"SIM bank APN'ida": "SIM в APN банка",
"10.20.0.41 — ichki manzil": "10.20.0.41 — внутренний адрес",
"alohida shartnoma kerak": "нужен отдельный договор",
"obyektlar bitta tarmoqda": "объекты в одной сети",
"so'rovni o'zi yuboradi": "запрос отправляет сам",
"ISUP ham, NAT ham kerak emas": "ни ISUP, ни NAT не нужны",
"Router va VPN": "Роутер и VPN",
"istalgan brend uchun": "под любой бренд",
"+3,2 Vt qo'shimcha": "+3,2 Вт сверху",
"Kamera va 4G router": "Камера и 4G-роутер",
"kamera routerga kabel bilan": "камера к роутеру кабелем",
"quvvat byudjetiga +3,2 Vt": "+3,2 Вт к энергобюджету",
"Oddiy SIM": "Обычная SIM",
"operator hech narsa bilmaydi": "оператор ничего не знает",
"tunnel ichi shifrlangan": "внутри туннеля всё зашифровано",
"brend almashsa ham o'zgarmaydi": "не меняется при смене бренда",
"Uchala yo'lda ham bankning tashqi perimetrida birorta port ochilmaydi: ulanishni har doim obyekt tomoni boshlaydi.": "Ни на одном из трёх путей на внешнем периметре банка не открывается ни один порт: соединение всегда начинает сторона объекта.",
"Oq IP bo'lmagan SIM bilan ulanishning uchta yo'li": "Три пути подключения при SIM без белого IP",
"Yo'l tanlovi texnik emas,": "Выбор пути — вопрос не технический,",
"bosqich masalasi.": "а вопрос этапа.",
"Pilotda ISUP olinadi: u bugun, operator bilan yozishmasiz ishlaydi. Yuz obyektdan keyin korporativ APN arzonlashadi va ISAPI bilan RTSP adapterdan to'g'ridan-to'g'ri ochiladi. Router va VPN esa brend aralashgan portfel uchun: u qimmatroq va quvvat byudjetiga 3,2 Vt qo'shadi, lekin kelgusi tenderda brend o'zgarsa, platforma tomonida hech narsa qayta yozilmaydi.": "В пилоте берут ISUP: он работает сегодня и не требует переписки с оператором. После сотни объектов корпоративный APN становится дешевле, и ISAPI с RTSP открываются из адаптера напрямую. Роутер и VPN — для портфеля со смешанными брендами: дороже и добавляет 3,2 Вт к энергобюджету, зато при смене бренда на следующем тендере на стороне платформы не переписывается ничего.",

/* ============================ Yechim 03 ============================ */
"Kamera yuboradi": "Отправляет камера",
"Adapter yuboradi": "Отправляет адаптер",
"Operator NAT'i — bu chiziqni faqat obyekt kesib o'tadi": "NAT оператора — эту линию пересекает только объект",
"Auto Register — kamera har 30 soniyada serverga o'zi ulanadi": "Auto Register — камера сама подключается к серверу каждые 30 секунд",
"Sessiya ochildi: seriya raqami obyekt kartasiga bog'landi": "Сессия открыта: серийный номер привязан к карточке объекта",
"Code=VideoMotion;action=Start — hodisa shu ochiq kanalda keladi": "Code=VideoMotion;action=Start — событие приходит по этому открытому каналу",
"ptz.cgi?code=GotoPreset&arg2=3 — kamera darvozaga buriladi": "ptz.cgi?code=GotoPreset&arg2=3 — камера поворачивается к воротам",
"RTSP subtype=1 — oqim faqat operator so'raganda ochiladi": "RTSP subtype=1 — поток открывается только по запросу оператора",
"quyosh paneli, 4G, oq IP yo'q": "солнечная панель, 4G, белого IP нет",
"Auto Register qabul qiluvchi": "приёмник Auto Register",
"Ketma-ketlikning birinchi o'qi eng muhimi:": "Первая стрелка последовательности важнее всех:",
"ulanishni kamera boshlaydi.": "соединение начинает камера.",
"Shundan keyin kanal ochiq qoladi va 2–6-qadamlar bir xil TCP sessiyasi ichida yuriladi — adapter kameraga «murojaat qilmaydi», u shunchaki ochiq kanalga yozadi. Shuning uchun operator NAT'i to'siq bo'lmaydi va bank perimetrida port ochilmaydi. Kanal uzilsa kamera 30 soniyadan keyin qayta ulanadi, uzilish oralig'i esa kamera holati sifatida qayd etiladi.": "После этого канал остаётся открытым, и шаги 2–6 идут внутри одной TCP-сессии — адаптер к камере не «обращается», он просто пишет в открытый канал. Поэтому NAT оператора не становится преградой, а на периметре банка не открывается порт. При обрыве камера переподключается через 30 секунд, а интервал обрыва фиксируется как состояние камеры.",
"Auto Register: kamera va adapter orasidagi buyruqlar ketma-ketligi": "Auto Register: последовательность команд между камерой и адаптером",

/* ============================ Yechim 04 ============================ */
"Quvvat": "Питание",
"Ma'lumot": "Данные",
"Akkumulyator bloki": "Аккумуляторный блок",
"Shkaf korpusi, IP54": "Корпус шкафа, IP54",
"SHKAF · 600 × 800 × 250 mm · IP54": "ШКАФ · 600 × 800 × 250 мм · IP54",
"DIN reyka,": "DIN-рейка,",
"olti modul": "шесть модулей",
"Quyosh paneli": "Солнечная панель",
"2 × 200 Vt, 48 V": "2 × 200 Вт, 48 В",
"4G antenna": "Антенна 4G",
"12 dBi, tomda": "12 дБи, на крыше",
"Bank tunneli": "Туннель банка",
"Kamera va NVR": "Камера и регистратор",
"48 V PoE+, 30 Vt": "48 В PoE+, 30 Вт",
"Ikki avtomat": "Два автомата",
"panel 16 A · yuklama 10 A · servisda alohida uziladi": "панель 16 А · нагрузка 10 А · при сервисе снимаются раздельно",
"MPPT kontroller": "Контроллер MPPT",
"48 V / 30 A · PWM dan 22% ko'p energiya yig'adi": "48 В / 30 А · собирает на 22% больше энергии, чем PWM",
"4G router, ikki SIM": "4G-роутер, две SIM",
"SNMP v3 bilan so'raladi: RSRP, SINR, faol SIM, trafik": "опрашивается по SNMP v3: RSRP, SINR, активная SIM, трафик",
"PoE injektor": "PoE-инжектор",
"48 V to'g'ridan-to'g'ri — o'zgartirish yo'qotishi yo'q": "48 В напрямую — без потерь на преобразовании",
"Modbus shlyuz": "Шлюз Modbus",
"RS-485 → TCP · adapter har 5 daqiqada o'qiydi": "RS-485 → TCP · адаптер читает каждые 5 минут",
"LiFePO4 48 V 100 A·soat — ishchi blok": "LiFePO4 48 В 100 А·ч — рабочий блок",
"4,6 kVt·soat foydali · 32 kg · o'z BMS'i bilan": "4,6 кВт·ч полезной ёмкости · 32 кг · со своей BMS",
"Ikkinchi blok — rotatsiya uchun": "Второй блок — для ротации",
"filialda zaryadlanadi, tashrifda almashtiriladi": "заряжается в филиале, меняется при выезде",
"Shkafning o'z telemetriyasi": "Собственная телеметрия шкафа",
"Ichki harorat: −20…+60 °C": "Внутренняя температура: −20…+60 °C",
"Qopqoq ochilishi — tamper kontakti": "Вскрытие крышки — контакт тампера",
"Zaryad foizi va qolgan kun": "Процент заряда и остаток дней",
"0 °C dan past — zaryad to'xtaydi": "ниже 0 °C — заряд прекращается",
"Uchalasi bitta hodisa sxemasida": "Все три — в одной схеме события",
"Shkafda hech narsa 220 V bilan ishlamaydi: butun tizim 48 V doimiy tokda quriladi va elektr montaj ruxsatnomasi talab qilinmaydi.": "В шкафу ничто не работает от 220 В: вся система строится на постоянных 48 В и допуска на электромонтаж не требует.",
"Shkafning tartibi tasodifiy emas.": "Порядок в шкафу не случаен.",
"Og'ir bloklar pastda": "Тяжёлые блоки внизу",
"— ularni almashtirishda narvon kerak bo'lmaydi va shkafning og'irlik markazi past qoladi.": "— при замене не нужна стремянка, а центр тяжести шкафа остаётся низким.",
"Avtomatlar tepada": "Автоматы наверху",
"— servischi qopqoqni ochishi bilan birinchi ko'radigan narsa uzgich bo'ladi.": "— открыв крышку, сервисник первым делом видит выключатель.",
"Shlyuz bloklarga yaqin": "Шлюз рядом с блоками",
"— RS-485 chizig'i qanchalik qisqa bo'lsa, quyosh kontrollerining shovqiniga shunchalik kam bog'liq bo'ladi.": "— чем короче линия RS-485, тем меньше она зависит от помех солнечного контроллера.",
"Quvvat shkafining ichki tuzilishi: avtomatlar, kontroller, router, injektor, shlyuz va ikkita akkumulyator bloki": "Внутреннее устройство силового шкафа: автоматы, контроллер, роутер, инжектор, шлюз и два аккумуляторных блока",

/* ============================ Yechim 05 ============================ */
"Ishonchli radio · 3/3": "Уверенное радио · 3/3",
"Zaif radio · 1/3, kengaytirgich kerak": "Слабое радио · 1/3, нужен ретранслятор",
"Hub va kengaytirgich": "Хаб и ретранслятор",
"Metall javon": "Металлический стеллаж",
"Asosiy darvoza": "Главные ворота",
"OMBOR ZALI · 24 × 19 m": "СКЛАДСКОЙ ЗАЛ · 24 × 19 м",
"OFIS VA YO'LAK": "ОФИС И КОРИДОР",
"TEXNIK XONA": "ТЕХНИЧЕСКОЕ ПОМЕЩЕНИЕ",
"8 m · 3/3": "8 м · 3/3",
"9 m · 3/3": "9 м · 3/3",
"23 m · 1 devor · 3/3": "23 м · 1 стена · 3/3",
"20 m · ochiq zal · 3/3": "20 м · открытый зал · 3/3",
"14 m · 1 devor · 2/3": "14 м · 1 стена · 2/3",
"16 m · metall · 1/3": "16 м · металл · 1/3",
"10 metr": "10 метров",
"ofis, balandlik 1,8 m": "офис, высота 1,8 м",
"yo'lak eshigi ustida": "над дверью коридора",
"asosiy darvoza": "главные ворота",
"zal, 12 m radius": "зал, радиус 12 м",
"javon oralig'i, surat bilan": "проход между стеллажами, со снимком",
"ofis shifti": "потолок офиса",
"isitish tuguni ostida": "под узлом отопления",
"So'rov oralig'i — 36 soniya": "Интервал опроса — 36 секунд",
"Har so'rovda hub datchikning tirikligini": "При каждом опросе хаб проверяет, жив ли",
"tekshiradi; javob kelmasa — hodisa ochiladi": "датчик; нет ответа — открывается событие",
"Katalogda 2 000 m, binoda 30 m": "В каталоге 2 000 м, в здании 30 м",
"Har g'isht devor masofani uchdan biriga": "Каждая кирпичная стена режет дальность до",
"qisqartiradi, metall javon — yarmiga": "трети, металлический стеллаж — вдвое",
"Javonlar ortidagi o'lik zona": "Мёртвая зона за стеллажами",
"Bu yerda ReX qo'yilmaydi — javon ustiga": "Здесь ReX не ставят — датчик поднимают",
"chiqilib, MotionCam hubga ko'rinadigan qilinadi": "над стеллажом, в прямую видимость хаба",
"Reja ikkita oddiy xatoni ko'rsatadi.": "План показывает две типовые ошибки.",
"Birinchisi — hubni ofisga qo'yish:": "Первая — поставить хаб в офис:",
"u yerdan darvozagacha ikkita devor bor va signal ReXsiz yetmaydi.": "оттуда до ворот две стены, и без ReX сигнал не доходит.",
"Ikkinchisi — MotionCam'ni javonlar orasiga osish:": "Вторая — повесить MotionCam между стеллажами:",
"metall javon 868 MGs to'lqinni yutadi va o'rnatuvchi buni faqat sinov rejimida ko'radi. Shu sababli har bir datchik o'rnatilgandan keyin hub ilovasida signal darajasi o'lchanadi va dalolatnomaga yoziladi: 2/3 dan past joy qabul qilinmaydi.": "металл поглощает волну 868 МГц, и монтажник увидит это только в режиме проверки. Поэтому после установки каждого датчика уровень сигнала замеряют в приложении хаба и вносят в акт: место слабее 2/3 не принимается.",
"Ombor va ofis rejasi: hub, datchiklar va ular orasidagi radio aloqa": "План склада и офиса: хаб, датчики и радиосвязь между ними",

/* --- yechim-01…05 sahifalarining tarjimasiz qolgan matnlari --- */
"Kameralarning o'zi RTSP ham, ONVIF ham bermaydi: bu protokollar faqat Home Hub orqali ochiladi. Hub — komplektning majburiy bo'g'ini, uni «tejash» mumkin emas.": "Сами камеры не отдают ни RTSP, ни ONVIF: эти протоколы открываются только через Home Hub. Хаб — обязательное звено комплекта, «сэкономить» на нём нельзя.",
"Toshkentda 21-dekabrda quyosh 07:50 da chiqib, 17:15 da botadi va peshinda ufqdan atigi 25° ko'tariladi. Panel foydali tokni kuniga olti-yetti soat beradi, qolgan o'n yetti soat butun yuklama akkumulyatorda turadi.": "В Ташкенте 21 декабря солнце восходит в 07:50, заходит в 17:15 и в полдень поднимается над горизонтом всего на 25°. Панель даёт полезный ток шесть-семь часов в сутки, остальные семнадцать вся нагрузка держится на аккумуляторе.",
"−4 °C dagi akkumulyator": "Аккумулятор при −4 °C",
"Panelsiz variantda o'sha akkumulyator 156 Vt·soatlik yuklamada 7,4 kun yetadi: servis haftada bir marta boradi. Panel narxining o'zi bir yillik tashriflardan arzon — shuning uchun panel «ixtiyoriy qo'shimcha» emas, smetaning majburiy qatori.": "Без панели тот же аккумулятор при нагрузке 156 Вт·ч держит 7,4 дня: сервис выезжает раз в неделю. Сама панель дешевле годовых выездов — поэтому она не «необязательное дополнение», а обязательная строка сметы.",
"LiFePO4 blokning BMS'i 0 °C dan past haroratda zaryadni to'xtatishi shart. Bu funksiya yo'q blokni sovuq kunda quyosh kontrolleri zaryadlaydi va akkumulyator bir qishda qaytarib bo'lmaydigan darajada sig'imini yo'qotadi.": "BMS блока LiFePO4 обязана прекращать заряд при температуре ниже 0 °C. Блок без этой функции солнечный контроллер в мороз всё равно зарядит, и за одну зиму аккумулятор безвозвратно потеряет ёмкость.",
"Hikvision'ning quyosh-4G liniyasida bir-biriga o'xshamaydigan ikkita mahsulot bor. Katalogda ikkalasi ham «avtonom quyosh kamerasi» deb ataladi, ammo farq dekabrda va sovuqda ko'rinadi — ya'ni aynan bankka kerak bo'lgan paytda.": "В линейке Hikvision «солнце + 4G» есть два непохожих продукта. В каталоге оба называются «автономная солнечная камера», но разница проявляется в декабре и на морозе — то есть именно тогда, когда банку это и нужно.",
"Ixcham sinf 0 °C dan past haroratda na ishlaydi, na zaryadlanadi. Toshkentda dekabr tunlari muntazam shu chegaradan pastga tushadi, shuning uchun ochiq joyga faqat perimetr sinfi qo'yiladi.": "Компактный класс ниже 0 °C ни работает, ни заряжается. Декабрьские ночи в Ташкенте регулярно опускаются ниже этого порога, поэтому на открытой площадке ставят только периметральный класс.",
"Janubga, 55–60° qiyalikda": "На юг, с наклоном 55–60°",
"Bu Yechim 02 dagi kabi «bitta korpus» emas: panel, akkumulyator, kontroller va kamera alohida qismlar va ular alohida sotiladi. Smetani tuzayotganda akkumulyator komplektga kirmasligini birinchi bo'lib tekshiring.": "Это не «единый корпус», как в Решении 02: панель, аккумулятор, контроллер и камера — отдельные части и продаются порознь. Составляя смету, первым делом проверьте, что аккумулятор в комплект не входит.",
"Aylanuvchi kamerada iste'mol o'zgarmas emas: eng tejamkor va eng och rejim orasida uch yuz barobar farq bor. Shuning uchun qishki nazorat rejasi «kamera nima qiladi» degan savoldan emas, «qaysi rejimda necha soat turadi» degan savoldan boshlanadi.": "У поворотной камеры потребление непостоянно: между самым экономным и самым прожорливым режимом разница в триста раз. Поэтому зимний план наблюдения начинается не с вопроса «что делает камера», а с вопроса «сколько часов она проводит в каком режиме».",
"Bu yechimning muhandislik jihatdan eng jiddiy qismi kamera emas, ustun. 125 Vt panel 0,6 m² yelkanga teng va u to'rt metr balandlikda turadi — poydevor xuddi shu yuk uchun hisoblanadi.": "Самая серьёзная инженерная часть этого решения — не камера, а опора. Панель 125 Вт — это парус площадью 0,6 м², и он стоит на четырёхметровой высоте; фундамент считают именно под эту нагрузку.",
"Sovuq bu yechimga zarar qilmaydi. LiFePO4 razryadi −20 °C gacha ruxsat etiladi, 0 °C dan past zaryad taqiqi esa bazada hal bo'ladi: bo'shagan blok isitiladigan xonada zaryadlanadi.": "Холод этому решению не вредит. Разряд LiFePO4 допускается до −20 °C, а запрет заряда ниже 0 °C снимается на базе: разряженный блок заряжают в отапливаемом помещении.",
"Hub va datchiklar −10…+40 °C ga mo'ljallangan. Isitilmaydigan binoda hub ichki xonaga qo'yiladi va sovuqda batareya muddati qisqaradi: platforma har datchikning batareya foizini alohida kuzatadi.": "Хаб и датчики рассчитаны на −10…+40 °C. В неотапливаемом здании хаб ставят во внутреннее помещение, а на морозе ресурс батарей сокращается: платформа ведёт процент заряда по каждому датчику отдельно.",
"Batareyali datchik yong'in signalizatsiyasi talabini yopishi qoidalarda yozilmagan. Bu masala IIV yong'in xavfsizligi organi bilan alohida kelishiladi: shu kelishuvsiz obyekt loyihada «himoyalangan» deb belgilanmaydi.": "Возможность закрыть требование пожарной сигнализации автономным извещателем в правилах не прописана. Вопрос согласуется с органом пожарного надзора МВД отдельно: без этого согласования объект в проекте не отмечается как «защищённый».",
"Bu yechim savolni o'zgartiradi: «nima bo'ldi» emas, «kimdir kirdimi va yong'in yo'qmi». Shu savol yetarli bo'lgan obyektda u eng arzon va eng ishonchli variant.": "Это решение меняет сам вопрос: не «что произошло», а «заходил ли кто-то и нет ли пожара». Там, где такого вопроса достаточно, оно самое дешёвое и самое надёжное."

});
